In [4]:
import pandas as pd

In [50]:
df = pd.read_excel("OneWayHetvii.xlsx")
df

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,flight_number,Calculated_Flight_Price
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,G84279,4810.84
1,2,0,firstClass,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,6E4357O,3580.20
2,7,0,economic,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,AI3905,3785.16
3,11,0,premium,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,SG2659K,3669.93
4,13,0,firstClass,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,G83184,5780.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,AI5405C,2949.67
39975,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,QP2071,5988.03
39976,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,QP589J,4272.88
39977,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,6E4801N,3349.72
39978,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,6E4290X,1673.92

In [51]:
df_loc = pd.read_excel("AirportCoordinates.xlsx")
df_loc

,LocationID,Name,Address,City,Latitude,Longitude
0,1,Coimbatore International Airport (CJB),"Coimbatore International Airport, Avinashi Roa...",Coimbatore,11.030030,77.043380
1,2,Birsa Munda Airport (IXR),"Birsa Munda Airport, Hinoo, Ranchi, Jharkhand ...",Ranchi,23.314250,85.321670
2,3,Goa International Airport (GOI),"Goa International Airport, Airport Road, Dabol...",Dabolim,15.380830,73.831420
3,4,Sardar Vallabhbhai Patel International Airport...,Sardar Vallabhbhai Patel International Airport...,Ahmedabad,23.077240,72.634650
4,5,Rajiv Gandhi International Airport (HYD),"Rajiv Gandhi International Airport, Shamshabad...",Hyderabad,17.231320,78.429860
5,6,Agartala Airport (IXA),"Agartala Airport, Agartala, Tripura 799009",Khowai,23.886980,91.240450
6,7,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Navi Mumbai,19.088690,72.867920
7,8,Pune International Airport (PNQ),"Pune International Airport, Lohegaon, Pune, Ma...",Pune,18.340000,73.550000
8,9,Vijayawada Airport (VGA),"Vijayawada Airport, Gannavaram, Andhra Pradesh...",Vijayawada,16.530430,80.796850
9,10,Gwalior Airport (GWL),"Gwalior Airport, Maharajpur, Gwalior, Madhya P...",Gwalior,26.293340,78.227750
10,11,Kempegowda International Airport (BLR),"Kempegowda International Airport, Devanahalli,...",Bengaluru,13.200710,77.708790
11,12,Lokpriya Gopinath Bordoloi International Airpo...,Lokpriya Gopinath Bordoloi International Airpo...,Guwahati,26.106090,91.585940
12,13,Bilaspur Airport (PAB),"Bilaspur Airport, Chakarbhata, Bilaspur, Chhat...",Bilaspur,21.988400,82.110980
13,14,Swami Vivekananda Airport (RPR),"Swami Vivekananda Airport, Ramchandi, Naya Rai...",Raipur,21.180400,81.738800
14,15,Puducherry Airport (PNY),"Puducherry Airport, Lawspet, Puducherry 605008",Puducherry,11.580000,79.480000
15,16,Sonari Airport (IXW),"Sonari Airport, Sonari, Jamshedpur, Jharkhand ...",Jamshedpur,22.480000,86.100000
16,17,Nashik International Airport (ISK),"Nashik International Airport, Ozar, Nashik, Ma...",Nashik,20.119444,73.913611
17,18,Mopa International Airport (GOX),"Mopa International Airport, Mopa, Pernem, Goa ...",Mopa,15.731300,73.868170
18,19,Prayagraj Airport (IXD),"Prayagraj Airport, Bamrauli, Prayagraj, Uttar ...",Prayagraj,25.440060,81.733870
19,20,Vadodara Airport (BDQ),"Vadodara Airport, Harni Road, Vadodara, Gujara...",Vadodara,22.336200,73.226300
20,21,Ludhiana Airport (LUH),"Ludhiana Airport, Sahnewal, Ludhiana, Punjab 1...",Ludhiana,30.854700,75.952600
21,22,Raigarh Airport (None),"Raigarh Airport, Kondatarai, Raigarh, Chhattis...",Raigarh,21.823889,83.360278
22,23,Chennai International Airport (MAA),"Chennai International Airport, GST Road, Meena...",Chennai,12.988330,80.165780
23,24,Biju Patnaik International Airport (BAI),"Biju Patnaik International Airport, Airport Ro...",Puri,20.244360,85.817780
24,25,Tirupati Airport (TIR),"Tirupati Airport, Renigunta, Andhra Pradesh 51...",Tirupati,13.632500,79.543300
25,26,Dehradun Airport (DED),"Dehradun Airport, Jolly Grant, Dehradun, Uttar...",Dehradun,30.189700,78.180300
26,27,Sheikh ul-Alam International Airport (SXR),"Sheikh ul-Alam International Airport, Aerodrom...",Srinagar,33.987100,74.774200
27,28,Indira Gandhi International Airport (DEL),"Indira Gandhi International Airport, New Delhi...",Delhi NCR,28.566500,77.103090
28,29,Donyi Polo Airport (HGI),"Donyi Polo Airport, Hollongi, Itanagar, Arunac...",Itanagar,26.970000,93.664722
29,30,Lal Bahadur Shastri International Airport (VNS),"Lal Bahadur Shastri International Airport, Bab...",Varanasi,25.452222,82.859444
30,31,Rupsi Airport (RUP),"Rupsi Airport, Rupsi, Assam 783372",Dhubri,26.141180,89.906870
31,32,Netaji Subhas Chandra Bose International Airpo...,Netaji Subhas Chandra Bose International Airpo...,Kolkata,22.654740,88.446720
32,33,Pakyong Airport (PYG),"Pakyong Airport, Pakyong, Sikkim 737106",Gangtok,27.227560,88.585960
33,34,Shillong Airport (SHL),"Shillong Airport, Umroi, Meghalaya 793103",Shillong,25.703600,91.978700
34,35,Sri Guru Ram Dass Jee International Airport (ATQ),"Sri Guru Ram Dass Jee International Airport, A...",Amritsar,31.709590,74.797260
35,36,Raja Bhoj Airport (BHO),"Raja Bhoj Airport, Gandhi Nagar, Bhopal, Madhy...",Bhopal,23.287470,77.337370
36,37,Jaipur International Airport (JAI),"Jaipur International Airport, Airport Road, Sa...",Jaipur,26.824190,75.812160
37,38,Kullu–Manali Airport (KUU),"Kullu–Manali Airport, Bhuntar, Kullu, Himachal...",Kullu-Manali,31.876667,77.154444
38,39,Ayodhya Airport (under construction),"Ayodhya Airport, Ayodhya, Uttar Pradesh 224123",Ayodhya,26.748034,82.150781
39,40,Biju Patnaik International Airport (BBI),"Biju Patnaik International Airport, Airport Ro...",Bhubaneswar,20.244360,85.817780
40,41,Trivandrum International Airport (TRV),"Trivandrum International Airport, Vallakkadavu...",Thiruvananthapuram,8.482120,76.920110
41,42,Kota Airport (KTU),"Kota Airport, Aerodrome Circle, Kota, Rajastha...",Kota,25.160220,75.845630
42,43,Surat Airport (STV),"Surat Airport, Dumas Road, Surat, Gujarat 395007",Surat,21.114100,72.741800
43,44,Maharana Pratap Airport (UDR),"Maharana Pratap Airport, NH 76, Dabok, Udaipur...",Udaipur,24.617840,73.896620
44,45,Diu Airport (DIU),"Diu Airport, Diu, Daman and Diu 362520",Diu,20.713100,70.921100
45,46,Chandigarh International Airport (IXC),"Chandigarh International Airport, Mohali, Punj...",Chandigarh,30.673500,76.788500
46,47,Shimla Airport (SLV),"Shimla Airport, Jubbarhatti, Shimla, Himachal ...",Shimla,31.081800,77.068000
47,48,Imphal International Airport (IMF),"Imphal International Airport, Imphal, Manipur ...",Imphal,24.759950,93.896700
48,49,Hisar Airport (HSS),"Hisar Airport, Hisar, Haryana 125001",Hisar,29.179440,75.755340
49,50,Visakhapatnam Airport (VTZ),"Visakhapatnam Airport, NAD Junction, Visakhapa...",Visakhapatnam,17.721200,83.224500
50,51,Devi Ahilya Bai Holkar Airport (IDR),"Devi Ahilya Bai Holkar Airport, Indore, Madhya...",Indore,22.721667,75.800833
51,52,Mysore Airport (MYQ),"Mysore Airport, Mandakalli, Mysuru, Karnataka ...",Mysuru,12.307200,76.649700
52,53,Jay Prakash Narayan Airport (PAT),"Jay Prakash Narayan Airport, Sheikhpura, Patna...",Patna,25.591389,85.089167
53,54,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Mumbai,19.088690,72.867920

In [52]:
code_to_name = dict(zip(df_loc['City'], df_loc['Name']))

In [53]:
df['Departure'] = df['Departure'].map(code_to_name)
df['Arrival'] = df['Arrival'].map(code_to_name)

In [56]:
df = df.drop(columns=['Flight Distance (km)', 'Flight Duration (hh:mm)'])

In [57]:
df

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Departure Time,Arrival Time,flight_number,Calculated_Flight_Price
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),03:59,05:05,G84279,4810.84
1,2,0,firstClass,IndiGo,10/10/2019,Birsa Munda Airport (IXR),Shillong Airport (SHL),01:02,01:49,6E4357O,3580.20
2,7,0,economic,Air India,14/11/2019,Goa International Airport (GOI),Birsa Munda Airport (IXR),00:15,01:54,AI3905,3785.16
3,11,0,premium,SpiceJet,12/12/2019,Sardar Vallabhbhai Patel International Airport...,Raigarh Airport (None),17:35,18:49,SG2659K,3669.93
4,13,0,firstClass,GoAir,26/12/2019,Rajiv Gandhi International Airport (HYD),Netaji Subhas Chandra Bose International Airpo...,18:18,19:36,G83184,5780.44
...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,premium,Air India,18/06/2020,Devi Ahilya Bai Holkar Airport (IDR),Goa International Airport (GOI),04:28,05:24,AI5405C,2949.67
39975,135939,1339,premium,Akasa Air,25/06/2020,Sardar Vallabhbhai Patel International Airport...,Shillong Airport (SHL),13:37,15:48,QP2071,5988.03
39976,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj Airport (IXD),Visakhapatnam Airport (VTZ),17:27,18:25,QP589J,4272.88
39977,135941,1339,firstClass,IndiGo,07/09/2020,Surat Airport (STV),Goa International Airport (GOI),00:46,01:29,6E4801N,3349.72
39978,135942,1339,economic,IndiGo,16/07/2020,Raja Bhoj Airport (BHO),Prayagraj Airport (IXD),12:14,12:48,6E4290X,1673.92

In [8]:
# import requests
# import pandas as pd

# def get_place_coordinates(place):
#     username = "HetviPatel"  # Replace with your GeoNames username
#     url = f"http://api.geonames.org/searchJSON?q={place}&maxRows=1&username={username}"

#     response = requests.get(url)
#     data = response.json()

#     if "geonames" in data and len(data["geonames"]) > 0:
#         lat = float(data["geonames"][0]["lat"])
#         lon = float(data["geonames"][0]["lng"])
#         return lat, lon

#     # If no GeoNames results, check Wikipedia results
#     wiki_url = f"http://api.geonames.org/wikipediaSearchJSON?q={place}&maxRows=1&username={username}"
#     wiki_response = requests.get(wiki_url)
#     wiki_data = wiki_response.json()

#     if "geonames" in wiki_data and len(wiki_data["geonames"]) > 0:
#         lat = float(wiki_data["geonames"][0]["lat"])
#         lon = float(wiki_data["geonames"][0]["lng"])
#         return lat, lon

#     return None, None  # Return None if no coordinates found

# # Apply function correctly
# df[['Departure_Lat', 'Departure_Lon']] = df['Departure'].apply(lambda x: pd.Series(get_place_coordinates(x)))
# df[['Arrival_Lat', 'Arrival_Lon']] = df['Arrival'].apply(lambda x: pd.Series(get_place_coordinates(x)))

In [9]:
df

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Departure Time,Arrival Time,flight_number,Calculated_Flight_Price
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),03:59,05:05,G84279,4810.84
1,2,0,firstClass,IndiGo,10/10/2019,Birsa Munda Airport (IXR),Shillong Airport (SHL),01:02,01:49,6E4357O,3580.20
2,7,0,economic,Air India,14/11/2019,Goa International Airport (GOI),Birsa Munda Airport (IXR),00:15,01:54,AI3905,3785.16
3,11,0,premium,SpiceJet,12/12/2019,Sardar Vallabhbhai Patel International Airport...,Raigarh Airport (None),17:35,18:49,SG2659K,3669.93
4,13,0,firstClass,GoAir,26/12/2019,Rajiv Gandhi International Airport (HYD),Netaji Subhas Chandra Bose International Airpo...,18:18,19:36,G83184,5780.44
...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,premium,Air India,18/06/2020,Devi Ahilya Bai Holkar Airport (IDR),Goa International Airport (GOI),04:28,05:24,AI5405C,2949.67
39975,135939,1339,premium,Akasa Air,25/06/2020,Sardar Vallabhbhai Patel International Airport...,Shillong Airport (SHL),13:37,15:48,QP2071,5988.03
39976,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj Airport (IXD),Visakhapatnam Airport (VTZ),17:27,18:25,QP589J,4272.88
39977,135941,1339,firstClass,IndiGo,07/09/2020,Surat Airport (STV),Goa International Airport (GOI),00:46,01:29,6E4801N,3349.72
39978,135942,1339,economic,IndiGo,16/07/2020,Raja Bhoj Airport (BHO),Prayagraj Airport (IXD),12:14,12:48,6E4290X,1673.92

In [10]:
# GEONAMES_USERNAME = "HetviPatel"

# def get_coordinates_geonames(airport_name):
#     """Fetch latitude & longitude using GeoNames API"""
#     url = f"http://api.geonames.org/searchJSON?q={airport_name}&maxRows=1&username={GEONAMES_USERNAME}"
    
#     try:
#         response = requests.get(url)
#         data = response.json()
        
#         if "geonames" in data and len(data["geonames"]) > 0:
#             location = data["geonames"][0]
#             return float(location["lat"]), float(location["lng"])
#     except Exception as e:
#         print(f"GeoNames Error for {airport_name}: {e}")
    
#     return None  # If not found, return None

# def get_coordinates_wikipedia(airport_name):
#     """Fetch latitude & longitude from Wikipedia"""
#     try:
#         search_url = f"https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch={airport_name}&format=json"
#         search_response = requests.get(search_url).json()
        
#         if "query" in search_response and search_response["query"]["search"]:
#             page_title = search_response["query"]["search"][0]["title"]
#             page_url = f"https://en.wikipedia.org/w/api.php?action=query&prop=extracts&pageids={page_title}&format=json"
#             page_response = requests.get(page_url).json()
            
#             if "query" in page_response and "pages" in page_response["query"]:
#                 page_content = next(iter(page_response["query"]["pages"].values()))
                
#                 if "extract" in page_content:
#                     parsed_content = mwparserfromhell.parse(page_content["extract"])
                    
#                     for template in parsed_content.filter_templates():
#                         if "coord" in str(template):
#                             lat, lon = template.params[0], template.params[1]
#                             return float(lat), float(lon)
#     except Exception as e:
#         print(f"Wikipedia Error for {airport_name}: {e}")
    
#     return None  # If not found, return None

# def get_coordinates(airport_name):
#     """Try to fetch coordinates from GeoNames, if not found, try Wikipedia"""
#     coords = get_coordinates_geonames(airport_name)
#     if not coords:  # Fallback to Wikipedia if GeoNames fails
#         coords = get_coordinates_wikipedia(airport_name)
#     return coords

# def get_distance(departure, arrival):
#     """Calculate distance using Haversine formula"""
#     dep_coords = get_coordinates(departure)
#     arr_coords = get_coordinates(arrival)

#     if dep_coords and arr_coords:
#         return round(geodesic(dep_coords, arr_coords).kilometers, 2)  # Distance in km
#     return None

# def get_wikipedia_info(airport_name):
#     """Fetch airport description from Wikipedia API"""
#     url = f"https://en.wikipedia.org/api/rest_v1/page/summary/{airport_name.replace(' ', '_')}"
    
#     try:
#         response = requests.get(url)
#         data = response.json()
        
#         if "extract" in data:
#             return data["extract"]
#     except Exception as e:
#         print(f"Error fetching Wikipedia info for {airport_name}: {e}")
#         return None
    
#     return None

# # Load Data (Assume it's a CSV or DataFrame)
# # data = pd.read_csv("flight_data.csv")

# # Add Distance Column
# df["Distance_km"] = df.apply(lambda row: get_distance(row["Departure"], row["Arrival"]), axis=1)

In [11]:
# import time
# import requests

# def get_coordinates_geonames(location, username):
#     """Fetch coordinates from GeoNames API"""
#     base_url = "http://api.geonames.org/searchJSON"
#     params = {
#         "q": location,
#         "maxRows": 1,
#         "username": username,
#         "featureClass": "A",  # Airports are administrative locations
#     }
#     response = requests.get(base_url, params=params)
#     if response.status_code == 200:
#         data = response.json()
#         if "geonames" in data and len(data["geonames"]) > 0:
#             return data["geonames"][0]["lat"], data["geonames"][0]["lng"]
#     return None

# def get_coordinates_wikipedia(location):
#     """Fetch coordinates from Wikipedia API"""
#     base_url = "https://en.wikipedia.org/w/api.php"
#     params = {
#         "action": "query",
#         "format": "json",
#         "titles": location,
#         "prop": "coordinates"
#     }
#     response = requests.get(base_url, params=params)
#     if response.status_code == 200:
#         data = response.json()
#         pages = data.get("query", {}).get("pages", {})
#         for page in pages.values():
#             if "coordinates" in page:
#                 return page["coordinates"][0]["lat"], page["coordinates"][0]["lon"]
#     return None

# def fetch_airport_coordinates(airport_name, username):
#     """Get airport coordinates from GeoNames, fallback to Wikipedia if necessary"""
#     coords = get_coordinates_geonames(airport_name, username)
#     if coords is None:
#         coords = get_coordinates_wikipedia(airport_name)
#     return coords if coords else (None, None)

# # Example usage
# USERNAME = "HetviPatel"

# df[["Departure_Lat", "Departure_Lon"]] = df["Departure"].apply(lambda x: fetch_airport_coordinates(x, USERNAME)).apply(pd.Series)
# df[["Arrival_Lat", "Arrival_Lon"]] = df["Arrival"].apply(lambda x: fetch_airport_coordinates(x, USERNAME)).apply(pd.Series)

In [12]:
# df

In [59]:
df.to_excel('FlightWithAirport.xlsx', index=False)
from IPython.display import FileLink
FileLink('FlightWithAirport.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\FlightWithAirport.xlsx

In [13]:
dtframe = pd.read_excel("Location_Table.xlsx")
dtframe

,LocationID,Name,Address,City
0,1,Coimbatore International Airport (CJB),"Coimbatore International Airport, Avinashi Roa...",Coimbatore
1,2,Birsa Munda Airport (IXR),"Birsa Munda Airport, Hinoo, Ranchi, Jharkhand ...",Ranchi
2,3,Goa International Airport (GOI),"Goa International Airport, Airport Road, Dabol...",Dabolim
3,4,Sardar Vallabhbhai Patel International Airport...,Sardar Vallabhbhai Patel International Airport...,Ahmedabad
4,5,Rajiv Gandhi International Airport (HYD),"Rajiv Gandhi International Airport, Shamshabad...",Hyderabad
5,6,Agartala Airport (IXA),"Agartala Airport, Agartala, Tripura 799009",Khowai
6,7,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Navi Mumbai
7,8,Pune International Airport (PNQ),"Pune International Airport, Lohegaon, Pune, Ma...",Pune
8,9,Vijayawada Airport (VGA),"Vijayawada Airport, Gannavaram, Andhra Pradesh...",Vijayawada
9,10,Gwalior Airport (GWL),"Gwalior Airport, Maharajpur, Gwalior, Madhya P...",Gwalior
10,11,Kempegowda International Airport (BLR),"Kempegowda International Airport, Devanahalli,...",Bengaluru
11,12,Lokpriya Gopinath Bordoloi International Airpo...,Lokpriya Gopinath Bordoloi International Airpo...,Guwahati
12,13,Bilaspur Airport (PAB),"Bilaspur Airport, Chakarbhata, Bilaspur, Chhat...",Bilaspur
13,14,Swami Vivekananda Airport (RPR),"Swami Vivekananda Airport, Ramchandi, Naya Rai...",Raipur
14,15,Puducherry Airport (PNY),"Puducherry Airport, Lawspet, Puducherry 605008",Puducherry
15,16,Sonari Airport (IXW),"Sonari Airport, Sonari, Jamshedpur, Jharkhand ...",Jamshedpur
16,17,Nashik International Airport (ISK),"Nashik International Airport, Ozar, Nashik, Ma...",Nashik
17,18,Mopa International Airport (GOX),"Mopa International Airport, Mopa, Pernem, Goa ...",Mopa
18,19,Prayagraj Airport (IXD),"Prayagraj Airport, Bamrauli, Prayagraj, Uttar ...",Prayagraj
19,20,Vadodara Airport (BDQ),"Vadodara Airport, Harni Road, Vadodara, Gujara...",Vadodara
20,21,Ludhiana Airport (LUH),"Ludhiana Airport, Sahnewal, Ludhiana, Punjab 1...",Ludhiana
21,22,Raigarh Airport (None),"Raigarh Airport, Kondatarai, Raigarh, Chhattis...",Raigarh
22,23,Chennai International Airport (MAA),"Chennai International Airport, GST Road, Meena...",Chennai
23,24,Biju Patnaik International Airport (BBI),"Biju Patnaik International Airport, Airport Ro...",Puri
24,25,Tirupati Airport (TIR),"Tirupati Airport, Renigunta, Andhra Pradesh 51...",Tirupati
25,26,Dehradun Airport (DED),"Dehradun Airport, Jolly Grant, Dehradun, Uttar...",Dehradun
26,27,Sheikh ul-Alam International Airport (SXR),"Sheikh ul-Alam International Airport, Aerodrom...",Srinagar
27,28,Indira Gandhi International Airport (DEL),"Indira Gandhi International Airport, New Delhi...",Delhi NCR
28,29,Donyi Polo Airport (HGI),"Donyi Polo Airport, Hollongi, Itanagar, Arunac...",Itanagar
29,30,Lal Bahadur Shastri International Airport (VNS),"Lal Bahadur Shastri International Airport, Bab...",Varanasi
30,31,Rupsi Airport (RUP),"Rupsi Airport, Rupsi, Assam 783372",Dhubri
31,32,Netaji Subhas Chandra Bose International Airpo...,Netaji Subhas Chandra Bose International Airpo...,Kolkata
32,33,Pakyong Airport (PYG),"Pakyong Airport, Pakyong, Sikkim 737106",Gangtok
33,34,Shillong Airport (SHL),"Shillong Airport, Umroi, Meghalaya 793103",Shillong
34,35,Sri Guru Ram Dass Jee International Airport (ATQ),"Sri Guru Ram Dass Jee International Airport, A...",Amritsar
35,36,Raja Bhoj Airport (BHO),"Raja Bhoj Airport, Gandhi Nagar, Bhopal, Madhy...",Bhopal
36,37,Jaipur International Airport (JAI),"Jaipur International Airport, Airport Road, Sa...",Jaipur
37,38,Kullu–Manali Airport (KUU),"Kullu–Manali Airport, Bhuntar, Kullu, Himachal...",Kullu-Manali
38,39,Ayodhya Airport (under construction),"Ayodhya Airport, Ayodhya, Uttar Pradesh 224123",Ayodhya
39,40,Biju Patnaik International Airport (BBI),"Biju Patnaik International Airport, Airport Ro...",Bhubaneswar
40,41,Trivandrum International Airport (TRV),"Trivandrum International Airport, Vallakkadavu...",Thiruvananthapuram
41,42,Kota Airport (KTU),"Kota Airport, Aerodrome Circle, Kota, Rajastha...",Kota
42,43,Surat Airport (STV),"Surat Airport, Dumas Road, Surat, Gujarat 395007",Surat
43,44,Maharana Pratap Airport (UDR),"Maharana Pratap Airport, NH 76, Dabok, Udaipur...",Udaipur
44,45,Diu Airport (DIU),"Diu Airport, Diu, Daman and Diu 362520",Diu
45,46,Chandigarh International Airport (IXC),"Chandigarh International Airport, Mohali, Punj...",Chandigarh
46,47,Shimla Airport (SLV),"Shimla Airport, Jubbarhatti, Shimla, Himachal ...",Shimla
47,48,Imphal International Airport (IMF),"Imphal International Airport, Imphal, Manipur ...",Imphal
48,49,Hisar Airport (HSS),"Hisar Airport, Hisar, Haryana 125001",Hisar
49,50,Visakhapatnam Airport (VTZ),"Visakhapatnam Airport, NAD Junction, Visakhapa...",Visakhapatnam
50,51,Devi Ahilya Bai Holkar Airport (IDR),"Devi Ahilya Bai Holkar Airport, Indore, Madhya...",Indore
51,52,Mysore Airport (MYQ),"Mysore Airport, Mandakalli, Mysuru, Karnataka ...",Mysuru
52,53,Jay Prakash Narayan Airport (PAT),"Jay Prakash Narayan Airport, Sheikhpura, Patna...",Patna
53,54,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Mumbai

In [14]:
import pandas as pd
import requests
import time

# Your GeoNames API username
GEONAMES_USERNAME = "HetviPatel"  # Replace with your actual GeoNames username

# Function to get coordinates from GeoNames API
def get_geonames_coordinates(location):
    base_url = "http://api.geonames.org/searchJSON"
    params = {
        "q": location,
        "maxRows": 1,
        "username": GEONAMES_USERNAME
    }
    try:
        response = requests.get(base_url, params=params)
        data = response.json()
        if "geonames" in data and len(data["geonames"]) > 0:
            lat = data["geonames"][0]["lat"]
            lon = data["geonames"][0]["lng"]
            return lat, lon
        else:
            return None, None
    except Exception as e:
        print(f"Error fetching {location}: {e}")
        return None, None

# Apply function to 'Name' column
dtframe[["Latitude", "Longitude"]] = dtframe["Name"].apply(lambda x: pd.Series(get_geonames_coordinates(str(x))))

In [15]:
dtframe

,LocationID,Name,Address,City,Latitude,Longitude
0,1,Coimbatore International Airport (CJB),"Coimbatore International Airport, Avinashi Roa...",Coimbatore,11.03003,77.04338
1,2,Birsa Munda Airport (IXR),"Birsa Munda Airport, Hinoo, Ranchi, Jharkhand ...",Ranchi,23.31425,85.32167
2,3,Goa International Airport (GOI),"Goa International Airport, Airport Road, Dabol...",Dabolim,15.38083,73.83142
3,4,Sardar Vallabhbhai Patel International Airport...,Sardar Vallabhbhai Patel International Airport...,Ahmedabad,23.07724,72.63465
4,5,Rajiv Gandhi International Airport (HYD),"Rajiv Gandhi International Airport, Shamshabad...",Hyderabad,17.23132,78.42986
5,6,Agartala Airport (IXA),"Agartala Airport, Agartala, Tripura 799009",Khowai,23.88698,91.24045
6,7,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Navi Mumbai,19.08869,72.86792
7,8,Pune International Airport (PNQ),"Pune International Airport, Lohegaon, Pune, Ma...",Pune,None,None
8,9,Vijayawada Airport (VGA),"Vijayawada Airport, Gannavaram, Andhra Pradesh...",Vijayawada,16.53043,80.79685
9,10,Gwalior Airport (GWL),"Gwalior Airport, Maharajpur, Gwalior, Madhya P...",Gwalior,26.29334,78.22775
10,11,Kempegowda International Airport (BLR),"Kempegowda International Airport, Devanahalli,...",Bengaluru,13.20071,77.70879
11,12,Lokpriya Gopinath Bordoloi International Airpo...,Lokpriya Gopinath Bordoloi International Airpo...,Guwahati,26.10609,91.58594
12,13,Bilaspur Airport (PAB),"Bilaspur Airport, Chakarbhata, Bilaspur, Chhat...",Bilaspur,21.9884,82.11098
13,14,Swami Vivekananda Airport (RPR),"Swami Vivekananda Airport, Ramchandi, Naya Rai...",Raipur,21.1804,81.7388
14,15,Puducherry Airport (PNY),"Puducherry Airport, Lawspet, Puducherry 605008",Puducherry,None,None
15,16,Sonari Airport (IXW),"Sonari Airport, Sonari, Jamshedpur, Jharkhand ...",Jamshedpur,None,None
16,17,Nashik International Airport (ISK),"Nashik International Airport, Ozar, Nashik, Ma...",Nashik,None,None
17,18,Mopa International Airport (GOX),"Mopa International Airport, Mopa, Pernem, Goa ...",Mopa,15.7313,73.86817
18,19,Prayagraj Airport (IXD),"Prayagraj Airport, Bamrauli, Prayagraj, Uttar ...",Prayagraj,25.44006,81.73387
19,20,Vadodara Airport (BDQ),"Vadodara Airport, Harni Road, Vadodara, Gujara...",Vadodara,22.3362,73.2263
20,21,Ludhiana Airport (LUH),"Ludhiana Airport, Sahnewal, Ludhiana, Punjab 1...",Ludhiana,30.8547,75.9526
21,22,Raigarh Airport (None),"Raigarh Airport, Kondatarai, Raigarh, Chhattis...",Raigarh,None,None
22,23,Chennai International Airport (MAA),"Chennai International Airport, GST Road, Meena...",Chennai,12.98833,80.16578
23,24,Biju Patnaik International Airport (BBI),"Biju Patnaik International Airport, Airport Ro...",Puri,20.24436,85.81778
24,25,Tirupati Airport (TIR),"Tirupati Airport, Renigunta, Andhra Pradesh 51...",Tirupati,13.6325,79.5433
25,26,Dehradun Airport (DED),"Dehradun Airport, Jolly Grant, Dehradun, Uttar...",Dehradun,30.1897,78.1803
26,27,Sheikh ul-Alam International Airport (SXR),"Sheikh ul-Alam International Airport, Aerodrom...",Srinagar,33.9871,74.7742
27,28,Indira Gandhi International Airport (DEL),"Indira Gandhi International Airport, New Delhi...",Delhi NCR,28.5665,77.10309
28,29,Donyi Polo Airport (HGI),"Donyi Polo Airport, Hollongi, Itanagar, Arunac...",Itanagar,None,None
29,30,Lal Bahadur Shastri International Airport (VNS),"Lal Bahadur Shastri International Airport, Bab...",Varanasi,None,None
30,31,Rupsi Airport (RUP),"Rupsi Airport, Rupsi, Assam 783372",Dhubri,26.14118,89.90687
31,32,Netaji Subhas Chandra Bose International Airpo...,Netaji Subhas Chandra Bose International Airpo...,Kolkata,22.65474,88.44672
32,33,Pakyong Airport (PYG),"Pakyong Airport, Pakyong, Sikkim 737106",Gangtok,27.22756,88.58596
33,34,Shillong Airport (SHL),"Shillong Airport, Umroi, Meghalaya 793103",Shillong,25.7036,91.9787
34,35,Sri Guru Ram Dass Jee International Airport (ATQ),"Sri Guru Ram Dass Jee International Airport, A...",Amritsar,31.70959,74.79726
35,36,Raja Bhoj Airport (BHO),"Raja Bhoj Airport, Gandhi Nagar, Bhopal, Madhy...",Bhopal,23.28747,77.33737
36,37,Jaipur International Airport (JAI),"Jaipur International Airport, Airport Road, Sa...",Jaipur,26.82419,75.81216
37,38,Kullu–Manali Airport (KUU),"Kullu–Manali Airport, Bhuntar, Kullu, Himachal...",Kullu-Manali,None,None
38,39,Ayodhya Airport (under construction),"Ayodhya Airport, Ayodhya, Uttar Pradesh 224123",Ayodhya,None,None
39,40,Biju Patnaik International Airport (BBI),"Biju Patnaik International Airport, Airport Ro...",Bhubaneswar,20.24436,85.81778
40,41,Trivandrum International Airport (TRV),"Trivandrum International Airport, Vallakkadavu...",Thiruvananthapuram,8.48212,76.92011
41,42,Kota Airport (KTU),"Kota Airport, Aerodrome Circle, Kota, Rajastha...",Kota,25.16022,75.84563
42,43,Surat Airport (STV),"Surat Airport, Dumas Road, Surat, Gujarat 395007",Surat,21.1141,72.7418
43,44,Maharana Pratap Airport (UDR),"Maharana Pratap Airport, NH 76, Dabok, Udaipur...",Udaipur,24.61784,73.89662
44,45,Diu Airport (DIU),"Diu Airport, Diu, Daman and Diu 362520",Diu,20.7131,70.9211
45,46,Chandigarh International Airport (IXC),"Chandigarh International Airport, Mohali, Punj...",Chandigarh,30.6735,76.7885
46,47,Shimla Airport (SLV),"Shimla Airport, Jubbarhatti, Shimla, Himachal ...",Shimla,31.0818,77.068
47,48,Imphal International Airport (IMF),"Imphal International Airport, Imphal, Manipur ...",Imphal,24.75995,93.8967
48,49,Hisar Airport (HSS),"Hisar Airport, Hisar, Haryana 125001",Hisar,29.17944,75.75534
49,50,Visakhapatnam Airport (VTZ),"Visakhapatnam Airport, NAD Junction, Visakhapa...",Visakhapatnam,17.7212,83.2245
50,51,Devi Ahilya Bai Holkar Airport (IDR),"Devi Ahilya Bai Holkar Airport, Indore, Madhya...",Indore,None,None
51,52,Mysore Airport (MYQ),"Mysore Airport, Mandakalli, Mysuru, Karnataka ...",Mysuru,12.3072,76.6497
52,53,Jay Prakash Narayan Airport (PAT),"Jay Prakash Narayan Airport, Sheikhpura, Patna...",Patna,None,None
53,54,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Mumbai,19.08869,72.86792

In [16]:
dtframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LocationID  54 non-null     int64
 1   Name        54 non-null     object
 2   Address     54 non-null     object
 3   City        54 non-null     object
 4   Latitude    43 non-null     object
 5   Longitude   43 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.7+ KB

In [18]:
dtframe.to_excel('AirportCoordinates.xlsx', index=False)
from IPython.display import FileLink
FileLink('AirportCoordinates.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\AirportCoordinates.xlsx

In [5]:
airport_df = pd.read_excel("AirportCoordinates.xlsx")
flight_df = pd.read_excel("FlightWithAirportCoordinates.xlsx")

In [6]:
airport_df

,LocationID,Name,Address,City,Latitude,Longitude
0,1,Coimbatore International Airport (CJB),"Coimbatore International Airport, Avinashi Roa...",Coimbatore,11.030030,77.043380
1,2,Birsa Munda Airport (IXR),"Birsa Munda Airport, Hinoo, Ranchi, Jharkhand ...",Ranchi,23.314250,85.321670
2,3,Goa International Airport (GOI),"Goa International Airport, Airport Road, Dabol...",Dabolim,15.380830,73.831420
3,4,Sardar Vallabhbhai Patel International Airport...,Sardar Vallabhbhai Patel International Airport...,Ahmedabad,23.077240,72.634650
4,5,Rajiv Gandhi International Airport (HYD),"Rajiv Gandhi International Airport, Shamshabad...",Hyderabad,17.231320,78.429860
5,6,Agartala Airport (IXA),"Agartala Airport, Agartala, Tripura 799009",Khowai,23.886980,91.240450
6,7,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Navi Mumbai,19.088690,72.867920
7,8,Pune International Airport (PNQ),"Pune International Airport, Lohegaon, Pune, Ma...",Pune,18.340000,73.550000
8,9,Vijayawada Airport (VGA),"Vijayawada Airport, Gannavaram, Andhra Pradesh...",Vijayawada,16.530430,80.796850
9,10,Gwalior Airport (GWL),"Gwalior Airport, Maharajpur, Gwalior, Madhya P...",Gwalior,26.293340,78.227750
10,11,Kempegowda International Airport (BLR),"Kempegowda International Airport, Devanahalli,...",Bengaluru,13.200710,77.708790
11,12,Lokpriya Gopinath Bordoloi International Airpo...,Lokpriya Gopinath Bordoloi International Airpo...,Guwahati,26.106090,91.585940
12,13,Bilaspur Airport (PAB),"Bilaspur Airport, Chakarbhata, Bilaspur, Chhat...",Bilaspur,21.988400,82.110980
13,14,Swami Vivekananda Airport (RPR),"Swami Vivekananda Airport, Ramchandi, Naya Rai...",Raipur,21.180400,81.738800
14,15,Puducherry Airport (PNY),"Puducherry Airport, Lawspet, Puducherry 605008",Puducherry,11.580000,79.480000
15,16,Sonari Airport (IXW),"Sonari Airport, Sonari, Jamshedpur, Jharkhand ...",Jamshedpur,22.480000,86.100000
16,17,Nashik International Airport (ISK),"Nashik International Airport, Ozar, Nashik, Ma...",Nashik,20.119444,73.913611
17,18,Mopa International Airport (GOX),"Mopa International Airport, Mopa, Pernem, Goa ...",Mopa,15.731300,73.868170
18,19,Prayagraj Airport (IXD),"Prayagraj Airport, Bamrauli, Prayagraj, Uttar ...",Prayagraj,25.440060,81.733870
19,20,Vadodara Airport (BDQ),"Vadodara Airport, Harni Road, Vadodara, Gujara...",Vadodara,22.336200,73.226300
20,21,Ludhiana Airport (LUH),"Ludhiana Airport, Sahnewal, Ludhiana, Punjab 1...",Ludhiana,30.854700,75.952600
21,22,Raigarh Airport (None),"Raigarh Airport, Kondatarai, Raigarh, Chhattis...",Raigarh,21.823889,83.360278
22,23,Chennai International Airport (MAA),"Chennai International Airport, GST Road, Meena...",Chennai,12.988330,80.165780
23,24,Biju Patnaik International Airport (BAI),"Biju Patnaik International Airport, Airport Ro...",Puri,20.244360,85.817780
24,25,Tirupati Airport (TIR),"Tirupati Airport, Renigunta, Andhra Pradesh 51...",Tirupati,13.632500,79.543300
25,26,Dehradun Airport (DED),"Dehradun Airport, Jolly Grant, Dehradun, Uttar...",Dehradun,30.189700,78.180300
26,27,Sheikh ul-Alam International Airport (SXR),"Sheikh ul-Alam International Airport, Aerodrom...",Srinagar,33.987100,74.774200
27,28,Indira Gandhi International Airport (DEL),"Indira Gandhi International Airport, New Delhi...",Delhi NCR,28.566500,77.103090
28,29,Donyi Polo Airport (HGI),"Donyi Polo Airport, Hollongi, Itanagar, Arunac...",Itanagar,26.970000,93.664722
29,30,Lal Bahadur Shastri International Airport (VNS),"Lal Bahadur Shastri International Airport, Bab...",Varanasi,25.452222,82.859444
30,31,Rupsi Airport (RUP),"Rupsi Airport, Rupsi, Assam 783372",Dhubri,26.141180,89.906870
31,32,Netaji Subhas Chandra Bose International Airpo...,Netaji Subhas Chandra Bose International Airpo...,Kolkata,22.654740,88.446720
32,33,Pakyong Airport (PYG),"Pakyong Airport, Pakyong, Sikkim 737106",Gangtok,27.227560,88.585960
33,34,Shillong Airport (SHL),"Shillong Airport, Umroi, Meghalaya 793103",Shillong,25.703600,91.978700
34,35,Sri Guru Ram Dass Jee International Airport (ATQ),"Sri Guru Ram Dass Jee International Airport, A...",Amritsar,31.709590,74.797260
35,36,Raja Bhoj Airport (BHO),"Raja Bhoj Airport, Gandhi Nagar, Bhopal, Madhy...",Bhopal,23.287470,77.337370
36,37,Jaipur International Airport (JAI),"Jaipur International Airport, Airport Road, Sa...",Jaipur,26.824190,75.812160
37,38,Kullu–Manali Airport (KUU),"Kullu–Manali Airport, Bhuntar, Kullu, Himachal...",Kullu-Manali,31.876667,77.154444
38,39,Ayodhya Airport (under construction),"Ayodhya Airport, Ayodhya, Uttar Pradesh 224123",Ayodhya,26.748034,82.150781
39,40,Biju Patnaik International Airport (BBI),"Biju Patnaik International Airport, Airport Ro...",Bhubaneswar,20.244360,85.817780
40,41,Trivandrum International Airport (TRV),"Trivandrum International Airport, Vallakkadavu...",Thiruvananthapuram,8.482120,76.920110
41,42,Kota Airport (KTU),"Kota Airport, Aerodrome Circle, Kota, Rajastha...",Kota,25.160220,75.845630
42,43,Surat Airport (STV),"Surat Airport, Dumas Road, Surat, Gujarat 395007",Surat,21.114100,72.741800
43,44,Maharana Pratap Airport (UDR),"Maharana Pratap Airport, NH 76, Dabok, Udaipur...",Udaipur,24.617840,73.896620
44,45,Diu Airport (DIU),"Diu Airport, Diu, Daman and Diu 362520",Diu,20.713100,70.921100
45,46,Chandigarh International Airport (IXC),"Chandigarh International Airport, Mohali, Punj...",Chandigarh,30.673500,76.788500
46,47,Shimla Airport (SLV),"Shimla Airport, Jubbarhatti, Shimla, Himachal ...",Shimla,31.081800,77.068000
47,48,Imphal International Airport (IMF),"Imphal International Airport, Imphal, Manipur ...",Imphal,24.759950,93.896700
48,49,Hisar Airport (HSS),"Hisar Airport, Hisar, Haryana 125001",Hisar,29.179440,75.755340
49,50,Visakhapatnam Airport (VTZ),"Visakhapatnam Airport, NAD Junction, Visakhapa...",Visakhapatnam,17.721200,83.224500
50,51,Devi Ahilya Bai Holkar Airport (IDR),"Devi Ahilya Bai Holkar Airport, Indore, Madhya...",Indore,22.721667,75.800833
51,52,Mysore Airport (MYQ),"Mysore Airport, Mandakalli, Mysuru, Karnataka ...",Mysuru,12.307200,76.649700
52,53,Jay Prakash Narayan Airport (PAT),"Jay Prakash Narayan Airport, Sheikhpura, Patna...",Patna,25.591389,85.089167
53,54,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Mumbai,19.088690,72.867920

In [7]:
flight_df

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Departure Time,Arrival Time,flight_number,Calculated_Flight_Price
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),03:59,05:05,G84279,4810.84
1,2,0,firstClass,IndiGo,10/10/2019,Birsa Munda Airport (IXR),Shillong Airport (SHL),01:02,01:49,6E4357O,3580.20
2,7,0,economic,Air India,14/11/2019,Goa International Airport (GOI),Birsa Munda Airport (IXR),00:15,01:54,AI3905,3785.16
3,11,0,premium,SpiceJet,12/12/2019,Sardar Vallabhbhai Patel International Airport...,Raigarh Airport (None),17:35,18:49,SG2659K,3669.93
4,13,0,firstClass,GoAir,26/12/2019,Rajiv Gandhi International Airport (HYD),Netaji Subhas Chandra Bose International Airpo...,18:18,19:36,G83184,5780.44
...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,premium,Air India,18/06/2020,Devi Ahilya Bai Holkar Airport (IDR),Goa International Airport (GOI),04:28,05:24,AI5405C,2949.67
39975,135939,1339,premium,Akasa Air,25/06/2020,Sardar Vallabhbhai Patel International Airport...,Shillong Airport (SHL),13:37,15:48,QP2071,5988.03
39976,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj Airport (IXD),Visakhapatnam Airport (VTZ),17:27,18:25,QP589J,4272.88
39977,135941,1339,firstClass,IndiGo,07/09/2020,Surat Airport (STV),Goa International Airport (GOI),00:46,01:29,6E4801N,3349.72
39978,135942,1339,economic,IndiGo,16/07/2020,Raja Bhoj Airport (BHO),Prayagraj Airport (IXD),12:14,12:48,6E4290X,1673.92

In [8]:
airport_df = airport_df.drop_duplicates(subset=["Name"])

In [9]:
flight_df = flight_df.merge(airport_df, left_on="Departure", right_on="Name", how="left")
flight_df = flight_df.rename(columns={"Latitude": "Dep_Lat", "Longitude": "Dep_Lon"})

flight_df = flight_df.merge(airport_df, left_on="Arrival", right_on="Name", how="left")
flight_df = flight_df.rename(columns={"Latitude": "Arr_Lat", "Longitude": "Arr_Lon"})

In [10]:
flight_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39979 entries, 0 to 39978
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   travelCode               39979 non-null  int64
 1   User_ID                  39979 non-null  int64
 2   flightType               39979 non-null  object
 3   Flight_agency            39979 non-null  object
 4   Departure_date           39979 non-null  object
 5   Departure                39979 non-null  object
 6   Arrival                  39979 non-null  object
 7   Departure Time           39979 non-null  object
 8   Arrival Time             39979 non-null  object
 9   flight_number            39979 non-null  object
 10  Calculated_Flight_Price  39979 non-null  float64
 11  LocationID_x             39979 non-null  int64
 12  Name_x                   39979 non-null  object
 13  Address_x                39979 non-null  object
 14  City_x                   39979 non-null  object
 15  Dep_Lat                  39979 non-null  float64
 16  Dep_Lon                  39979 non-null  float64
 17  LocationID_y             39979 non-null  int64
 18  Name_y                   39979 non-null  object
 19  Address_y                39979 non-null  object
 20  City_y                   39979 non-null  object
 21  Arr_Lat                  39979 non-null  float64
 22  Arr_Lon                  39979 non-null  float64
dtypes: float64(5), int64(4), object(14)
memory usage: 7.0+ MB

In [11]:
flight_df.drop(columns=['Arrival Time','LocationID_x','Name_x','Address_x','City_x','LocationID_y','Name_y','Address_y','City_y'])

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Departure Time,flight_number,Calculated_Flight_Price,Dep_Lat,Dep_Lon,Arr_Lat,Arr_Lon
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),03:59,G84279,4810.84,11.030030,77.043380,17.721200,83.224500
1,2,0,firstClass,IndiGo,10/10/2019,Birsa Munda Airport (IXR),Shillong Airport (SHL),01:02,6E4357O,3580.20,23.314250,85.321670,25.703600,91.978700
2,7,0,economic,Air India,14/11/2019,Goa International Airport (GOI),Birsa Munda Airport (IXR),00:15,AI3905,3785.16,15.380830,73.831420,23.314250,85.321670
3,11,0,premium,SpiceJet,12/12/2019,Sardar Vallabhbhai Patel International Airport...,Raigarh Airport (None),17:35,SG2659K,3669.93,23.077240,72.634650,21.823889,83.360278
4,13,0,firstClass,GoAir,26/12/2019,Rajiv Gandhi International Airport (HYD),Netaji Subhas Chandra Bose International Airpo...,18:18,G83184,5780.44,17.231320,78.429860,22.654740,88.446720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,premium,Air India,18/06/2020,Devi Ahilya Bai Holkar Airport (IDR),Goa International Airport (GOI),04:28,AI5405C,2949.67,22.721667,75.800833,15.380830,73.831420
39975,135939,1339,premium,Akasa Air,25/06/2020,Sardar Vallabhbhai Patel International Airport...,Shillong Airport (SHL),13:37,QP2071,5988.03,23.077240,72.634650,25.703600,91.978700
39976,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj Airport (IXD),Visakhapatnam Airport (VTZ),17:27,QP589J,4272.88,25.440060,81.733870,17.721200,83.224500
39977,135941,1339,firstClass,IndiGo,07/09/2020,Surat Airport (STV),Goa International Airport (GOI),00:46,6E4801N,3349.72,21.114100,72.741800,15.380830,73.831420
39978,135942,1339,economic,IndiGo,16/07/2020,Raja Bhoj Airport (BHO),Prayagraj Airport (IXD),12:14,6E4290X,1673.92,23.287470,77.337370,25.440060,81.733870

In [12]:
from math import radians, sin, cos, sqrt, atan2

def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Radius of the Earth in km
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * atan2(sqrt(a), sqrt(1-a))
    return R * c

flight_df["Distance_km"] = flight_df.apply(lambda row: haversine(row["Dep_Lat"], row["Dep_Lon"], row["Arr_Lat"], row["Arr_Lon"]), axis=1)

In [13]:
flight_df['Flight_agency'].value_counts()

Flight_agency
Akasa Air        8636
IndiGo           8588
Air India        8565
SpiceJet         8527
AirAsia India    2847
GoAir            2816
Name: count, dtype: int64

In [33]:
flight_speeds = {
    "Akasa Air": 820,
    "Air India": 840,
    "IndiGo": 830,
    "SpiceJet": 820,
    "AirAsia India": 810,
    "GoAir": 815
}

In [35]:
flight_df["Speed_kmh"] = flight_df["Flight_agency"].map(flight_speeds)
flight_df["EstimatedDuration_hr"] = flight_df["Distance_km"] / flight_df["Speed_kmh"]

In [37]:
def convert_to_hhmm(duration_hr):
    hours = int(duration_hr)
    minutes = int((duration_hr - hours) * 60)
    return f"{hours:02d}:{minutes:02d}"

flight_df["EstimatedDuration_HHMM"] = flight_df["EstimatedDuration_hr"].apply(convert_to_hhmm)

In [38]:
flight_df

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Departure Time,Arrival Time,flight_number,...,LocationID_y,Name_y,Address_y,City_y,Arr_Lat,Arr_Lon,Distance_km,Speed_kmh,EstimatedDuration_hr,EstimatedDuration_HHMM
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),03:59,05:05,G84279,...,50,Visakhapatnam Airport (VTZ),"Visakhapatnam Airport, NAD Junction, Visakhapa...",Visakhapatnam,17.721200,83.224500,998.106548,815,1.224671,01:13
1,2,0,firstClass,IndiGo,10/10/2019,Birsa Munda Airport (IXR),Shillong Airport (SHL),01:02,01:49,6E4357O,...,34,Shillong Airport (SHL),"Shillong Airport, Umroi, Meghalaya 793103",Shillong,25.703600,91.978700,723.904020,830,0.872174,00:52
2,7,0,economic,Air India,14/11/2019,Goa International Airport (GOI),Birsa Munda Airport (IXR),00:15,01:54,AI3905,...,2,Birsa Munda Airport (IXR),"Birsa Munda Airport, Hinoo, Ranchi, Jharkhand ...",Ranchi,23.314250,85.321670,1492.553600,840,1.776850,01:46
3,11,0,premium,SpiceJet,12/12/2019,Sardar Vallabhbhai Patel International Airport...,Raigarh Airport (None),17:35,18:49,SG2659K,...,22,Raigarh Airport (None),"Raigarh Airport, Kondatarai, Raigarh, Chhattis...",Raigarh,21.823889,83.360278,1110.753989,820,1.354578,01:21
4,13,0,firstClass,GoAir,26/12/2019,Rajiv Gandhi International Airport (HYD),Netaji Subhas Chandra Bose International Airpo...,18:18,19:36,G83184,...,32,Netaji Subhas Chandra Bose International Airpo...,Netaji Subhas Chandra Bose International Airpo...,Kolkata,22.654740,88.446720,1207.676138,815,1.481811,01:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45948,135938,1339,premium,Air India,18/06/2020,Devi Ahilya Bai Holkar Airport (IDR),Goa International Airport (GOI),04:28,05:24,AI5405C,...,3,Goa International Airport (GOI),"Goa International Airport, Airport Road, Dabol...",Dabolim,15.380830,73.831420,842.052913,840,1.002444,01:00
45949,135939,1339,premium,Akasa Air,25/06/2020,Sardar Vallabhbhai Patel International Airport...,Shillong Airport (SHL),13:37,15:48,QP2071,...,34,Shillong Airport (SHL),"Shillong Airport, Umroi, Meghalaya 793103",Shillong,25.703600,91.978700,1978.782106,820,2.413149,02:24
45950,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj Airport (IXD),Visakhapatnam Airport (VTZ),17:27,18:25,QP589J,...,50,Visakhapatnam Airport (VTZ),"Visakhapatnam Airport, NAD Junction, Visakhapa...",Visakhapatnam,17.721200,83.224500,871.997188,820,1.063411,01:03
45951,135941,1339,firstClass,IndiGo,07/09/2020,Surat Airport (STV),Goa International Airport (GOI),00:46,01:29,6E4801N,...,3,Goa International Airport (GOI),"Goa International Airport, Airport Road, Dabol...",Dabolim,15.380830,73.831420,647.800512,830,0.780483,00:46
45952,135942,1339,economic,IndiGo,16/07/2020,Raja Bhoj Airport (BHO),Prayagraj Airport (IXD),12:14,12:48,6E4290X,...,19,Prayagraj Airport (IXD),"Prayagraj Airport, Bamrauli, Prayagraj, Uttar ...",Prayagraj,25.440060,81.733870,505.527757,830,0.609070,00:36

In [1]:
flight_df['Flight_agency'].value_counts()

NameError: name 'flight_df' is not defined