In [1]:
import pandas as pd

In [97]:
round_2 = pd.read_excel("roundtrip_modified_dataset_with_cost.xlsx")
round_2

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price,Return Date,Total Flights,Total Flight Cost
0,503,4,firstClass,Air India,2021-03-25,Itanagar,Surat,2204.62,02:26,00:56,03:22,12220.60,2021-04-02,2,19782.96
1,590,4,economic,SpiceJet,2021-04-02,Surat,Itanagar,2204.62,02:26,04:18,06:44,7562.36,2021-03-25,2,19782.96
2,1479,13,economic,IndiGo,2020-09-07,Bengaluru,Visakhapatnam,797.17,00:53,01:41,02:34,3110.76,2020-09-15,2,6441.52
3,1507,13,economic,SpiceJet,2020-09-15,Visakhapatnam,Bengaluru,797.17,00:53,08:07,09:00,3330.76,2020-09-07,2,6441.52
4,1666,15,firstClass,Air India,2019-11-28,Chandigarh,Navi Mumbai,1355.13,01:30,11:12,12:42,7763.15,2019-12-09,2,12681.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,133540,1315,economic,Akasa Air,2021-06-17,Delhi NCR,Shimla,271.89,00:18,13:48,14:06,1456.17,2021-06-05,2,3112.34
384,134586,1323,premium,Air India,2021-12-16,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84,2021-12-30,2,14442.79
385,134613,1323,firstClass,Akasa Air,2021-12-30,Dehradun,Hyderabad,1439.54,01:35,22:00,23:35,8153.95,2021-12-16,2,14442.79
386,135670,1335,firstClass,IndiGo,2019-11-28,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25,2019-12-06,2,30903.11
387,135799,1335,premium,Akasa Air,2019-12-06,Kota,Raigarh,3289.60,03:39,22:43,02:22,13033.86,2019-11-28,2,30903.11

In [98]:
round_2 = round_2.iloc[::2]
round_2

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price,Return Date,Total Flights,Total Flight Cost
0,503,4,firstClass,Air India,2021-03-25,Itanagar,Surat,2204.62,02:26,00:56,03:22,12220.60,2021-04-02,2,19782.96
2,1479,13,economic,IndiGo,2020-09-07,Bengaluru,Visakhapatnam,797.17,00:53,01:41,02:34,3110.76,2020-09-15,2,6441.52
4,1666,15,firstClass,Air India,2019-11-28,Chandigarh,Navi Mumbai,1355.13,01:30,11:12,12:42,7763.15,2019-12-09,2,12681.04
6,2069,18,premium,Akasa Air,2021-01-28,Kota,Visakhapatnam,3406.67,03:47,03:42,07:29,13476.91,2021-01-31,2,27003.82
8,2383,21,economic,IndiGo,2021-06-17,Shillong,Diu,2201.44,02:26,16:15,18:41,7532.82,2021-07-01,2,15115.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,132731,1307,firstClass,SpiceJet,2020-05-21,Ranchi,Dhubri,558.25,00:37,22:07,22:44,3550.00,2020-05-24,2,7080.00
380,133011,1311,economic,Air India,2020-07-30,Gwalior,Nashik,825.13,00:55,09:03,09:58,3449.14,2020-08-03,2,8581.04
382,133492,1315,economic,Akasa Air,2021-06-05,Shimla,Delhi NCR,271.89,00:18,06:52,07:10,1656.17,2021-06-17,2,3112.34
384,134586,1323,premium,Air India,2021-12-16,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84,2021-12-30,2,14442.79
386,135670,1335,firstClass,IndiGo,2019-11-28,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25,2019-12-06,2,30903.11

In [4]:
round_4 = pd.read_excel('roundtrip_detailed_costs.xlsx')
round_4

,User_ID,From,To,Departure_Date,Return_Date,Roundtrip_Cost
0,34,Khowai,Ayodhya,2020-05-07,2020-07-12,10211.83
1,34,Bhopal,Mysuru,2021-04-15,2021-05-22,12723.14
2,63,Thiruvananthapuram,Vijayawada,2019-07-23,2019-11-07,9833.92
3,63,Nashik,Coimbatore,2020-02-13,2020-03-18,10793.01
4,132,Dehradun,Bengaluru,2019-10-10,2019-10-20,21460.40
...,...,...,...,...,...,...
65,1080,Amritsar,Kota,2020-03-05,2020-05-23,19344.22
66,1104,Delhi NCR,Guwahati,2020-04-30,2020-05-07,16682.00
67,1104,Jamshedpur,Amritsar,2020-12-24,2021-01-02,16819.60
68,1165,Bhubaneswar,Kullu-Manali,2019-10-31,2019-11-03,11181.38
69,1165,Indore,Kota,2020-12-31,2021-01-02,28018.40

In [14]:
round_4 = round_4.rename(columns={'From':'Departure','To':'Arrival'})

In [6]:
rounddd_4 = pd.read_excel("roundtrip_dataset_user_4.xlsx")
rounddd_4

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price,Return Date,Total Flights,Total Flight Cost
0,3392,34,firstClass,GoAir,2020-05-07,Ayodhya,Khowai,991.41,01:06,01:34,02:40,5814.55,2020-07-12,4,22934.97
1,3442,34,premium,Air India,2020-07-12,Khowai,Ayodhya,991.41,01:06,23:29,00:35,4397.28,2020-05-07,4,22934.97
2,3441,34,premium,Air India,2021-04-15,Mysuru,Bhopal,1221.01,01:21,19:40,21:01,5464.34,2021-05-22,4,22934.97
3,3498,34,firstClass,Air India,2021-05-22,Bhopal,Mysuru,1221.01,01:21,07:30,08:51,7258.80,2021-04-15,4,22934.97
4,6422,63,economic,Akasa Air,2019-07-23,Vijayawada,Thiruvananthapuram,977.99,01:05,21:51,22:56,3880.22,2019-11-07,4,20626.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,111482,1104,firstClass,GoAir,2021-01-02,Jamshedpur,Amritsar,1485.71,01:39,04:27,06:06,8409.80,2020-12-24,4,33501.60
136,117586,1165,economic,Akasa Air,2019-10-31,Kullu-Manali,Bhubaneswar,1552.98,01:43,10:49,12:32,5490.69,2019-11-03,4,39199.78
137,117598,1165,economic,IndiGo,2019-11-03,Bhubaneswar,Kullu-Manali,1552.98,01:43,19:50,21:33,5690.69,2019-10-31,4,39199.78
138,117647,1165,firstClass,Air India,2020-12-31,Kota,Indore,2510.59,02:47,06:25,09:12,14029.20,2021-01-02,4,39199.78
139,117742,1165,firstClass,GoAir,2021-01-02,Indore,Kota,2510.59,02:47,21:21,00:08,13989.20,2020-12-31,4,39199.78

In [8]:
rounddd_4 = rounddd_4.drop(columns={'Total Flight Cost'})

In [9]:
rounddd_4

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price,Return Date,Total Flights
0,3392,34,firstClass,GoAir,2020-05-07,Ayodhya,Khowai,991.41,01:06,01:34,02:40,5814.55,2020-07-12,4
1,3442,34,premium,Air India,2020-07-12,Khowai,Ayodhya,991.41,01:06,23:29,00:35,4397.28,2020-05-07,4
2,3441,34,premium,Air India,2021-04-15,Mysuru,Bhopal,1221.01,01:21,19:40,21:01,5464.34,2021-05-22,4
3,3498,34,firstClass,Air India,2021-05-22,Bhopal,Mysuru,1221.01,01:21,07:30,08:51,7258.80,2021-04-15,4
4,6422,63,economic,Akasa Air,2019-07-23,Vijayawada,Thiruvananthapuram,977.99,01:05,21:51,22:56,3880.22,2019-11-07,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,111482,1104,firstClass,GoAir,2021-01-02,Jamshedpur,Amritsar,1485.71,01:39,04:27,06:06,8409.80,2020-12-24,4
136,117586,1165,economic,Akasa Air,2019-10-31,Kullu-Manali,Bhubaneswar,1552.98,01:43,10:49,12:32,5490.69,2019-11-03,4
137,117598,1165,economic,IndiGo,2019-11-03,Bhubaneswar,Kullu-Manali,1552.98,01:43,19:50,21:33,5690.69,2019-10-31,4
138,117647,1165,firstClass,Air India,2020-12-31,Kota,Indore,2510.59,02:47,06:25,09:12,14029.20,2021-01-02,4
139,117742,1165,firstClass,GoAir,2021-01-02,Indore,Kota,2510.59,02:47,21:21,00:08,13989.20,2020-12-31,4

In [25]:
round__4 = pd.merge(round_4,rounddd_4, on=['User_ID','Departure','Arrival'], how="inner")
round__4

,User_ID,Departure,Arrival,Departure_Date,Return_Date,Roundtrip_Cost,travelCode,flightType,Flight_agency,Departure_date,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price,Return Date,Total Flights
0,34,Khowai,Ayodhya,2020-05-07,2020-07-12,10211.83,3442,premium,Air India,2020-07-12,991.41,01:06,23:29,00:35,4397.28,2020-05-07,4
1,34,Bhopal,Mysuru,2021-04-15,2021-05-22,12723.14,3498,firstClass,Air India,2021-05-22,1221.01,01:21,07:30,08:51,7258.80,2021-04-15,4
2,63,Thiruvananthapuram,Vijayawada,2019-07-23,2019-11-07,9833.92,6385,firstClass,SpiceJet,2019-11-07,977.99,01:05,21:57,23:02,5953.70,2019-07-23,4
3,63,Nashik,Coimbatore,2020-02-13,2020-03-18,10793.01,6502,firstClass,GoAir,2020-03-18,1055.99,01:10,00:42,01:52,6152.45,2020-02-13,4
4,132,Dehradun,Bengaluru,2019-10-10,2019-10-20,21460.40,13400,firstClass,Akasa Air,2019-10-20,1930.04,02:08,15:49,17:57,10730.20,2019-10-10,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,1080,Amritsar,Kota,2020-03-05,2020-05-23,19344.22,109044,premium,Akasa Air,2020-05-23,2400.03,02:40,22:38,01:18,9672.11,2020-03-05,4
66,1104,Delhi NCR,Guwahati,2020-04-30,2020-05-07,16682.00,111460,firstClass,SpiceJet,2020-05-07,1472.70,01:38,14:15,15:53,8351.00,2020-04-30,4
67,1104,Jamshedpur,Amritsar,2020-12-24,2021-01-02,16819.60,111482,firstClass,GoAir,2021-01-02,1485.71,01:39,04:27,06:06,8409.80,2020-12-24,4
68,1165,Bhubaneswar,Kullu-Manali,2019-10-31,2019-11-03,11181.38,117598,economic,IndiGo,2019-11-03,1552.98,01:43,19:50,21:33,5690.69,2019-10-31,4
69,1165,Indore,Kota,2020-12-31,2021-01-02,28018.40,117742,firstClass,GoAir,2021-01-02,2510.59,02:47,21:21,00:08,13989.20,2020-12-31,4

In [26]:
round__4 = round__4.drop(columns={'Departure_date','Calculated_Flight_Price','Return Date','Total Flights'})

In [27]:
round__4

,User_ID,Departure,Arrival,Departure_Date,Return_Date,Roundtrip_Cost,travelCode,flightType,Flight_agency,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time
0,34,Khowai,Ayodhya,2020-05-07,2020-07-12,10211.83,3442,premium,Air India,991.41,01:06,23:29,00:35
1,34,Bhopal,Mysuru,2021-04-15,2021-05-22,12723.14,3498,firstClass,Air India,1221.01,01:21,07:30,08:51
2,63,Thiruvananthapuram,Vijayawada,2019-07-23,2019-11-07,9833.92,6385,firstClass,SpiceJet,977.99,01:05,21:57,23:02
3,63,Nashik,Coimbatore,2020-02-13,2020-03-18,10793.01,6502,firstClass,GoAir,1055.99,01:10,00:42,01:52
4,132,Dehradun,Bengaluru,2019-10-10,2019-10-20,21460.40,13400,firstClass,Akasa Air,1930.04,02:08,15:49,17:57
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,1080,Amritsar,Kota,2020-03-05,2020-05-23,19344.22,109044,premium,Akasa Air,2400.03,02:40,22:38,01:18
66,1104,Delhi NCR,Guwahati,2020-04-30,2020-05-07,16682.00,111460,firstClass,SpiceJet,1472.70,01:38,14:15,15:53
67,1104,Jamshedpur,Amritsar,2020-12-24,2021-01-02,16819.60,111482,firstClass,GoAir,1485.71,01:39,04:27,06:06
68,1165,Bhubaneswar,Kullu-Manali,2019-10-31,2019-11-03,11181.38,117598,economic,IndiGo,1552.98,01:43,19:50,21:33
69,1165,Indore,Kota,2020-12-31,2021-01-02,28018.40,117742,firstClass,GoAir,2510.59,02:47,21:21,00:08

In [28]:
reorder = ['travelCode','User_ID','Departure','Arrival','Departure_Date','Return_Date','flightType','Flight_agency','Flight Distance (km)','Flight Duration (hh:mm)','Departure Time','Arrival Time','Roundtrip_Cost']

In [29]:
round__4 = round__4[reorder]

In [30]:
round__4

,travelCode,User_ID,Departure,Arrival,Departure_Date,Return_Date,flightType,Flight_agency,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Roundtrip_Cost
0,3442,34,Khowai,Ayodhya,2020-05-07,2020-07-12,premium,Air India,991.41,01:06,23:29,00:35,10211.83
1,3498,34,Bhopal,Mysuru,2021-04-15,2021-05-22,firstClass,Air India,1221.01,01:21,07:30,08:51,12723.14
2,6385,63,Thiruvananthapuram,Vijayawada,2019-07-23,2019-11-07,firstClass,SpiceJet,977.99,01:05,21:57,23:02,9833.92
3,6502,63,Nashik,Coimbatore,2020-02-13,2020-03-18,firstClass,GoAir,1055.99,01:10,00:42,01:52,10793.01
4,13400,132,Dehradun,Bengaluru,2019-10-10,2019-10-20,firstClass,Akasa Air,1930.04,02:08,15:49,17:57,21460.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,109044,1080,Amritsar,Kota,2020-03-05,2020-05-23,premium,Akasa Air,2400.03,02:40,22:38,01:18,19344.22
66,111460,1104,Delhi NCR,Guwahati,2020-04-30,2020-05-07,firstClass,SpiceJet,1472.70,01:38,14:15,15:53,16682.00
67,111482,1104,Jamshedpur,Amritsar,2020-12-24,2021-01-02,firstClass,GoAir,1485.71,01:39,04:27,06:06,16819.60
68,117598,1165,Bhubaneswar,Kullu-Manali,2019-10-31,2019-11-03,economic,IndiGo,1552.98,01:43,19:50,21:33,11181.38
69,117742,1165,Indore,Kota,2020-12-31,2021-01-02,firstClass,GoAir,2510.59,02:47,21:21,00:08,28018.40

In [37]:
round_6 = pd.read_excel('roundtrip_detailed_costs_user6.xlsx')
round_6

,User_ID,From,To,Departure_Date,Return_Date,Roundtrip_Cost
0,93,Ludhiana,Dabolim,2019-07-15,2019-11-07,12352.76
1,93,Bilaspur,Hyderabad,2020-01-23,2020-01-30,5702.52
2,93,Puducherry,Guwahati,2020-04-09,2020-09-08,18138.88
3,641,Hyderabad,Surat,2020-08-13,2020-08-18,8827.10
4,641,Navi Mumbai,Dabolim,2021-05-19,2021-08-05,3865.40
5,641,Nashik,Surat,2021-04-08,2021-08-19,2599.04
6,737,Puri,Coimbatore,2019-10-10,2019-10-24,13995.08
7,737,Mumbai,Jaipur,2020-11-19,2020-11-26,9149.52
8,737,Puri,Puducherry,2020-03-12,2020-12-17,9643.68
9,1039,Raigarh,Visakhapatnam,2021-04-29,2021-05-09,5361.28
10,1039,Amritsar,Delhi NCR,2022-04-14,2022-04-19,4488.08
11,1039,Ranchi,Bilaspur,2022-02-17,NaT,4851.31
12,1041,Kullu-Manali,Chandigarh,2020-07-23,2020-08-01,2349.92
13,1041,Mysuru,Chennai,2020-11-19,2020-11-26,4611.36
14,1041,Thiruvananthapuram,Guwahati,2022-07-14,2022-07-27,24335.51
15,1286,Jamshedpur,Shimla,2020-06-25,2020-06-28,14746.40
16,1286,Srinagar,Mopa,2020-07-23,2020-07-28,80917.40
17,1286,Puducherry,Chennai,2021-04-15,2021-04-26,2898.40

In [38]:
round_6['Return_Date'].fillna(pd.to_datetime('2022-02-25'), inplace=True)

In [39]:
round_6

,User_ID,From,To,Departure_Date,Return_Date,Roundtrip_Cost
0,93,Ludhiana,Dabolim,2019-07-15,2019-11-07,12352.76
1,93,Bilaspur,Hyderabad,2020-01-23,2020-01-30,5702.52
2,93,Puducherry,Guwahati,2020-04-09,2020-09-08,18138.88
3,641,Hyderabad,Surat,2020-08-13,2020-08-18,8827.10
4,641,Navi Mumbai,Dabolim,2021-05-19,2021-08-05,3865.40
5,641,Nashik,Surat,2021-04-08,2021-08-19,2599.04
6,737,Puri,Coimbatore,2019-10-10,2019-10-24,13995.08
7,737,Mumbai,Jaipur,2020-11-19,2020-11-26,9149.52
8,737,Puri,Puducherry,2020-03-12,2020-12-17,9643.68
9,1039,Raigarh,Visakhapatnam,2021-04-29,2021-05-09,5361.28
10,1039,Amritsar,Delhi NCR,2022-04-14,2022-04-19,4488.08
11,1039,Ranchi,Bilaspur,2022-02-17,2022-02-25,4851.31
12,1041,Kullu-Manali,Chandigarh,2020-07-23,2020-08-01,2349.92
13,1041,Mysuru,Chennai,2020-11-19,2020-11-26,4611.36
14,1041,Thiruvananthapuram,Guwahati,2022-07-14,2022-07-27,24335.51
15,1286,Jamshedpur,Shimla,2020-06-25,2020-06-28,14746.40
16,1286,Srinagar,Mopa,2020-07-23,2020-07-28,80917.40
17,1286,Puducherry,Chennai,2021-04-15,2021-04-26,2898.40

In [47]:
round_6 = round_6.rename(columns={'From':'Departure','To':'Arrival'})

In [41]:
r6 = pd.read_excel("dataset_user_6.xlsx")

In [42]:
r6

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,9126,93,economic,Akasa Air,11/07/2019,Ludhiana,Dabolim,1739.21,01:55,04:33,06:28,6076.38
1,9137,93,premium,IndiGo,23/01/2020,Hyderabad,Bilaspur,649.95,00:43,13:22,14:05,3055.92
2,9148,93,economic,Akasa Air,04/09/2020,Guwahati,Puducherry,2016.86,02:14,14:32,16:46,6952.08
3,9175,93,economic,IndiGo,2019-07-15 00:00:00,Dabolim,Ludhiana,1739.21,01:55,19:29,21:24,6276.38
4,9218,93,firstClass,AirAsia India,2020-09-08 00:00:00,Puducherry,Guwahati,2016.86,02:14,14:39,16:53,11186.80
5,9231,93,economic,Akasa Air,2020-01-30 00:00:00,Bilaspur,Hyderabad,649.95,00:43,04:22,05:05,2646.60
6,65993,641,firstClass,Akasa Air,13/08/2020,Surat,Hyderabad,726.71,00:48,15:24,16:12,4413.55
7,66020,641,firstClass,AirAsia India,2020-08-18 00:00:00,Hyderabad,Surat,726.71,00:48,17:28,18:16,4413.55
8,66027,641,firstClass,Akasa Air,04/08/2021,Surat,Nashik,166.63,00:11,15:57,16:08,1474.40
9,66044,641,economic,Akasa Air,08/05/2021,Navi Mumbai,Dabolim,415.65,00:27,11:37,12:04,1907.70
10,66046,641,economic,Akasa Air,2021-08-19 00:00:00,Nashik,Surat,166.63,00:11,05:34,05:45,1124.64
11,66048,641,economic,Air India,2021-05-19 00:00:00,Dabolim,Navi Mumbai,415.65,00:27,01:11,01:38,1957.70
12,75623,737,premium,Air India,10/10/2019,Coimbatore,Puri,1362.16,01:30,20:17,21:47,5996.78
13,75625,737,firstClass,Air India,24/10/2019,Puri,Coimbatore,1362.16,01:30,20:20,21:50,7998.30
14,75645,737,premium,Air India,03/12/2020,Puducherry,Puri,1084.01,01:12,22:19,23:31,4746.84
15,75681,737,economic,Akasa Air,19/11/2020,Jaipur,Mumbai,921.69,01:01,10:02,11:03,3502.32
16,75724,737,firstClass,GoAir,2020-11-26 00:00:00,Mumbai,Jaipur,921.69,01:01,20:17,21:18,5647.20
17,75750,737,premium,IndiGo,2020-12-17 00:00:00,Puri,Puducherry,1084.01,01:12,09:34,10:46,4896.84
18,104683,1039,firstClass,SpiceJet,2021-04-29 00:00:00,Visakhapatnam,Raigarh,469.41,00:31,18:18,18:49,3283.30
19,104725,1039,premium,Air India,2022-02-17 00:00:00,Bilaspur,Ranchi,352.67,00:23,06:26,06:49,2181.71
20,104726,1039,economic,Akasa Air,2021-05-09 00:00:00,Raigarh,Visakhapatnam,469.41,00:31,03:29,04:00,2077.98
21,104731,1039,firstClass,SpiceJet,31/02/2022,Ranchi,Bilaspur,352.67,00:23,06:00,06:23,2669.60
22,104733,1039,firstClass,AirAsia India,14/04/2022,Delhi NCR,Amritsar,391.51,00:26,02:50,03:16,2655.05
23,104753,1039,economic,IndiGo,2022-04-19 00:00:00,Amritsar,Delhi NCR,391.51,00:26,03:06,03:32,1833.03
24,104985,1041,firstClass,Air India,23/07/2020,Chandigarh,Kullu-Manali,131.49,00:08,10:29,10:37,1337.45
25,105002,1041,firstClass,SpiceJet,19/11/2020,Chennai,Mysuru,404.42,00:26,14:19,14:45,2739.60
26,105006,1041,economic,Akasa Air,2020-08-01 00:00:00,Kullu-Manali,Chandigarh,131.49,00:08,22:27,22:35,1012.47
27,105088,1041,firstClass,AirAsia India,14/07/2022,Guwahati,Thiruvananthapuram,2512.60,02:47,07:21,10:08,13989.25
28,105129,1041,premium,Air India,2022-07-27 00:00:00,Thiruvananthapuram,Guwahati,2512.60,02:47,18:38,21:25,10346.26
29,105134,1041,economic,IndiGo,2020-11-26 00:00:00,Mysuru,Chennai,404.42,00:26,12:51,13:17,1871.76
30,130646,1286,firstClass,SpiceJet,25/06/2020,Shimla,Jamshedpur,1283.89,01:25,11:11,12:36,7358.20
31,130650,1286,firstClass,SpiceJet,23/07/2020,Mopa,Srinagar,7566.74,08:24,09:11,17:35,40543.70
32,130685,1286,firstClass,Air India,2020-07-28 00:00:00,Srinagar,Mopa,7566.74,08:24,17:11,01:35,40373.70
33,130688,1286,premium,Air India,15/04/2021,Chennai,Puducherry,137.25,00:09,09:08,09:17,1368.40
34,130696,1286,firstClass,GoAir,2021-04-26 00:00:00,Puducherry,Chennai,137.25,00:09,19:13,19:22,1530.00
35,130775,1286,firstClass,Air India,2020-06-28 00:00:00,Jamshedpur,Shimla,1283.89,01:25,05:35,07:00,7388.20

In [48]:
round_6 = pd.merge(r6,round_6, on=['User_ID','Departure','Arrival'], how="inner")
round_6

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price,Departure_Date,Return_Date,Roundtrip_Cost
0,9126,93,economic,Akasa Air,11/07/2019,Ludhiana,Dabolim,1739.21,01:55,04:33,06:28,6076.38,2019-07-15,2019-11-07,12352.76
1,9218,93,firstClass,AirAsia India,2020-09-08 00:00:00,Puducherry,Guwahati,2016.86,02:14,14:39,16:53,11186.80,2020-04-09,2020-09-08,18138.88
2,9231,93,economic,Akasa Air,2020-01-30 00:00:00,Bilaspur,Hyderabad,649.95,00:43,04:22,05:05,2646.60,2020-01-23,2020-01-30,5702.52
3,66020,641,firstClass,AirAsia India,2020-08-18 00:00:00,Hyderabad,Surat,726.71,00:48,17:28,18:16,4413.55,2020-08-13,2020-08-18,8827.10
4,66044,641,economic,Akasa Air,08/05/2021,Navi Mumbai,Dabolim,415.65,00:27,11:37,12:04,1907.70,2021-05-19,2021-08-05,3865.40
5,66046,641,economic,Akasa Air,2021-08-19 00:00:00,Nashik,Surat,166.63,00:11,05:34,05:45,1124.64,2021-04-08,2021-08-19,2599.04
6,75625,737,firstClass,Air India,24/10/2019,Puri,Coimbatore,1362.16,01:30,20:20,21:50,7998.30,2019-10-10,2019-10-24,13995.08
7,75724,737,firstClass,GoAir,2020-11-26 00:00:00,Mumbai,Jaipur,921.69,01:01,20:17,21:18,5647.20,2020-11-19,2020-11-26,9149.52
8,75750,737,premium,IndiGo,2020-12-17 00:00:00,Puri,Puducherry,1084.01,01:12,09:34,10:46,4896.84,2020-03-12,2020-12-17,9643.68
9,104726,1039,economic,Akasa Air,2021-05-09 00:00:00,Raigarh,Visakhapatnam,469.41,00:31,03:29,04:00,2077.98,2021-04-29,2021-05-09,5361.28
10,104731,1039,firstClass,SpiceJet,31/02/2022,Ranchi,Bilaspur,352.67,00:23,06:00,06:23,2669.60,2022-02-17,2022-02-25,4851.31
11,104753,1039,economic,IndiGo,2022-04-19 00:00:00,Amritsar,Delhi NCR,391.51,00:26,03:06,03:32,1833.03,2022-04-14,2022-04-19,4488.08
12,105006,1041,economic,Akasa Air,2020-08-01 00:00:00,Kullu-Manali,Chandigarh,131.49,00:08,22:27,22:35,1012.47,2020-07-23,2020-08-01,2349.92
13,105129,1041,premium,Air India,2022-07-27 00:00:00,Thiruvananthapuram,Guwahati,2512.60,02:47,18:38,21:25,10346.26,2022-07-14,2022-07-27,24335.51
14,105134,1041,economic,IndiGo,2020-11-26 00:00:00,Mysuru,Chennai,404.42,00:26,12:51,13:17,1871.76,2020-11-19,2020-11-26,4611.36
15,130685,1286,firstClass,Air India,2020-07-28 00:00:00,Srinagar,Mopa,7566.74,08:24,17:11,01:35,40373.70,2020-07-23,2020-07-28,80917.40
16,130696,1286,firstClass,GoAir,2021-04-26 00:00:00,Puducherry,Chennai,137.25,00:09,19:13,19:22,1530.00,2021-04-15,2021-04-26,2898.40
17,130775,1286,firstClass,Air India,2020-06-28 00:00:00,Jamshedpur,Shimla,1283.89,01:25,05:35,07:00,7388.20,2020-06-25,2020-06-28,14746.40

In [49]:
round_6 = round_6[reorder]
round_6

,travelCode,User_ID,Departure,Arrival,Departure_Date,Return_Date,flightType,Flight_agency,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Roundtrip_Cost
0,9126,93,Ludhiana,Dabolim,2019-07-15,2019-11-07,economic,Akasa Air,1739.21,01:55,04:33,06:28,12352.76
1,9218,93,Puducherry,Guwahati,2020-04-09,2020-09-08,firstClass,AirAsia India,2016.86,02:14,14:39,16:53,18138.88
2,9231,93,Bilaspur,Hyderabad,2020-01-23,2020-01-30,economic,Akasa Air,649.95,00:43,04:22,05:05,5702.52
3,66020,641,Hyderabad,Surat,2020-08-13,2020-08-18,firstClass,AirAsia India,726.71,00:48,17:28,18:16,8827.10
4,66044,641,Navi Mumbai,Dabolim,2021-05-19,2021-08-05,economic,Akasa Air,415.65,00:27,11:37,12:04,3865.40
5,66046,641,Nashik,Surat,2021-04-08,2021-08-19,economic,Akasa Air,166.63,00:11,05:34,05:45,2599.04
6,75625,737,Puri,Coimbatore,2019-10-10,2019-10-24,firstClass,Air India,1362.16,01:30,20:20,21:50,13995.08
7,75724,737,Mumbai,Jaipur,2020-11-19,2020-11-26,firstClass,GoAir,921.69,01:01,20:17,21:18,9149.52
8,75750,737,Puri,Puducherry,2020-03-12,2020-12-17,premium,IndiGo,1084.01,01:12,09:34,10:46,9643.68
9,104726,1039,Raigarh,Visakhapatnam,2021-04-29,2021-05-09,economic,Akasa Air,469.41,00:31,03:29,04:00,5361.28
10,104731,1039,Ranchi,Bilaspur,2022-02-17,2022-02-25,firstClass,SpiceJet,352.67,00:23,06:00,06:23,4851.31
11,104753,1039,Amritsar,Delhi NCR,2022-04-14,2022-04-19,economic,IndiGo,391.51,00:26,03:06,03:32,4488.08
12,105006,1041,Kullu-Manali,Chandigarh,2020-07-23,2020-08-01,economic,Akasa Air,131.49,00:08,22:27,22:35,2349.92
13,105129,1041,Thiruvananthapuram,Guwahati,2022-07-14,2022-07-27,premium,Air India,2512.60,02:47,18:38,21:25,24335.51
14,105134,1041,Mysuru,Chennai,2020-11-19,2020-11-26,economic,IndiGo,404.42,00:26,12:51,13:17,4611.36
15,130685,1286,Srinagar,Mopa,2020-07-23,2020-07-28,firstClass,Air India,7566.74,08:24,17:11,01:35,80917.40
16,130696,1286,Puducherry,Chennai,2021-04-15,2021-04-26,firstClass,GoAir,137.25,00:09,19:13,19:22,2898.40
17,130775,1286,Jamshedpur,Shimla,2020-06-25,2020-06-28,firstClass,Air India,1283.89,01:25,05:35,07:00,14746.40

In [50]:
round_3 = pd.read_excel("users_3_occurrences.xlsx")
round_3

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price,Return_Date
0,46192,450,firstClass,GoAir,13/02/2020,Puducherry,Varanasi,1525.15,01:41,02:00,03:41,17269.00,2020-02-26
1,46247,450,firstClass,Air India,2020-02-26 00:00:00,Varanasi,Puducherry,1525.15,01:41,23:36,01:17,8654.50,NaT
2,46309,450,economic,Air India,05/12/2022,Puducherry,Varanasi,1525.15,01:41,10:29,12:10,10904.00,2022-12-08
3,96876,958,firstClass,AirAsia India,04/09/2020,Mopa,Amritsar,7551.25,08:23,00:31,08:54,69385.10,2020-09-10
4,96954,958,premium,IndiGo,2020-09-10 00:00:00,Amritsar,Mopa,7551.25,08:23,11:04,19:27,29142.60,NaT
5,96982,958,economic,Akasa Air,21/04/2022,Amritsar,Mopa,7551.25,08:23,06:25,14:48,49171.00,2022-04-28
6,111856,1108,premium,Akasa Air,14/05/2020,Hisar,Shillong,6610.02,07:20,21:09,04:29,51568.14,2020-05-22
7,111935,1108,premium,IndiGo,18/11/2021,Hisar,Shillong,6610.02,07:20,19:11,02:31,61084.17,2021-11-28
8,111957,1108,firstClass,AirAsia India,2021-11-28 00:00:00,Shillong,Hisar,6610.02,07:20,14:56,22:16,35300.10,NaT

In [53]:
round_3 = round_3.dropna(subset=['Return_Date'])
round_3

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price,Return_Date
0,46192,450,firstClass,GoAir,13/02/2020,Puducherry,Varanasi,1525.15,01:41,02:00,03:41,17269.00,2020-02-26
2,46309,450,economic,Air India,05/12/2022,Puducherry,Varanasi,1525.15,01:41,10:29,12:10,10904.00,2022-12-08
3,96876,958,firstClass,AirAsia India,04/09/2020,Mopa,Amritsar,7551.25,08:23,00:31,08:54,69385.10,2020-09-10
5,96982,958,economic,Akasa Air,21/04/2022,Amritsar,Mopa,7551.25,08:23,06:25,14:48,49171.00,2022-04-28
6,111856,1108,premium,Akasa Air,14/05/2020,Hisar,Shillong,6610.02,07:20,21:09,04:29,51568.14,2020-05-22
7,111935,1108,premium,IndiGo,18/11/2021,Hisar,Shillong,6610.02,07:20,19:11,02:31,61084.17,2021-11-28

In [57]:
round_3 = round_3.rename(columns={'Departure_date':'Departure_Date','Calculated_Flight_Price':'Roundtrip_Cost'})

In [59]:
round_3 = round_3[reorder]
round_3

,travelCode,User_ID,Departure,Arrival,Departure_Date,Return_Date,flightType,Flight_agency,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Roundtrip_Cost
0,46192,450,Puducherry,Varanasi,13/02/2020,2020-02-26,firstClass,GoAir,1525.15,01:41,02:00,03:41,17269.00
2,46309,450,Puducherry,Varanasi,05/12/2022,2022-12-08,economic,Air India,1525.15,01:41,10:29,12:10,10904.00
3,96876,958,Mopa,Amritsar,04/09/2020,2020-09-10,firstClass,AirAsia India,7551.25,08:23,00:31,08:54,69385.10
5,96982,958,Amritsar,Mopa,21/04/2022,2022-04-28,economic,Akasa Air,7551.25,08:23,06:25,14:48,49171.00
6,111856,1108,Hisar,Shillong,14/05/2020,2020-05-22,premium,Akasa Air,6610.02,07:20,21:09,04:29,51568.14
7,111935,1108,Hisar,Shillong,18/11/2021,2021-11-28,premium,IndiGo,6610.02,07:20,19:11,02:31,61084.17

In [99]:
round_2

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price,Return Date,Total Flights,Total Flight Cost
0,503,4,firstClass,Air India,2021-03-25,Itanagar,Surat,2204.62,02:26,00:56,03:22,12220.60,2021-04-02,2,19782.96
2,1479,13,economic,IndiGo,2020-09-07,Bengaluru,Visakhapatnam,797.17,00:53,01:41,02:34,3110.76,2020-09-15,2,6441.52
4,1666,15,firstClass,Air India,2019-11-28,Chandigarh,Navi Mumbai,1355.13,01:30,11:12,12:42,7763.15,2019-12-09,2,12681.04
6,2069,18,premium,Akasa Air,2021-01-28,Kota,Visakhapatnam,3406.67,03:47,03:42,07:29,13476.91,2021-01-31,2,27003.82
8,2383,21,economic,IndiGo,2021-06-17,Shillong,Diu,2201.44,02:26,16:15,18:41,7532.82,2021-07-01,2,15115.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,132731,1307,firstClass,SpiceJet,2020-05-21,Ranchi,Dhubri,558.25,00:37,22:07,22:44,3550.00,2020-05-24,2,7080.00
380,133011,1311,economic,Air India,2020-07-30,Gwalior,Nashik,825.13,00:55,09:03,09:58,3449.14,2020-08-03,2,8581.04
382,133492,1315,economic,Akasa Air,2021-06-05,Shimla,Delhi NCR,271.89,00:18,06:52,07:10,1656.17,2021-06-17,2,3112.34
384,134586,1323,premium,Air India,2021-12-16,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84,2021-12-30,2,14442.79
386,135670,1335,firstClass,IndiGo,2019-11-28,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25,2019-12-06,2,30903.11

In [100]:
round_2 = round_2.rename(columns={'Departure_date':'Departure_Date','Return Date':'Return_Date','Total Flight Cost':'Roundtrip_Cost'})
round_2 = round_2[reorder]

In [102]:
Final_RoundTripp = pd.concat([round_2, round_3, round__4, round_6], ignore_index=True)

In [89]:
round_6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   travelCode               18 non-null     int64
 1   User_ID                  18 non-null     int64
 2   Departure                18 non-null     object
 3   Arrival                  18 non-null     object
 4   Departure_Date           18 non-null     datetime64[ns]
 5   Return_Date              18 non-null     datetime64[ns]
 6   flightType               18 non-null     object
 7   Flight_agency            18 non-null     object
 8   Flight Distance (km)     18 non-null     float64
 9   Flight Duration (hh:mm)  18 non-null     object
 10  Departure Time           18 non-null     object
 11  Arrival Time             18 non-null     object
 12  Roundtrip_Cost           18 non-null     float64
dtypes: datetime64[ns](2), float64(2), int64(2), object(7)
memory usage: 2.0+ KB

In [103]:
Final_RoundTripp.to_excel('Final_RoundTripp.xlsx', index=False)
from IPython.display import FileLink
FileLink('Final_RoundTripp.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\Final_RoundTripp.xlsx

In [92]:
update = pd.read_excel('Final_RoundTrip_Buffered.xlsx')
update

,travelCode,User_ID,Departure,Arrival,Departure_Date,Return_Date,flightType,Flight_agency,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Roundtrip_Cost,Return Departure Time,Return Arrival Time
0,503,4,Itanagar,Surat,2021-03-25 00:00:00,2021-04-02,firstClass,Air India,2204.62,0.101389,00:56,03:22:00,12220.60,05:22,07:48
1,1479,13,Bengaluru,Visakhapatnam,2020-09-07 00:00:00,2020-09-15,economic,IndiGo,797.17,0.036806,01:41,02:34:00,3110.76,04:34,05:27
2,1666,15,Chandigarh,Navi Mumbai,2019-11-28 00:00:00,2019-12-09,firstClass,Air India,1355.13,0.062500,11:12,12:42:00,7763.15,14:42,16:12
3,2069,18,Kota,Visakhapatnam,2021-01-28 00:00:00,2021-01-31,premium,Akasa Air,3406.67,0.157639,03:42,07:29:00,13476.91,09:29,13:16
4,2383,21,Shillong,Diu,2021-06-17 00:00:00,2021-07-01,economic,IndiGo,2201.44,0.101389,16:15,18:41:00,7532.82,20:41,23:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,105129,1041,Thiruvananthapuram,Guwahati,2022-07-14 00:00:00,2022-07-27,premium,Air India,2512.60,0.115972,18:38,21:25:00,24335.51,23:25,02:12
284,105134,1041,Mysuru,Chennai,2020-11-19 00:00:00,2020-11-26,economic,IndiGo,404.42,0.018056,12:51,13:17:00,4611.36,15:17,15:43
285,130685,1286,Srinagar,Mopa,2020-07-23 00:00:00,2020-07-28,firstClass,Air India,7566.74,0.350000,17:11,01:35:00,80917.40,03:35,11:59
286,130696,1286,Puducherry,Chennai,2021-04-15 00:00:00,2021-04-26,firstClass,GoAir,137.25,0.006250,19:13,19:22:00,2898.40,21:22,21:31
287,130775,1286,Jamshedpur,Shimla,2020-06-25 00:00:00,2020-06-28,firstClass,Air India,1283.89,0.059028,05:35,07:00:00,14746.40,09:00,10:25

In [93]:
Final_RoundTrip['Return Departure Time'] = update['Return Departure Time']
Final_RoundTrip

,travelCode,User_ID,Departure,Arrival,Departure_Date,Return_Date,flightType,Flight_agency,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Roundtrip_Cost,Return Departure Time
0,503,4,Itanagar,Surat,2021-03-25 00:00:00,2021-04-02,firstClass,Air India,2204.62,02:26,00:56,03:22,12220.60,05:22
1,1479,13,Bengaluru,Visakhapatnam,2020-09-07 00:00:00,2020-09-15,economic,IndiGo,797.17,00:53,01:41,02:34,3110.76,04:34
2,1666,15,Chandigarh,Navi Mumbai,2019-11-28 00:00:00,2019-12-09,firstClass,Air India,1355.13,01:30,11:12,12:42,7763.15,14:42
3,2069,18,Kota,Visakhapatnam,2021-01-28 00:00:00,2021-01-31,premium,Akasa Air,3406.67,03:47,03:42,07:29,13476.91,09:29
4,2383,21,Shillong,Diu,2021-06-17 00:00:00,2021-07-01,economic,IndiGo,2201.44,02:26,16:15,18:41,7532.82,20:41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,105129,1041,Thiruvananthapuram,Guwahati,2022-07-14 00:00:00,2022-07-27,premium,Air India,2512.60,02:47,18:38,21:25,24335.51,23:25
284,105134,1041,Mysuru,Chennai,2020-11-19 00:00:00,2020-11-26,economic,IndiGo,404.42,00:26,12:51,13:17,4611.36,15:17
285,130685,1286,Srinagar,Mopa,2020-07-23 00:00:00,2020-07-28,firstClass,Air India,7566.74,08:24,17:11,01:35,80917.40,03:35
286,130696,1286,Puducherry,Chennai,2021-04-15 00:00:00,2021-04-26,firstClass,GoAir,137.25,00:09,19:13,19:22,2898.40,21:22
287,130775,1286,Jamshedpur,Shimla,2020-06-25 00:00:00,2020-06-28,firstClass,Air India,1283.89,01:25,05:35,07:00,14746.40,09:00

In [94]:
Final_RoundTrip['Return Arrival Time'] = update['Return Arrival Time']
Final_RoundTrip

,travelCode,User_ID,Departure,Arrival,Departure_Date,Return_Date,flightType,Flight_agency,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Roundtrip_Cost,Return Departure Time,Return Arrival Time
0,503,4,Itanagar,Surat,2021-03-25 00:00:00,2021-04-02,firstClass,Air India,2204.62,02:26,00:56,03:22,12220.60,05:22,07:48
1,1479,13,Bengaluru,Visakhapatnam,2020-09-07 00:00:00,2020-09-15,economic,IndiGo,797.17,00:53,01:41,02:34,3110.76,04:34,05:27
2,1666,15,Chandigarh,Navi Mumbai,2019-11-28 00:00:00,2019-12-09,firstClass,Air India,1355.13,01:30,11:12,12:42,7763.15,14:42,16:12
3,2069,18,Kota,Visakhapatnam,2021-01-28 00:00:00,2021-01-31,premium,Akasa Air,3406.67,03:47,03:42,07:29,13476.91,09:29,13:16
4,2383,21,Shillong,Diu,2021-06-17 00:00:00,2021-07-01,economic,IndiGo,2201.44,02:26,16:15,18:41,7532.82,20:41,23:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,105129,1041,Thiruvananthapuram,Guwahati,2022-07-14 00:00:00,2022-07-27,premium,Air India,2512.60,02:47,18:38,21:25,24335.51,23:25,02:12
284,105134,1041,Mysuru,Chennai,2020-11-19 00:00:00,2020-11-26,economic,IndiGo,404.42,00:26,12:51,13:17,4611.36,15:17,15:43
285,130685,1286,Srinagar,Mopa,2020-07-23 00:00:00,2020-07-28,firstClass,Air India,7566.74,08:24,17:11,01:35,80917.40,03:35,11:59
286,130696,1286,Puducherry,Chennai,2021-04-15 00:00:00,2021-04-26,firstClass,GoAir,137.25,00:09,19:13,19:22,2898.40,21:22,21:31
287,130775,1286,Jamshedpur,Shimla,2020-06-25 00:00:00,2020-06-28,firstClass,Air India,1283.89,01:25,05:35,07:00,14746.40,09:00,10:25

In [95]:
Final_RoundTrip.to_excel('Final_Updated_RoundTrip.xlsx', index=False)
from IPython.display import FileLink
FileLink('Final_Updated_RoundTrip.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\Final_Updated_RoundTrip.xlsx

In [96]:
round_2

,travelCode,User_ID,Departure,Arrival,Departure_Date,Return_Date,flightType,Flight_agency,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Roundtrip_Cost
0,503,4,Itanagar,Surat,2021-03-25,2021-04-02,firstClass,Air India,2204.62,02:26,00:56,03:22,12220.60
2,1479,13,Bengaluru,Visakhapatnam,2020-09-07,2020-09-15,economic,IndiGo,797.17,00:53,01:41,02:34,3110.76
4,1666,15,Chandigarh,Navi Mumbai,2019-11-28,2019-12-09,firstClass,Air India,1355.13,01:30,11:12,12:42,7763.15
6,2069,18,Kota,Visakhapatnam,2021-01-28,2021-01-31,premium,Akasa Air,3406.67,03:47,03:42,07:29,13476.91
8,2383,21,Shillong,Diu,2021-06-17,2021-07-01,economic,IndiGo,2201.44,02:26,16:15,18:41,7532.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,132731,1307,Ranchi,Dhubri,2020-05-21,2020-05-24,firstClass,SpiceJet,558.25,00:37,22:07,22:44,3550.00
380,133011,1311,Gwalior,Nashik,2020-07-30,2020-08-03,economic,Air India,825.13,00:55,09:03,09:58,3449.14
382,133492,1315,Shimla,Delhi NCR,2021-06-05,2021-06-17,economic,Akasa Air,271.89,00:18,06:52,07:10,1656.17
384,134586,1323,Hyderabad,Dehradun,2021-12-16,2021-12-30,premium,Air India,1439.54,01:35,19:57,21:32,6288.84
386,135670,1335,Raigarh,Kota,2019-11-28,2019-12-06,firstClass,IndiGo,3289.60,03:39,10:34,14:13,17869.25