In [1]:
import pandas as pd

In [3]:
Round_chatgpt = pd.read_excel('Final_RoundTripp_Modified_Updated.xlsx')
Round_chatgpt

,travelCode,User_ID,Departure,Arrival,Departure_Date,Return_Date,flightType,Flight_agency,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Roundtrip_Cost,Return Departure Time,Return Arrival Time,Modified_Departure_Date,Modified_Return_Date,arrival_date,return_arrival_date
0,503,4,Itanagar,Surat,2021-03-25,2021-04-02,firstClass,Air India,2204.62,0.101389,0.038889,0.140278,19782.96,0.223611,0.325000,2021-03-25 00:56:00,2021-04-02 05:22:00,2021-03-25 03:22:00,2021-04-02 07:48:00
1,1479,13,Bengaluru,Visakhapatnam,2020-09-07,2020-09-15,economic,IndiGo,797.17,0.036806,0.070139,0.106944,6441.52,0.190278,0.227083,2020-09-07 01:41:00,2020-09-15 04:34:00,2020-09-07 02:34:00,2020-09-15 05:27:00
2,1666,15,Chandigarh,Navi Mumbai,2019-11-28,2019-12-09,firstClass,Air India,1355.13,0.062500,0.466667,0.529167,12681.04,0.612500,0.675000,2019-11-28 11:12:00,2019-12-09 14:42:00,2019-11-28 12:42:00,2019-12-09 16:12:00
3,2069,18,Kota,Visakhapatnam,2021-01-28,2021-01-31,premium,Akasa Air,3406.67,0.157639,0.154167,0.311806,27003.82,0.395139,0.552778,2021-01-28 03:42:00,2021-01-31 09:29:00,2021-01-28 07:29:00,2021-01-31 13:16:00
4,2383,21,Shillong,Diu,2021-06-17,2021-07-01,economic,IndiGo,2201.44,0.101389,0.677083,0.778472,15115.64,0.861806,0.963194,2021-06-17 16:15:00,2021-07-01 20:41:00,2021-06-17 18:41:00,2021-07-01 23:07:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,105129,1041,Thiruvananthapuram,Guwahati,2022-07-14,2022-07-27,premium,Air India,2512.60,0.115972,0.776389,0.892361,24335.51,0.975694,0.091667,2022-07-14 18:38:00,2022-07-27 23:25:00,2022-07-14 21:25:00,2022-07-27 02:12:00
284,105134,1041,Mysuru,Chennai,2020-11-19,2020-11-26,economic,IndiGo,404.42,0.018056,0.535417,0.553472,4611.36,0.636806,0.654861,2020-11-19 12:51:00,2020-11-26 15:17:00,2020-11-19 13:17:00,2020-11-26 15:43:00
285,130685,1286,Srinagar,Mopa,2020-07-23,2020-07-28,firstClass,Air India,7566.74,0.350000,0.715972,0.065972,80917.40,0.149306,0.499306,2020-07-23 17:11:00,2020-07-28 03:35:00,2020-07-23 01:35:00,2020-07-28 11:59:00
286,130696,1286,Puducherry,Chennai,2021-04-15,2021-04-26,firstClass,GoAir,137.25,0.006250,0.800694,0.806944,2898.40,0.890278,0.896528,2021-04-15 19:13:00,2021-04-26 21:22:00,2021-04-15 19:22:00,2021-04-26 21:31:00
287,130775,1286,Jamshedpur,Shimla,2020-06-25,2020-06-28,firstClass,Air India,1283.89,0.059028,0.232639,0.291667,14746.40,0.375000,0.434028,2020-06-25 05:35:00,2020-06-28 09:00:00,2020-06-25 07:00:00,2020-06-28 10:25:00

In [4]:
# Round_chatgpt.drop(columns={'Departure_Date','Return_Date'})
Round_chatgpt.head(20)

,travelCode,User_ID,Departure,Arrival,Departure_Date,Return_Date,flightType,Flight_agency,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Roundtrip_Cost,Return Departure Time,Return Arrival Time,Modified_Departure_Date,Modified_Return_Date,arrival_date,return_arrival_date
0,503,4,Itanagar,Surat,2021-03-25,2021-04-02,firstClass,Air India,2204.62,0.101389,0.038889,0.140278,19782.96,0.223611,0.325000,2021-03-25 00:56:00,2021-04-02 05:22:00,2021-03-25 03:22:00,2021-04-02 07:48:00
1,1479,13,Bengaluru,Visakhapatnam,2020-09-07,2020-09-15,economic,IndiGo,797.17,0.036806,0.070139,0.106944,6441.52,0.190278,0.227083,2020-09-07 01:41:00,2020-09-15 04:34:00,2020-09-07 02:34:00,2020-09-15 05:27:00
2,1666,15,Chandigarh,Navi Mumbai,2019-11-28,2019-12-09,firstClass,Air India,1355.13,0.062500,0.466667,0.529167,12681.04,0.612500,0.675000,2019-11-28 11:12:00,2019-12-09 14:42:00,2019-11-28 12:42:00,2019-12-09 16:12:00
3,2069,18,Kota,Visakhapatnam,2021-01-28,2021-01-31,premium,Akasa Air,3406.67,0.157639,0.154167,0.311806,27003.82,0.395139,0.552778,2021-01-28 03:42:00,2021-01-31 09:29:00,2021-01-28 07:29:00,2021-01-31 13:16:00
4,2383,21,Shillong,Diu,2021-06-17,2021-07-01,economic,IndiGo,2201.44,0.101389,0.677083,0.778472,15115.64,0.861806,0.963194,2021-06-17 16:15:00,2021-07-01 20:41:00,2021-06-17 18:41:00,2021-07-01 23:07:00
5,2691,23,Bilaspur,Dabolim,2020-12-11,2020-12-18,firstClass,GoAir,1149.76,0.052778,0.842361,0.895139,11084.08,0.978472,0.031250,2020-12-11 20:13:00,2020-12-18 23:29:00,2020-12-11 21:29:00,2020-12-18 00:45:00
6,3787,39,Kota,Mopa,2020-09-04,2020-09-13,economic,IndiGo,5169.94,0.238889,0.840972,0.079861,44823.52,0.163194,0.402083,2020-09-04 20:11:00,2020-09-13 03:55:00,2020-09-04 01:55:00,2020-09-13 09:39:00
7,4108,41,Bilaspur,Hisar,2020-12-03,2020-12-13,firstClass,IndiGo,6022.62,0.278472,0.225694,0.504167,51786.96,0.587500,0.865972,2020-12-03 05:25:00,2020-12-13 14:06:00,2020-12-03 12:06:00,2020-12-13 20:47:00
8,4381,44,Hisar,Khowai,2020-06-18,2020-06-29,economic,SpiceJet,6682.72,0.309028,0.802778,0.111806,57561.76,0.195139,0.504167,2020-06-18 19:16:00,2020-06-29 04:41:00,2020-06-18 02:41:00,2020-06-29 12:06:00
9,5206,52,Bhopal,Puri,2020-11-19,2020-11-25,economic,IndiGo,951.91,0.043750,0.452083,0.495833,7994.46,0.579167,0.622917,2020-11-19 10:51:00,2020-11-25 13:54:00,2020-11-19 11:54:00,2020-11-25 14:57:00
10,5372,54,Bhubaneswar,Puri,2020-02-13,2020-02-20,premium,Air India,52.73,0.002083,0.374306,0.376389,1895.86,0.459722,0.461806,2020-02-13 08:59:00,2020-02-20 11:02:00,2020-02-13 09:02:00,2020-02-20 11:05:00
11,5472,55,Puducherry,Delhi NCR,2020-02-20,2020-03-02,firstClass,SpiceJet,1881.72,0.086806,0.922917,0.009722,21174.70,0.093056,0.179861,2020-02-20 22:09:00,2020-03-02 02:14:00,2020-02-20 00:14:00,2020-03-02 04:19:00
12,5587,56,Hisar,Navi Mumbai,2019-12-19,2019-12-30,firstClass,GoAir,5467.58,0.252778,0.746528,0.999306,50778.99,0.082639,0.335417,2019-12-19 17:55:00,2019-12-30 01:59:00,2019-12-19 23:59:00,2019-12-30 08:03:00
13,6288,62,Chennai,Kota,2021-01-14,2021-01-17,premium,SpiceJet,3333.78,0.154167,0.514583,0.668750,31332.41,0.752083,0.906250,2021-01-14 12:21:00,2021-01-17 18:03:00,2021-01-14 16:03:00,2021-01-17 21:45:00
14,6765,65,Navi Mumbai,Ahmedabad,2020-10-12,2020-10-18,economic,Air India,445.78,0.020139,0.208333,0.228472,5210.24,0.311806,0.331944,2020-10-12 05:00:00,2020-10-18 07:29:00,2020-10-12 05:29:00,2020-10-18 07:58:00
15,7793,75,Delhi NCR,Ayodhya,2020-07-23,2020-07-31,premium,Akasa Air,545.38,0.025000,0.079167,0.104167,6342.47,0.187500,0.212500,2020-07-23 01:54:00,2020-07-31 04:30:00,2020-07-23 02:30:00,2020-07-31 05:06:00
16,8834,90,Puducherry,Ahmedabad,2019-10-24,2019-11-03,economic,Akasa Air,1452.17,0.066667,0.365278,0.431944,13603.36,0.515278,0.581944,2019-10-24 08:46:00,2019-11-03 12:22:00,2019-10-24 10:22:00,2019-11-03 13:58:00
17,9713,96,Itanagar,Coimbatore,2021-02-09,2021-02-18,firstClass,AirAsia India,2495.63,0.115278,0.485417,0.600694,27601.30,0.684028,0.799306,2021-02-09 11:39:00,2021-02-18 16:25:00,2021-02-09 14:25:00,2021-02-18 19:11:00
18,10472,105,Coimbatore,Pune,2022-11-08,2022-11-18,firstClass,Akasa Air,899.88,0.040972,0.111806,0.152778,10661.30,0.236111,0.277083,2022-11-08 02:41:00,2022-11-18 05:40:00,2022-11-08 03:40:00,2022-11-18 06:39:00
19,11868,116,Guwahati,Visakhapatnam,2020-01-23,2020-01-30,economic,IndiGo,1291.75,0.059722,0.738889,0.798611,9357.50,0.881944,0.941667,2020-01-23 17:44:00,2020-01-30 21:10:00,2020-01-23 19:10:00,2020-01-30 22:36:00

In [30]:

import pandas as pd

# Load the dataset
import pandas as pd

# Load the dataset (ensuring Flight Duration is read as a string)
df = pd.read_excel('Final_RoundTripp_Modified_Updated.xlsx', dtype={'Flight Duration (hh:mm)': str})

# Convert date columns to datetime format
df['Modified_Departure_Date'] = pd.to_datetime(df['Modified_Departure_Date'])
df['Modified_Return_Date'] = pd.to_datetime(df['Modified_Return_Date'])

# Ensure 'Flight Duration (hh:mm)' is formatted correctly and append ':00' for seconds
df['Flight_Duration'] = a['Flight Duration (hh:mm)'].astype(str) + ':00'

# Convert 'Flight_Duration' to timedelta
df['Flight_Duration'] = pd.to_timedelta(df['Flight_Duration'])

# Compute new arrival dates
df['arrival_date'] = df['Modified_Departure_Date'] + df['Flight_Duration']
df['return_arrival_date'] = df['Modified_Return_Date'] + df['Flight_Duration']


# Display the updated DataFrame
df = df.drop(columns=['Flight Duration (hh:mm)'])

df.head(20)

,travelCode,User_ID,Departure,Arrival,Departure_Date,Return_Date,flightType,Flight_agency,Flight Distance (km),Departure Time,Arrival Time,Roundtrip_Cost,Return Departure Time,Return Arrival Time,Modified_Departure_Date,Modified_Return_Date,arrival_date,return_arrival_date,Flight_Duration
0,503,4,Itanagar,Surat,2021-03-25,2021-04-02,firstClass,Air India,2204.62,0.038889,0.140278,19782.96,0.223611,0.325000,2021-03-25 00:56:00,2021-04-02 05:22:00,2021-03-25 03:22:00,2021-04-02 07:48:00,0 days 02:26:00
1,1479,13,Bengaluru,Visakhapatnam,2020-09-07,2020-09-15,economic,IndiGo,797.17,0.070139,0.106944,6441.52,0.190278,0.227083,2020-09-07 01:41:00,2020-09-15 04:34:00,2020-09-07 02:34:00,2020-09-15 05:27:00,0 days 00:53:00
2,1666,15,Chandigarh,Navi Mumbai,2019-11-28,2019-12-09,firstClass,Air India,1355.13,0.466667,0.529167,12681.04,0.612500,0.675000,2019-11-28 11:12:00,2019-12-09 14:42:00,2019-11-28 12:42:00,2019-12-09 16:12:00,0 days 01:30:00
3,2069,18,Kota,Visakhapatnam,2021-01-28,2021-01-31,premium,Akasa Air,3406.67,0.154167,0.311806,27003.82,0.395139,0.552778,2021-01-28 03:42:00,2021-01-31 09:29:00,2021-01-28 07:29:00,2021-01-31 13:16:00,0 days 03:47:00
4,2383,21,Shillong,Diu,2021-06-17,2021-07-01,economic,IndiGo,2201.44,0.677083,0.778472,15115.64,0.861806,0.963194,2021-06-17 16:15:00,2021-07-01 20:41:00,2021-06-17 18:41:00,2021-07-01 23:07:00,0 days 02:26:00
5,2691,23,Bilaspur,Dabolim,2020-12-11,2020-12-18,firstClass,GoAir,1149.76,0.842361,0.895139,11084.08,0.978472,0.031250,2020-12-11 20:13:00,2020-12-18 23:29:00,2020-12-11 21:29:00,2020-12-19 00:45:00,0 days 01:16:00
6,3787,39,Kota,Mopa,2020-09-04,2020-09-13,economic,IndiGo,5169.94,0.840972,0.079861,44823.52,0.163194,0.402083,2020-09-04 20:11:00,2020-09-13 03:55:00,2020-09-05 01:55:00,2020-09-13 09:39:00,0 days 05:44:00
7,4108,41,Bilaspur,Hisar,2020-12-03,2020-12-13,firstClass,IndiGo,6022.62,0.225694,0.504167,51786.96,0.587500,0.865972,2020-12-03 05:25:00,2020-12-13 14:06:00,2020-12-03 12:06:00,2020-12-13 20:47:00,0 days 06:41:00
8,4381,44,Hisar,Khowai,2020-06-18,2020-06-29,economic,SpiceJet,6682.72,0.802778,0.111806,57561.76,0.195139,0.504167,2020-06-18 19:16:00,2020-06-29 04:41:00,2020-06-19 02:41:00,2020-06-29 12:06:00,0 days 07:25:00
9,5206,52,Bhopal,Puri,2020-11-19,2020-11-25,economic,IndiGo,951.91,0.452083,0.495833,7994.46,0.579167,0.622917,2020-11-19 10:51:00,2020-11-25 13:54:00,2020-11-19 11:54:00,2020-11-25 14:57:00,0 days 01:03:00
10,5372,54,Bhubaneswar,Puri,2020-02-13,2020-02-20,premium,Air India,52.73,0.374306,0.376389,1895.86,0.459722,0.461806,2020-02-13 08:59:00,2020-02-20 11:02:00,2020-02-13 09:02:00,2020-02-20 11:05:00,0 days 00:03:00
11,5472,55,Puducherry,Delhi NCR,2020-02-20,2020-03-02,firstClass,SpiceJet,1881.72,0.922917,0.009722,21174.70,0.093056,0.179861,2020-02-20 22:09:00,2020-03-02 02:14:00,2020-02-21 00:14:00,2020-03-02 04:19:00,0 days 02:05:00
12,5587,56,Hisar,Navi Mumbai,2019-12-19,2019-12-30,firstClass,GoAir,5467.58,0.746528,0.999306,50778.99,0.082639,0.335417,2019-12-19 17:55:00,2019-12-30 01:59:00,2019-12-19 23:59:00,2019-12-30 08:03:00,0 days 06:04:00
13,6288,62,Chennai,Kota,2021-01-14,2021-01-17,premium,SpiceJet,3333.78,0.514583,0.668750,31332.41,0.752083,0.906250,2021-01-14 12:21:00,2021-01-17 18:03:00,2021-01-14 16:03:00,2021-01-17 21:45:00,0 days 03:42:00
14,6765,65,Navi Mumbai,Ahmedabad,2020-10-12,2020-10-18,economic,Air India,445.78,0.208333,0.228472,5210.24,0.311806,0.331944,2020-10-12 05:00:00,2020-10-18 07:29:00,2020-10-12 05:29:00,2020-10-18 07:58:00,0 days 00:29:00
15,7793,75,Delhi NCR,Ayodhya,2020-07-23,2020-07-31,premium,Akasa Air,545.38,0.079167,0.104167,6342.47,0.187500,0.212500,2020-07-23 01:54:00,2020-07-31 04:30:00,2020-07-23 02:30:00,2020-07-31 05:06:00,0 days 00:36:00
16,8834,90,Puducherry,Ahmedabad,2019-10-24,2019-11-03,economic,Akasa Air,1452.17,0.365278,0.431944,13603.36,0.515278,0.581944,2019-10-24 08:46:00,2019-11-03 12:22:00,2019-10-24 10:22:00,2019-11-03 13:58:00,0 days 01:36:00
17,9713,96,Itanagar,Coimbatore,2021-02-09,2021-02-18,firstClass,AirAsia India,2495.63,0.485417,0.600694,27601.30,0.684028,0.799306,2021-02-09 11:39:00,2021-02-18 16:25:00,2021-02-09 14:25:00,2021-02-18 19:11:00,0 days 02:46:00
18,10472,105,Coimbatore,Pune,2022-11-08,2022-11-18,firstClass,Akasa Air,899.88,0.111806,0.152778,10661.30,0.236111,0.277083,2022-11-08 02:41:00,2022-11-18 05:40:00,2022-11-08 03:40:00,2022-11-18 06:39:00,0 days 00:59:00
19,11868,116,Guwahati,Visakhapatnam,2020-01-23,2020-01-30,economic,IndiGo,1291.75,0.738889,0.798611,9357.50,0.881944,0.941667,2020-01-23 17:44:00,2020-01-30 21:10:00,2020-01-23 19:10:00,2020-01-30 22:36:00,0 days 01:26:00

In [10]:
a= pd.read_excel("Final_RoundTripp.xlsx")

In [11]:
a

,travelCode,User_ID,Departure,Arrival,Departure_Date,Return_Date,flightType,Flight_agency,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Roundtrip_Cost
0,503,4,Itanagar,Surat,2021-03-25 00:00:00,2021-04-02,firstClass,Air India,2204.62,02:26,00:56,03:22,19782.96
1,1479,13,Bengaluru,Visakhapatnam,2020-09-07 00:00:00,2020-09-15,economic,IndiGo,797.17,00:53,01:41,02:34,6441.52
2,1666,15,Chandigarh,Navi Mumbai,2019-11-28 00:00:00,2019-12-09,firstClass,Air India,1355.13,01:30,11:12,12:42,12681.04
3,2069,18,Kota,Visakhapatnam,2021-01-28 00:00:00,2021-01-31,premium,Akasa Air,3406.67,03:47,03:42,07:29,27003.82
4,2383,21,Shillong,Diu,2021-06-17 00:00:00,2021-07-01,economic,IndiGo,2201.44,02:26,16:15,18:41,15115.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,105129,1041,Thiruvananthapuram,Guwahati,2022-07-14 00:00:00,2022-07-27,premium,Air India,2512.60,02:47,18:38,21:25,24335.51
284,105134,1041,Mysuru,Chennai,2020-11-19 00:00:00,2020-11-26,economic,IndiGo,404.42,00:26,12:51,13:17,4611.36
285,130685,1286,Srinagar,Mopa,2020-07-23 00:00:00,2020-07-28,firstClass,Air India,7566.74,08:24,17:11,01:35,80917.40
286,130696,1286,Puducherry,Chennai,2021-04-15 00:00:00,2021-04-26,firstClass,GoAir,137.25,00:09,19:13,19:22,2898.40
287,130775,1286,Jamshedpur,Shimla,2020-06-25 00:00:00,2020-06-28,firstClass,Air India,1283.89,01:25,05:35,07:00,14746.40

In [47]:
df.to_excel('Sujall.xlsx', index=False)
from IPython.display import FileLink
FileLink('Sujall.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\Sujall.xlsx

In [33]:
df = df.drop(columns={'Departure_Date','Return_Date','Departure Time','Arrival Time','Return Departure Time'})
df

,travelCode,User_ID,Departure,Arrival,flightType,Flight_agency,Flight Distance (km),Roundtrip_Cost,Return Arrival Time,Modified_Departure_Date,Modified_Return_Date,arrival_date,return_arrival_date,Flight_Duration
0,503,4,Itanagar,Surat,firstClass,Air India,2204.62,19782.96,0.325000,2021-03-25 00:56:00,2021-04-02 05:22:00,2021-03-25 03:22:00,2021-04-02 07:48:00,0 days 02:26:00
1,1479,13,Bengaluru,Visakhapatnam,economic,IndiGo,797.17,6441.52,0.227083,2020-09-07 01:41:00,2020-09-15 04:34:00,2020-09-07 02:34:00,2020-09-15 05:27:00,0 days 00:53:00
2,1666,15,Chandigarh,Navi Mumbai,firstClass,Air India,1355.13,12681.04,0.675000,2019-11-28 11:12:00,2019-12-09 14:42:00,2019-11-28 12:42:00,2019-12-09 16:12:00,0 days 01:30:00
3,2069,18,Kota,Visakhapatnam,premium,Akasa Air,3406.67,27003.82,0.552778,2021-01-28 03:42:00,2021-01-31 09:29:00,2021-01-28 07:29:00,2021-01-31 13:16:00,0 days 03:47:00
4,2383,21,Shillong,Diu,economic,IndiGo,2201.44,15115.64,0.963194,2021-06-17 16:15:00,2021-07-01 20:41:00,2021-06-17 18:41:00,2021-07-01 23:07:00,0 days 02:26:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,105129,1041,Thiruvananthapuram,Guwahati,premium,Air India,2512.60,24335.51,0.091667,2022-07-14 18:38:00,2022-07-27 23:25:00,2022-07-14 21:25:00,2022-07-28 02:12:00,0 days 02:47:00
284,105134,1041,Mysuru,Chennai,economic,IndiGo,404.42,4611.36,0.654861,2020-11-19 12:51:00,2020-11-26 15:17:00,2020-11-19 13:17:00,2020-11-26 15:43:00,0 days 00:26:00
285,130685,1286,Srinagar,Mopa,firstClass,Air India,7566.74,80917.40,0.499306,2020-07-23 17:11:00,2020-07-28 03:35:00,2020-07-24 01:35:00,2020-07-28 11:59:00,0 days 08:24:00
286,130696,1286,Puducherry,Chennai,firstClass,GoAir,137.25,2898.40,0.896528,2021-04-15 19:13:00,2021-04-26 21:22:00,2021-04-15 19:22:00,2021-04-26 21:31:00,0 days 00:09:00
287,130775,1286,Jamshedpur,Shimla,firstClass,Air India,1283.89,14746.40,0.434028,2020-06-25 05:35:00,2020-06-28 09:00:00,2020-06-25 07:00:00,2020-06-28 10:25:00,0 days 01:25:00

In [39]:
df =df.rename(columns={'Modified_Departure_Date':'Departure_Date','Modified_Return_Date':'ReturnDeparture_Date','arrival_date':'Arrival_Date','return_arrival_date':'ReturnArrival_Date'})

In [40]:
df

,travelCode,User_ID,Departure,Arrival,flightType,Flight_agency,Flight Distance (km),Roundtrip_Cost,Return Arrival Time,Departure_Date,ReturnDeparture_Date,Arrival_Date,ReturnArrival_Date,Flight_Duration
0,503,4,Itanagar,Surat,firstClass,Air India,2204.62,19782.96,0.325000,2021-03-25 00:56:00,2021-04-02 05:22:00,2021-03-25 03:22:00,2021-04-02 07:48:00,0 days 02:26:00
1,1479,13,Bengaluru,Visakhapatnam,economic,IndiGo,797.17,6441.52,0.227083,2020-09-07 01:41:00,2020-09-15 04:34:00,2020-09-07 02:34:00,2020-09-15 05:27:00,0 days 00:53:00
2,1666,15,Chandigarh,Navi Mumbai,firstClass,Air India,1355.13,12681.04,0.675000,2019-11-28 11:12:00,2019-12-09 14:42:00,2019-11-28 12:42:00,2019-12-09 16:12:00,0 days 01:30:00
3,2069,18,Kota,Visakhapatnam,premium,Akasa Air,3406.67,27003.82,0.552778,2021-01-28 03:42:00,2021-01-31 09:29:00,2021-01-28 07:29:00,2021-01-31 13:16:00,0 days 03:47:00
4,2383,21,Shillong,Diu,economic,IndiGo,2201.44,15115.64,0.963194,2021-06-17 16:15:00,2021-07-01 20:41:00,2021-06-17 18:41:00,2021-07-01 23:07:00,0 days 02:26:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,105129,1041,Thiruvananthapuram,Guwahati,premium,Air India,2512.60,24335.51,0.091667,2022-07-14 18:38:00,2022-07-27 23:25:00,2022-07-14 21:25:00,2022-07-28 02:12:00,0 days 02:47:00
284,105134,1041,Mysuru,Chennai,economic,IndiGo,404.42,4611.36,0.654861,2020-11-19 12:51:00,2020-11-26 15:17:00,2020-11-19 13:17:00,2020-11-26 15:43:00,0 days 00:26:00
285,130685,1286,Srinagar,Mopa,firstClass,Air India,7566.74,80917.40,0.499306,2020-07-23 17:11:00,2020-07-28 03:35:00,2020-07-24 01:35:00,2020-07-28 11:59:00,0 days 08:24:00
286,130696,1286,Puducherry,Chennai,firstClass,GoAir,137.25,2898.40,0.896528,2021-04-15 19:13:00,2021-04-26 21:22:00,2021-04-15 19:22:00,2021-04-26 21:31:00,0 days 00:09:00
287,130775,1286,Jamshedpur,Shimla,firstClass,Air India,1283.89,14746.40,0.434028,2020-06-25 05:35:00,2020-06-28 09:00:00,2020-06-25 07:00:00,2020-06-28 10:25:00,0 days 01:25:00

In [41]:
df = df.drop(columns={'Return Arrival Time'})

In [42]:
reorder = ['travelCode','User_ID','Departure','Arrival','Departure_Date','Arrival_Date','ReturnDeparture_Date','ReturnArrival_Date','flightType','Flight_agency','Flight Distance (km)','Flight_Duration','Roundtrip_Cost']

In [43]:
df = df[reorder]

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 288 entries, 0 to 287
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   travelCode            288 non-null    int64
 1   User_ID               288 non-null    int64
 2   Departure             288 non-null    object
 3   Arrival               288 non-null    object
 4   Departure_Date        288 non-null    datetime64[ns]
 5   Arrival_Date          288 non-null    datetime64[ns]
 6   ReturnDeparture_Date  288 non-null    datetime64[ns]
 7   ReturnArrival_Date    288 non-null    datetime64[ns]
 8   flightType            288 non-null    object
 9   Flight_agency         288 non-null    object
 10  Flight Distance (km)  288 non-null    float64
 11  Flight_Duration       288 non-null    timedelta64[ns]
 12  Roundtrip_Cost        288 non-null    float64
dtypes: datetime64[ns](4), float64(2), int64(2), object(4), timedelta64[ns](1)
memory usage: 31.5+ KB

In [ ]:
df