In [1]:
import pandas as pd

In [2]:
airport_df = pd.read_excel("AirportCoordinates.xlsx")
flight_df = pd.read_excel("FlightWithAirport.xlsx")

In [3]:
airport_df

,LocationID,Name,Address,City,Latitude,Longitude
0,1,Coimbatore International Airport (CJB),"Coimbatore International Airport, Avinashi Roa...",Coimbatore,11.030030,77.043380
1,2,Birsa Munda Airport (IXR),"Birsa Munda Airport, Hinoo, Ranchi, Jharkhand ...",Ranchi,23.314250,85.321670
2,3,Goa International Airport (GOI),"Goa International Airport, Airport Road, Dabol...",Dabolim,15.380830,73.831420
3,4,Sardar Vallabhbhai Patel International Airport...,Sardar Vallabhbhai Patel International Airport...,Ahmedabad,23.077240,72.634650
4,5,Rajiv Gandhi International Airport (HYD),"Rajiv Gandhi International Airport, Shamshabad...",Hyderabad,17.231320,78.429860
5,6,Agartala Airport (IXA),"Agartala Airport, Agartala, Tripura 799009",Khowai,23.886980,91.240450
6,7,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Navi Mumbai,19.088690,72.867920
7,8,Pune International Airport (PNQ),"Pune International Airport, Lohegaon, Pune, Ma...",Pune,18.340000,73.550000
8,9,Vijayawada Airport (VGA),"Vijayawada Airport, Gannavaram, Andhra Pradesh...",Vijayawada,16.530430,80.796850
9,10,Gwalior Airport (GWL),"Gwalior Airport, Maharajpur, Gwalior, Madhya P...",Gwalior,26.293340,78.227750
10,11,Kempegowda International Airport (BLR),"Kempegowda International Airport, Devanahalli,...",Bengaluru,13.200710,77.708790
11,12,Lokpriya Gopinath Bordoloi International Airpo...,Lokpriya Gopinath Bordoloi International Airpo...,Guwahati,26.106090,91.585940
12,13,Bilaspur Airport (PAB),"Bilaspur Airport, Chakarbhata, Bilaspur, Chhat...",Bilaspur,21.988400,82.110980
13,14,Swami Vivekananda Airport (RPR),"Swami Vivekananda Airport, Ramchandi, Naya Rai...",Raipur,21.180400,81.738800
14,15,Puducherry Airport (PNY),"Puducherry Airport, Lawspet, Puducherry 605008",Puducherry,11.580000,79.480000
15,16,Sonari Airport (IXW),"Sonari Airport, Sonari, Jamshedpur, Jharkhand ...",Jamshedpur,22.480000,86.100000
16,17,Nashik International Airport (ISK),"Nashik International Airport, Ozar, Nashik, Ma...",Nashik,20.119444,73.913611
17,18,Mopa International Airport (GOX),"Mopa International Airport, Mopa, Pernem, Goa ...",Mopa,15.731300,73.868170
18,19,Prayagraj Airport (IXD),"Prayagraj Airport, Bamrauli, Prayagraj, Uttar ...",Prayagraj,25.440060,81.733870
19,20,Vadodara Airport (BDQ),"Vadodara Airport, Harni Road, Vadodara, Gujara...",Vadodara,22.336200,73.226300
20,21,Ludhiana Airport (LUH),"Ludhiana Airport, Sahnewal, Ludhiana, Punjab 1...",Ludhiana,30.854700,75.952600
21,22,Raigarh Airport (None),"Raigarh Airport, Kondatarai, Raigarh, Chhattis...",Raigarh,21.823889,83.360278
22,23,Chennai International Airport (MAA),"Chennai International Airport, GST Road, Meena...",Chennai,12.988330,80.165780
23,24,Biju Patnaik International Airport (BAI),"Biju Patnaik International Airport, Airport Ro...",Puri,20.244360,85.817780
24,25,Tirupati Airport (TIR),"Tirupati Airport, Renigunta, Andhra Pradesh 51...",Tirupati,13.632500,79.543300
25,26,Dehradun Airport (DED),"Dehradun Airport, Jolly Grant, Dehradun, Uttar...",Dehradun,30.189700,78.180300
26,27,Sheikh ul-Alam International Airport (SXR),"Sheikh ul-Alam International Airport, Aerodrom...",Srinagar,33.987100,74.774200
27,28,Indira Gandhi International Airport (DEL),"Indira Gandhi International Airport, New Delhi...",Delhi NCR,28.566500,77.103090
28,29,Donyi Polo Airport (HGI),"Donyi Polo Airport, Hollongi, Itanagar, Arunac...",Itanagar,26.970000,93.664722
29,30,Lal Bahadur Shastri International Airport (VNS),"Lal Bahadur Shastri International Airport, Bab...",Varanasi,25.452222,82.859444
30,31,Rupsi Airport (RUP),"Rupsi Airport, Rupsi, Assam 783372",Dhubri,26.141180,89.906870
31,32,Netaji Subhas Chandra Bose International Airpo...,Netaji Subhas Chandra Bose International Airpo...,Kolkata,22.654740,88.446720
32,33,Pakyong Airport (PYG),"Pakyong Airport, Pakyong, Sikkim 737106",Gangtok,27.227560,88.585960
33,34,Shillong Airport (SHL),"Shillong Airport, Umroi, Meghalaya 793103",Shillong,25.703600,91.978700
34,35,Sri Guru Ram Dass Jee International Airport (ATQ),"Sri Guru Ram Dass Jee International Airport, A...",Amritsar,31.709590,74.797260
35,36,Raja Bhoj Airport (BHO),"Raja Bhoj Airport, Gandhi Nagar, Bhopal, Madhy...",Bhopal,23.287470,77.337370
36,37,Jaipur International Airport (JAI),"Jaipur International Airport, Airport Road, Sa...",Jaipur,26.824190,75.812160
37,38,Kullu–Manali Airport (KUU),"Kullu–Manali Airport, Bhuntar, Kullu, Himachal...",Kullu-Manali,31.876667,77.154444
38,39,Ayodhya Airport (under construction),"Ayodhya Airport, Ayodhya, Uttar Pradesh 224123",Ayodhya,26.748034,82.150781
39,40,Biju Patnaik International Airport (BBI),"Biju Patnaik International Airport, Airport Ro...",Bhubaneswar,20.244360,85.817780
40,41,Trivandrum International Airport (TRV),"Trivandrum International Airport, Vallakkadavu...",Thiruvananthapuram,8.482120,76.920110
41,42,Kota Airport (KTU),"Kota Airport, Aerodrome Circle, Kota, Rajastha...",Kota,25.160220,75.845630
42,43,Surat Airport (STV),"Surat Airport, Dumas Road, Surat, Gujarat 395007",Surat,21.114100,72.741800
43,44,Maharana Pratap Airport (UDR),"Maharana Pratap Airport, NH 76, Dabok, Udaipur...",Udaipur,24.617840,73.896620
44,45,Diu Airport (DIU),"Diu Airport, Diu, Daman and Diu 362520",Diu,20.713100,70.921100
45,46,Chandigarh International Airport (IXC),"Chandigarh International Airport, Mohali, Punj...",Chandigarh,30.673500,76.788500
46,47,Shimla Airport (SLV),"Shimla Airport, Jubbarhatti, Shimla, Himachal ...",Shimla,31.081800,77.068000
47,48,Imphal International Airport (IMF),"Imphal International Airport, Imphal, Manipur ...",Imphal,24.759950,93.896700
48,49,Hisar Airport (HSS),"Hisar Airport, Hisar, Haryana 125001",Hisar,29.179440,75.755340
49,50,Visakhapatnam Airport (VTZ),"Visakhapatnam Airport, NAD Junction, Visakhapa...",Visakhapatnam,17.721200,83.224500
50,51,Devi Ahilya Bai Holkar Airport (IDR),"Devi Ahilya Bai Holkar Airport, Indore, Madhya...",Indore,22.721667,75.800833
51,52,Mysore Airport (MYQ),"Mysore Airport, Mandakalli, Mysuru, Karnataka ...",Mysuru,12.307200,76.649700
52,53,Jay Prakash Narayan Airport (PAT),"Jay Prakash Narayan Airport, Sheikhpura, Patna...",Patna,25.591389,85.089167
53,54,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Mumbai,19.088690,72.867920

In [4]:
airport_df['Name'].value_counts()

Name
Coimbatore International Airport (CJB)                      1
Trivandrum International Airport (TRV)                      1
Lal Bahadur Shastri International Airport (VNS)             1
Rupsi Airport (RUP)                                         1
Netaji Subhas Chandra Bose International Airport (CCU)      1
Pakyong Airport (PYG)                                       1
Shillong Airport (SHL)                                      1
Sri Guru Ram Dass Jee International Airport (ATQ)           1
Raja Bhoj Airport (BHO)                                     1
Jaipur International Airport (JAI)                          1
Kullu–Manali Airport (KUU)                                  1
Ayodhya Airport (under construction)                        1
Biju Patnaik International Airport (BBI)                    1
Kota Airport (KTU)                                          1
Birsa Munda Airport (IXR)                                   1
Surat Airport (STV)                                         1
Maharana Pratap Airport (UDR)                               1
Diu Airport (DIU)                                           1
Chandigarh International Airport (IXC)                      1
Shimla Airport (SLV)                                        1
Imphal International Airport (IMF)                          1
Hisar Airport (HSS)                                         1
Visakhapatnam Airport (VTZ)                                 1
Devi Ahilya Bai Holkar Airport (IDR)                        1
Mysore Airport (MYQ)                                        1
Jay Prakash Narayan Airport (PAT)                           1
Donyi Polo Airport (HGI)                                    1
Indira Gandhi International Airport (DEL)                   1
Sheikh ul-Alam International Airport (SXR)                  1
Dehradun Airport (DED)                                      1
Goa International Airport (GOI)                             1
Sardar Vallabhbhai Patel International Airport (AMD)        1
Rajiv Gandhi International Airport (HYD)                    1
Agartala Airport (IXA)                                      1
Chhatrapati Shivaji Maharaj International Airport (BOmm)    1
Pune International Airport (PNQ)                            1
Vijayawada Airport (VGA)                                    1
Gwalior Airport (GWL)                                       1
Kempegowda International Airport (BLR)                      1
Lokpriya Gopinath Bordoloi International Airport (GAU)      1
Bilaspur Airport (PAB)                                      1
Swami Vivekananda Airport (RPR)                             1
Puducherry Airport (PNY)                                    1
Sonari Airport (IXW)                                        1
Nashik International Airport (ISK)                          1
Mopa International Airport (GOX)                            1
Prayagraj Airport (IXD)                                     1
Vadodara Airport (BDQ)                                      1
Ludhiana Airport (LUH)                                      1
Raigarh Airport (None)                                      1
Chennai International Airport (MAA)                         1
Biju Patnaik International Airport (BAI)                    1
Tirupati Airport (TIR)                                      1
Chhatrapati Shivaji Maharaj International Airport (BOM)     1
Name: count, dtype: int64

In [5]:
airport_df['City'].value_counts()

City
Coimbatore            1
Thiruvananthapuram    1
Varanasi              1
Dhubri                1
Kolkata               1
Gangtok               1
Shillong              1
Amritsar              1
Bhopal                1
Jaipur                1
Kullu-Manali          1
Ayodhya               1
Bhubaneswar           1
Kota                  1
Ranchi                1
Surat                 1
Udaipur               1
Diu                   1
Chandigarh            1
Shimla                1
Imphal                1
Hisar                 1
Visakhapatnam         1
Indore                1
Mysuru                1
Patna                 1
Itanagar              1
Delhi NCR             1
Srinagar              1
Dehradun              1
Dabolim               1
Ahmedabad             1
Hyderabad             1
Khowai                1
Navi Mumbai           1
Pune                  1
Vijayawada            1
Gwalior               1
Bengaluru             1
Guwahati              1
Bilaspur              1
Raipur                1
Puducherry            1
Jamshedpur            1
Nashik                1
Mopa                  1
Prayagraj             1
Vadodara              1
Ludhiana              1
Raigarh               1
Chennai               1
Puri                  1
Tirupati              1
Mumbai                1
Name: count, dtype: int64

In [6]:
flight_df = flight_df.merge(airport_df, left_on="Departure", right_on="Name", how="left")
flight_df = flight_df.rename(columns={"Latitude": "Dep_Lat", "Longitude": "Dep_Lon"})

flight_df = flight_df.merge(airport_df, left_on="Arrival", right_on="Name", how="left")
flight_df = flight_df.rename(columns={"Latitude": "Arr_Lat", "Longitude": "Arr_Lon"})

In [7]:
flight_df

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Departure Time,Arrival Time,flight_number,...,Address_x,City_x,Dep_Lat,Dep_Lon,LocationID_y,Name_y,Address_y,City_y,Arr_Lat,Arr_Lon
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),03:59,05:05,G84279,...,"Coimbatore International Airport, Avinashi Roa...",Coimbatore,11.030030,77.043380,50,Visakhapatnam Airport (VTZ),"Visakhapatnam Airport, NAD Junction, Visakhapa...",Visakhapatnam,17.721200,83.224500
1,2,0,firstClass,IndiGo,10/10/2019,Birsa Munda Airport (IXR),Shillong Airport (SHL),01:02,01:49,6E4357O,...,"Birsa Munda Airport, Hinoo, Ranchi, Jharkhand ...",Ranchi,23.314250,85.321670,34,Shillong Airport (SHL),"Shillong Airport, Umroi, Meghalaya 793103",Shillong,25.703600,91.978700
2,7,0,economic,Air India,14/11/2019,Goa International Airport (GOI),Birsa Munda Airport (IXR),00:15,01:54,AI3905,...,"Goa International Airport, Airport Road, Dabol...",Dabolim,15.380830,73.831420,2,Birsa Munda Airport (IXR),"Birsa Munda Airport, Hinoo, Ranchi, Jharkhand ...",Ranchi,23.314250,85.321670
3,11,0,premium,SpiceJet,12/12/2019,Sardar Vallabhbhai Patel International Airport...,Raigarh Airport (None),17:35,18:49,SG2659K,...,Sardar Vallabhbhai Patel International Airport...,Ahmedabad,23.077240,72.634650,22,Raigarh Airport (None),"Raigarh Airport, Kondatarai, Raigarh, Chhattis...",Raigarh,21.823889,83.360278
4,13,0,firstClass,GoAir,26/12/2019,Rajiv Gandhi International Airport (HYD),Netaji Subhas Chandra Bose International Airpo...,18:18,19:36,G83184,...,"Rajiv Gandhi International Airport, Shamshabad...",Hyderabad,17.231320,78.429860,32,Netaji Subhas Chandra Bose International Airpo...,Netaji Subhas Chandra Bose International Airpo...,Kolkata,22.654740,88.446720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,premium,Air India,18/06/2020,Devi Ahilya Bai Holkar Airport (IDR),Goa International Airport (GOI),04:28,05:24,AI5405C,...,"Devi Ahilya Bai Holkar Airport, Indore, Madhya...",Indore,22.721667,75.800833,3,Goa International Airport (GOI),"Goa International Airport, Airport Road, Dabol...",Dabolim,15.380830,73.831420
39975,135939,1339,premium,Akasa Air,25/06/2020,Sardar Vallabhbhai Patel International Airport...,Shillong Airport (SHL),13:37,15:48,QP2071,...,Sardar Vallabhbhai Patel International Airport...,Ahmedabad,23.077240,72.634650,34,Shillong Airport (SHL),"Shillong Airport, Umroi, Meghalaya 793103",Shillong,25.703600,91.978700
39976,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj Airport (IXD),Visakhapatnam Airport (VTZ),17:27,18:25,QP589J,...,"Prayagraj Airport, Bamrauli, Prayagraj, Uttar ...",Prayagraj,25.440060,81.733870,50,Visakhapatnam Airport (VTZ),"Visakhapatnam Airport, NAD Junction, Visakhapa...",Visakhapatnam,17.721200,83.224500
39977,135941,1339,firstClass,IndiGo,07/09/2020,Surat Airport (STV),Goa International Airport (GOI),00:46,01:29,6E4801N,...,"Surat Airport, Dumas Road, Surat, Gujarat 395007",Surat,21.114100,72.741800,3,Goa International Airport (GOI),"Goa International Airport, Airport Road, Dabol...",Dabolim,15.380830,73.831420
39978,135942,1339,economic,IndiGo,16/07/2020,Raja Bhoj Airport (BHO),Prayagraj Airport (IXD),12:14,12:48,6E4290X,...,"Raja Bhoj Airport, Gandhi Nagar, Bhopal, Madhy...",Bhopal,23.287470,77.337370,19,Prayagraj Airport (IXD),"Prayagraj Airport, Bamrauli, Prayagraj, Uttar ...",Prayagraj,25.440060,81.733870

In [8]:
flight_df = flight_df.drop(columns=['Arrival Time','LocationID_x','Name_x','Address_x','City_x','LocationID_y','Name_y','Address_y','City_y'])

In [9]:
from math import radians, sin, cos, sqrt, atan2

def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Radius of the Earth in km
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * atan2(sqrt(a), sqrt(1-a))
    return R * c

flight_df["Distance_km"] = flight_df.apply(lambda row: haversine(row["Dep_Lat"], row["Dep_Lon"], row["Arr_Lat"], row["Arr_Lon"]), axis=1)

In [10]:
flight_speeds = {
    "Akasa Air": 820,
    "Air India": 840,
    "IndiGo": 830,
    "SpiceJet": 820,
    "AirAsia India": 810,
    "GoAir": 815
}

In [11]:
flight_df["Speed_kmh"] = flight_df["Flight_agency"].map(flight_speeds)
flight_df["EstimatedDuration_hr"] = flight_df["Distance_km"] / flight_df["Speed_kmh"]

def convert_to_hhmm(duration_hr):
    hours = int(duration_hr)
    minutes = int((duration_hr - hours) * 60)
    return f"{hours:02d}:{minutes:02d}"

flight_df["EstimatedDuration_HHMM"] = flight_df["EstimatedDuration_hr"].apply(convert_to_hhmm)

In [12]:
flight_df = flight_df.drop(columns={'EstimatedDuration_hr'})

In [13]:
flight_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39979 entries, 0 to 39978
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   travelCode               39979 non-null  int64
 1   User_ID                  39979 non-null  int64
 2   flightType               39979 non-null  object
 3   Flight_agency            39979 non-null  object
 4   Departure_date           39979 non-null  object
 5   Departure                39979 non-null  object
 6   Arrival                  39979 non-null  object
 7   Departure Time           39979 non-null  object
 8   flight_number            39979 non-null  object
 9   Calculated_Flight_Price  39979 non-null  float64
 10  Dep_Lat                  39979 non-null  float64
 11  Dep_Lon                  39979 non-null  float64
 12  Arr_Lat                  39979 non-null  float64
 13  Arr_Lon                  39979 non-null  float64
 14  Distance_km              39979 non-null  float64
 15  Speed_kmh                39979 non-null  int64
 16  EstimatedDuration_HHMM   39979 non-null  object
dtypes: float64(6), int64(3), object(8)
memory usage: 5.2+ MB

In [14]:
flight_df.to_excel('fl.xlsx', index=False)
from IPython.display import FileLink
FileLink('fl.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\fl.xlsx

In [15]:
flight_df["Departure_date"] = pd.to_datetime(flight_df["Departure_date"])
flight_df["Departure Time"] = flight_df["Departure Time"].astype(str).str.zfill(5) + ":00"
flight_df["Departure Time"] = pd.to_timedelta(flight_df["Departure Time"])

# Ensure "EstimatedDuration_HHMM" is in hh:mm:ss format
flight_df["EstimatedDuration_HHMM"] = flight_df["EstimatedDuration_HHMM"].astype(str).str.zfill(5) + ":00"
flight_df["EstimatedDuration_HHMM"] = pd.to_timedelta(flight_df["EstimatedDuration_HHMM"])
flight_df["Arrival_Date"] = flight_df["Departure_date"] + flight_df["Departure Time"] + flight_df["EstimatedDuration_HHMM"]
flight_df["Departure_date"] = flight_df["Departure_date"] + flight_df["Departure Time"]

C:\Users\SURAJ\AppData\Local\Temp\ipykernel_4352\2100894459.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  flight_df["Departure_date"] = pd.to_datetime(flight_df["Departure_date"])

In [18]:
flight_df.head(20)

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Departure Time,flight_number,Calculated_Flight_Price,Dep_Lat,Dep_Lon,Arr_Lat,Arr_Lon,Distance_km,Speed_kmh,EstimatedDuration_HHMM,Arrival_Date
0,0,0,firstClass,GoAir,2019-09-26 03:59:00,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),0 days 03:59:00,G84279,4810.84,11.03003,77.04338,17.721200,83.224500,998.106548,815,0 days 01:13:00,2019-09-26 05:12:00
1,2,0,firstClass,IndiGo,2019-10-10 01:02:00,Birsa Munda Airport (IXR),Shillong Airport (SHL),0 days 01:02:00,6E4357O,3580.20,23.31425,85.32167,25.703600,91.978700,723.904020,830,0 days 00:52:00,2019-10-10 01:54:00
2,7,0,economic,Air India,2019-11-14 00:15:00,Goa International Airport (GOI),Birsa Munda Airport (IXR),0 days 00:15:00,AI3905,3785.16,15.38083,73.83142,23.314250,85.321670,1492.553600,840,0 days 01:46:00,2019-11-14 02:01:00
3,11,0,premium,SpiceJet,2019-12-12 17:35:00,Sardar Vallabhbhai Patel International Airport...,Raigarh Airport (None),0 days 17:35:00,SG2659K,3669.93,23.07724,72.63465,21.823889,83.360278,1110.753989,820,0 days 01:21:00,2019-12-12 18:56:00
4,13,0,firstClass,GoAir,2019-12-26 18:18:00,Rajiv Gandhi International Airport (HYD),Netaji Subhas Chandra Bose International Airpo...,0 days 18:18:00,G83184,5780.44,17.23132,78.42986,22.654740,88.446720,1207.676138,815,0 days 01:28:00,2019-12-26 19:46:00
5,15,0,premium,IndiGo,2020-09-01 09:08:00,Agartala Airport (IXA),Sri Guru Ram Dass Jee International Airport (ATQ),0 days 09:08:00,6E168,5832.53,23.88698,91.24045,31.709590,74.797260,1833.350410,830,0 days 02:12:00,2020-09-01 11:20:00
6,22,0,firstClass,SpiceJet,2020-02-27 18:34:00,Chhatrapati Shivaji Maharaj International Airp...,Pune International Airport (PNQ),0 days 18:34:00,SG2054R,1262.80,19.08869,72.86792,18.340000,73.550000,109.957560,820,0 days 00:08:00,2020-02-27 18:42:00
7,29,0,economic,Air India,2020-04-16 21:53:00,Pune International Airport (PNQ),Chhatrapati Shivaji Maharaj International Airp...,0 days 21:53:00,AI3866C,1099.40,18.34000,73.55000,19.088690,72.867920,109.957560,840,0 days 00:07:00,2020-04-16 22:00:00
8,32,0,firstClass,Air India,2020-07-05 16:05:00,Agartala Airport (IXA),Chhatrapati Shivaji Maharaj International Airp...,0 days 16:05:00,AI4803,9099.52,23.88698,91.24045,19.088690,72.867920,1972.548579,840,0 days 02:20:00,2020-07-05 18:25:00
9,33,0,premium,IndiGo,2020-05-14 16:44:00,Chhatrapati Shivaji Maharaj International Airp...,Swami Vivekananda Airport (RPR),0 days 16:44:00,6E4017,3144.23,19.08869,72.86792,21.180400,81.738800,954.698329,830,0 days 01:09:00,2020-05-14 17:53:00
10,34,0,premium,IndiGo,2020-05-21 08:45:00,Vijayawada Airport (VGA),Raigarh Airport (None),0 days 08:45:00,6E1197,2615.42,16.53043,80.79685,21.823889,83.360278,647.198554,830,0 days 00:46:00,2020-05-21 09:31:00
11,38,0,firstClass,AirAsia India,2020-06-18 17:59:00,Sardar Vallabhbhai Patel International Airport...,Sheikh ul-Alam International Airport (SXR),0 days 17:59:00,I53903,5843.52,23.07724,72.63465,33.987100,74.774200,1230.893406,810,0 days 01:31:00,2020-06-18 19:30:00
12,39,0,economic,IndiGo,2020-06-25 14:19:00,Gwalior Airport (GWL),Indira Gandhi International Airport (DEL),0 days 14:19:00,6E1740,1210.72,26.29334,78.22775,28.566500,77.103090,276.055968,830,0 days 00:19:00,2020-06-25 14:38:00
13,42,0,premium,SpiceJet,2020-07-16 01:39:00,Kempegowda International Airport (BLR),Swami Vivekananda Airport (RPR),0 days 01:39:00,SG1278,3386.50,13.20071,77.70879,21.180400,81.738800,984.978613,820,0 days 01:12:00,2020-07-16 02:51:00
14,43,0,firstClass,Air India,2020-07-23 23:16:00,Rajiv Gandhi International Airport (HYD),Ludhiana Airport (LUH),0 days 23:16:00,AI1098S,7061.32,17.23132,78.42986,30.854700,75.952600,1535.440070,840,0 days 01:49:00,2020-07-24 01:05:00
15,45,0,premium,Air India,2020-06-08 04:49:00,Lokpriya Gopinath Bordoloi International Airpo...,Raigarh Airport (None),0 days 04:49:00,AI3775,3302.73,26.10609,91.58594,21.823889,83.360278,961.549764,840,0 days 01:08:00,2020-06-08 05:57:00
16,51,0,premium,IndiGo,2020-09-17 02:33:00,Rajiv Gandhi International Airport (HYD),Swami Vivekananda Airport (RPR),0 days 02:33:00,6E5786,2080.67,17.23132,78.42986,21.180400,81.738800,559.895707,830,0 days 00:40:00,2020-09-17 03:13:00
17,53,0,premium,IndiGo,2020-01-10 09:16:00,Bilaspur Airport (PAB),Devi Ahilya Bai Holkar Airport (IDR),0 days 09:16:00,6E5849,2583.63,21.98840,82.11098,22.721667,75.800833,653.971788,830,0 days 00:47:00,2020-01-10 10:03:00
18,54,0,firstClass,Air India,2020-08-10 17:23:00,Swami Vivekananda Airport (RPR),Shillong Airport (SHL),0 days 17:23:00,AI1767,5482.72,21.18040,81.73880,25.703600,91.978700,1158.837295,840,0 days 01:22:00,2020-08-10 18:45:00
19,55,0,firstClass,Akasa Air,2020-10-15 12:32:00,Puducherry Airport (PNY),Agartala Airport (IXA),0 days 12:32:00,QP5828W,8299.12,11.58000,79.48000,23.886980,91.240450,1848.196905,820,0 days 02:15:00,2020-10-15 14:47:00

In [17]:
flight_df.to_excel('LastFLight.xlsx', index=False)
from IPython.display import FileLink
FileLink('LastFLight.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\LastFLight.xlsx

In [56]:
x = pd.read_excel("LastFLight.xlsx")

# def convert_to_hhmm(duration_hr):
#     hours = int(duration_hr)
#     minutes = int((duration_hr - hours) * 60)
#     return f"{hours:02d}:{minutes:02d}"
# # x["Departure Time"] = pd.to_timedelta(x["Departure Time"])
# x["EstimatedDuration_HHMM"] = x["EstimatedDuration_HHMM"].apply(convert_to_hhmm)

In [57]:
def extract_time(df, datetime_col, new_col="Time_HHMM"):
    """
    Extracts time in HHMM format from a datetime column.
    
    Args:
    df (pd.DataFrame): Input DataFrame
    datetime_col (str): Column name containing datetime values
    new_col (str): Name of the new column to store extracted time

    Returns:
    pd.DataFrame: DataFrame with new time column in HHMM format
    """
    df[new_col] = pd.to_datetime(df[datetime_col]).dt.strftime('%H%M')
    return df

x = extract_time(x, "Departure_date", "Departure_time")

In [58]:
# x= x.drop(columns="Time_HHMM")
x = extract_time(x, "Arrival_Date", "Arrival_time")

In [59]:
x

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Departure Time,flight_number,Calculated_Flight_Price,Dep_Lat,Dep_Lon,Arr_Lat,Arr_Lon,Distance_km,Speed_kmh,EstimatedDuration_HHMM,Arrival_Date,Departure_time,Arrival_time
0,0,0,firstClass,GoAir,2019-09-26 03:59:00,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),0.165972,G84279,4810.84,11.030030,77.043380,17.721200,83.224500,998.106548,815,01:13,2019-09-26 05:12:00,0359,0512
1,2,0,firstClass,IndiGo,2019-10-10 01:02:00,Birsa Munda Airport (IXR),Shillong Airport (SHL),0.043056,6E4357O,3580.20,23.314250,85.321670,25.703600,91.978700,723.904020,830,00:52,2019-10-10 01:54:00,0102,0154
2,7,0,economic,Air India,2019-11-14 00:15:00,Goa International Airport (GOI),Birsa Munda Airport (IXR),0.010417,AI3905,3785.16,15.380830,73.831420,23.314250,85.321670,1492.553600,840,01:46,2019-11-14 02:01:00,0015,0201
3,11,0,premium,SpiceJet,2019-12-12 17:35:00,Sardar Vallabhbhai Patel International Airport...,Raigarh Airport (None),0.732639,SG2659K,3669.93,23.077240,72.634650,21.823889,83.360278,1110.753989,820,01:21,2019-12-12 18:56:00,1735,1856
4,13,0,firstClass,GoAir,2019-12-26 18:18:00,Rajiv Gandhi International Airport (HYD),Netaji Subhas Chandra Bose International Airpo...,0.762500,G83184,5780.44,17.231320,78.429860,22.654740,88.446720,1207.676138,815,01:28,2019-12-26 19:46:00,1818,1946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,premium,Air India,2020-06-18 04:28:00,Devi Ahilya Bai Holkar Airport (IDR),Goa International Airport (GOI),0.186111,AI5405C,2949.67,22.721667,75.800833,15.380830,73.831420,842.052913,840,01:00,2020-06-18 05:28:00,0428,0528
39975,135939,1339,premium,Akasa Air,2020-06-25 13:37:00,Sardar Vallabhbhai Patel International Airport...,Shillong Airport (SHL),0.567361,QP2071,5988.03,23.077240,72.634650,25.703600,91.978700,1978.782106,820,02:24,2020-06-25 16:01:00,1337,1601
39976,135940,1339,firstClass,Akasa Air,2020-02-07 17:27:00,Prayagraj Airport (IXD),Visakhapatnam Airport (VTZ),0.727083,QP589J,4272.88,25.440060,81.733870,17.721200,83.224500,871.997188,820,01:03,2020-02-07 18:30:00,1727,1830
39977,135941,1339,firstClass,IndiGo,2020-09-07 00:46:00,Surat Airport (STV),Goa International Airport (GOI),0.031944,6E4801N,3349.72,21.114100,72.741800,15.380830,73.831420,647.800512,830,00:46,2020-09-07 01:32:00,0046,0132
39978,135942,1339,economic,IndiGo,2020-07-16 12:14:00,Raja Bhoj Airport (BHO),Prayagraj Airport (IXD),0.509722,6E4290X,1673.92,23.287470,77.337370,25.440060,81.733870,505.527757,830,00:36,2020-07-16 12:50:00,1214,1250

In [60]:
x["EstimatedDuration_hr"] = flight_df["Distance_km"] / flight_df["Speed_kmh"]

def convert_to_hhmm(duration_hr):
    hours = int(duration_hr)
    minutes = int((duration_hr - hours) * 60)
    return f"{hours:02d}{minutes:02d}"

x["EstimatedDuration_HHMM"] = x["EstimatedDuration_hr"].apply(convert_to_hhmm)

In [61]:
x=x.drop(columns={"EstimatedDuration_hr"})
x

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Departure Time,flight_number,Calculated_Flight_Price,Dep_Lat,Dep_Lon,Arr_Lat,Arr_Lon,Distance_km,Speed_kmh,EstimatedDuration_HHMM,Arrival_Date,Departure_time,Arrival_time
0,0,0,firstClass,GoAir,2019-09-26 03:59:00,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),0.165972,G84279,4810.84,11.030030,77.043380,17.721200,83.224500,998.106548,815,0113,2019-09-26 05:12:00,0359,0512
1,2,0,firstClass,IndiGo,2019-10-10 01:02:00,Birsa Munda Airport (IXR),Shillong Airport (SHL),0.043056,6E4357O,3580.20,23.314250,85.321670,25.703600,91.978700,723.904020,830,0052,2019-10-10 01:54:00,0102,0154
2,7,0,economic,Air India,2019-11-14 00:15:00,Goa International Airport (GOI),Birsa Munda Airport (IXR),0.010417,AI3905,3785.16,15.380830,73.831420,23.314250,85.321670,1492.553600,840,0146,2019-11-14 02:01:00,0015,0201
3,11,0,premium,SpiceJet,2019-12-12 17:35:00,Sardar Vallabhbhai Patel International Airport...,Raigarh Airport (None),0.732639,SG2659K,3669.93,23.077240,72.634650,21.823889,83.360278,1110.753989,820,0121,2019-12-12 18:56:00,1735,1856
4,13,0,firstClass,GoAir,2019-12-26 18:18:00,Rajiv Gandhi International Airport (HYD),Netaji Subhas Chandra Bose International Airpo...,0.762500,G83184,5780.44,17.231320,78.429860,22.654740,88.446720,1207.676138,815,0128,2019-12-26 19:46:00,1818,1946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,premium,Air India,2020-06-18 04:28:00,Devi Ahilya Bai Holkar Airport (IDR),Goa International Airport (GOI),0.186111,AI5405C,2949.67,22.721667,75.800833,15.380830,73.831420,842.052913,840,0100,2020-06-18 05:28:00,0428,0528
39975,135939,1339,premium,Akasa Air,2020-06-25 13:37:00,Sardar Vallabhbhai Patel International Airport...,Shillong Airport (SHL),0.567361,QP2071,5988.03,23.077240,72.634650,25.703600,91.978700,1978.782106,820,0224,2020-06-25 16:01:00,1337,1601
39976,135940,1339,firstClass,Akasa Air,2020-02-07 17:27:00,Prayagraj Airport (IXD),Visakhapatnam Airport (VTZ),0.727083,QP589J,4272.88,25.440060,81.733870,17.721200,83.224500,871.997188,820,0103,2020-02-07 18:30:00,1727,1830
39977,135941,1339,firstClass,IndiGo,2020-09-07 00:46:00,Surat Airport (STV),Goa International Airport (GOI),0.031944,6E4801N,3349.72,21.114100,72.741800,15.380830,73.831420,647.800512,830,0046,2020-09-07 01:32:00,0046,0132
39978,135942,1339,economic,IndiGo,2020-07-16 12:14:00,Raja Bhoj Airport (BHO),Prayagraj Airport (IXD),0.509722,6E4290X,1673.92,23.287470,77.337370,25.440060,81.733870,505.527757,830,0036,2020-07-16 12:50:00,1214,1250

In [55]:
x.to_excel('LastFlight.xlsx', index=False)
from IPython.display import FileLink
FileLink('LastFlight.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\LastFlight.xlsx

In [62]:
x

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Departure Time,flight_number,Calculated_Flight_Price,Dep_Lat,Dep_Lon,Arr_Lat,Arr_Lon,Distance_km,Speed_kmh,EstimatedDuration_HHMM,Arrival_Date,Departure_time,Arrival_time
0,0,0,firstClass,GoAir,2019-09-26 03:59:00,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),0.165972,G84279,4810.84,11.030030,77.043380,17.721200,83.224500,998.106548,815,0113,2019-09-26 05:12:00,0359,0512
1,2,0,firstClass,IndiGo,2019-10-10 01:02:00,Birsa Munda Airport (IXR),Shillong Airport (SHL),0.043056,6E4357O,3580.20,23.314250,85.321670,25.703600,91.978700,723.904020,830,0052,2019-10-10 01:54:00,0102,0154
2,7,0,economic,Air India,2019-11-14 00:15:00,Goa International Airport (GOI),Birsa Munda Airport (IXR),0.010417,AI3905,3785.16,15.380830,73.831420,23.314250,85.321670,1492.553600,840,0146,2019-11-14 02:01:00,0015,0201
3,11,0,premium,SpiceJet,2019-12-12 17:35:00,Sardar Vallabhbhai Patel International Airport...,Raigarh Airport (None),0.732639,SG2659K,3669.93,23.077240,72.634650,21.823889,83.360278,1110.753989,820,0121,2019-12-12 18:56:00,1735,1856
4,13,0,firstClass,GoAir,2019-12-26 18:18:00,Rajiv Gandhi International Airport (HYD),Netaji Subhas Chandra Bose International Airpo...,0.762500,G83184,5780.44,17.231320,78.429860,22.654740,88.446720,1207.676138,815,0128,2019-12-26 19:46:00,1818,1946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,premium,Air India,2020-06-18 04:28:00,Devi Ahilya Bai Holkar Airport (IDR),Goa International Airport (GOI),0.186111,AI5405C,2949.67,22.721667,75.800833,15.380830,73.831420,842.052913,840,0100,2020-06-18 05:28:00,0428,0528
39975,135939,1339,premium,Akasa Air,2020-06-25 13:37:00,Sardar Vallabhbhai Patel International Airport...,Shillong Airport (SHL),0.567361,QP2071,5988.03,23.077240,72.634650,25.703600,91.978700,1978.782106,820,0224,2020-06-25 16:01:00,1337,1601
39976,135940,1339,firstClass,Akasa Air,2020-02-07 17:27:00,Prayagraj Airport (IXD),Visakhapatnam Airport (VTZ),0.727083,QP589J,4272.88,25.440060,81.733870,17.721200,83.224500,871.997188,820,0103,2020-02-07 18:30:00,1727,1830
39977,135941,1339,firstClass,IndiGo,2020-09-07 00:46:00,Surat Airport (STV),Goa International Airport (GOI),0.031944,6E4801N,3349.72,21.114100,72.741800,15.380830,73.831420,647.800512,830,0046,2020-09-07 01:32:00,0046,0132
39978,135942,1339,economic,IndiGo,2020-07-16 12:14:00,Raja Bhoj Airport (BHO),Prayagraj Airport (IXD),0.509722,6E4290X,1673.92,23.287470,77.337370,25.440060,81.733870,505.527757,830,0036,2020-07-16 12:50:00,1214,1250

In [64]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39979 entries, 0 to 39978
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   travelCode               39979 non-null  int64
 1   User_ID                  39979 non-null  int64
 2   flightType               39979 non-null  object
 3   Flight_agency            39979 non-null  object
 4   Departure_date           39979 non-null  datetime64[ns]
 5   Departure                39979 non-null  object
 6   Arrival                  39979 non-null  object
 7   Departure Time           39979 non-null  float64
 8   flight_number            39979 non-null  object
 9   Calculated_Flight_Price  39979 non-null  float64
 10  Dep_Lat                  39979 non-null  float64
 11  Dep_Lon                  39979 non-null  float64
 12  Arr_Lat                  39979 non-null  float64
 13  Arr_Lon                  39979 non-null  float64
 14  Distance_km              39979 non-null  float64
 15  Speed_kmh                39979 non-null  int64
 16  EstimatedDuration_HHMM   39979 non-null  object
 17  Arrival_Date             39979 non-null  datetime64[ns]
 18  Departure_time           39979 non-null  object
 19  Arrival_time             39979 non-null  object
dtypes: datetime64[ns](2), float64(7), int64(3), object(8)
memory usage: 6.1+ MB

In [66]:
x["Departure_time"] = x["Departure_time"].astype(str)

x["Departure_time"] = x["Departure_time"].str.zfill(4)  
x["Departure_time"] = x["Departure_time"].str[:2] + ":" + x["Departure_time"].str[2:]

In [69]:
x["Arrival_time"] = x["Arrival_time"].astype(str)

x["Arrival_time"] = x["Arrival_time"].str.zfill(4)  
x["Arrival_time"] = x["Arrival_time"].str[:2] + ":" + x["Arrival_time"].str[2:]

In [71]:
x["EstimatedDuration_HHMM"] = x["EstimatedDuration_HHMM"].astype(str)

x["EstimatedDuration_HHMM"] = x["EstimatedDuration_HHMM"].str.zfill(4)  
x["EstimatedDuration_HHMM"] = x["EstimatedDuration_HHMM"].str[:2] + ":" + x["EstimatedDuration_HHMM"].str[2:]

In [75]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39979 entries, 0 to 39978
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   travelCode               39979 non-null  int64
 1   User_ID                  39979 non-null  int64
 2   flightType               39979 non-null  object
 3   Flight_agency            39979 non-null  object
 4   Departure_date           39979 non-null  datetime64[ns]
 5   Departure                39979 non-null  object
 6   Arrival                  39979 non-null  object
 7   flight_number            39979 non-null  object
 8   Calculated_Flight_Price  39979 non-null  float64
 9   Distance_km              39979 non-null  float64
 10  EstimatedDuration_HHMM   39979 non-null  object
 11  Arrival_Date             39979 non-null  datetime64[ns]
 12  Departure_time           39979 non-null  object
 13  Arrival_time             39979 non-null  object
dtypes: datetime64[ns](2), float64(2), int64(2), object(8)
memory usage: 4.3+ MB

In [74]:
x = x.drop(columns={'Departure Time','Dep_Lat','Dep_Lon','Arr_Lat','Arr_Lon','Speed_kmh'})

In [76]:
order = ['travelCode','User_ID','Departure','Arrival','Departure_date','Departure_time','Arrival_Date','Arrival_time','flight_number','flightType','Flight_agency','Distance_km','EstimatedDuration_HHMM','Calculated_Flight_Price']

In [80]:
x = x[order]

In [81]:
x.to_excel('FinalFlightCTO.xlsx', index=False)
from IPython.display import FileLink
FileLink('FinalFlightCTO.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\FinalFlightCTO.xlsx