In [20]:
import pandas as pd

In [21]:
df = pd.read_excel('April-May.xlsx')
df

,flight_type,flight_agency,departure_date,departure,arrival,flight_number,flight_distance,flight_duration,flight_price,departure_time,Arrival_date,arrival_time
0,firstClass,GoAir,2025-04-10 13:19:00,Lokpriya Gopinath Bordoloi International Airpo...,Sheikh ul-Alam International Airport (SXR),G81343G,1836.680899,02:15,8344.290039,13:19:00,2025-04-10 15:34:00,15:34:00
1,firstClass,Akasa Air,2025-04-10 19:36:00,Vijayawada Airport (VGA),Biju Patnaik International Airport (BBI),QP2350,671.626075,00:49,3336.770020,19:36:00,2025-04-10 20:25:00,20:25:00
2,firstClass,IndiGo,2025-04-18 09:05:00,Biju Patnaik International Airport (BAI),Maharana Pratap Airport (UDR),6E1901,1317.539107,01:35,6291.720215,09:05:00,2025-04-18 10:40:00,10:40:00
3,firstClass,SpiceJet,2025-04-01 07:38:00,Nashik International Airport (ISK),Biju Patnaik International Airport (BAI),SG3982,1242.222092,01:30,5997.950195,07:38:00,2025-04-01 09:08:00,09:08:00
4,firstClass,SpiceJet,2025-04-25 08:22:00,Ayodhya Airport (under construction),Sri Guru Ram Dass Jee International Airport (ATQ),SG4683,901.534106,01:05,4464.419922,08:22:00,2025-04-25 09:27:00,09:27:00
...,...,...,...,...,...,...,...,...,...,...,...,...
271883,firstClass,SpiceJet,2025-04-12 23:24:00,Puducherry Airport (PNY),Sheikh ul-Alam International Airport (SXR),SG3612,2536.928839,03:05,11215.459961,23:24:00,2025-04-13 02:29:00,02:29:00
271884,economic,Akasa Air,2025-04-23 06:19:00,Imphal International Airport (IMF),Mopa International Airport (GOX),QP4713D,2314.231288,02:49,20625.310547,06:19:00,2025-04-23 09:08:00,09:08:00
271885,economic,Air India,2025-04-28 01:04:00,Kempegowda International Airport (BLR),Sardar Vallabhbhai Patel International Airport...,AI1661,1221.726282,01:27,3351.899902,01:04:00,2025-04-28 02:31:00,02:31:00
271886,economic,SpiceJet,2025-04-02 20:34:00,Biju Patnaik International Airport (BAI),Goa International Airport (GOI),SG4733,1378.705163,01:40,3594.030029,20:34:00,2025-04-02 22:14:00,22:14:00
271887,economic,Akasa Air,2025-04-07 11:38:00,Indira Gandhi International Airport (DEL),Mopa International Airport (GOX),QP5133,1465.340539,01:47,16979.169922,11:38:00,2025-04-07 13:25:00,13:25:00

In [22]:
df = df[df['arrival'] != "Chhatrapati Shivaji Maharaj International Airport (BOmm)"]

In [23]:
df

,flight_type,flight_agency,departure_date,departure,arrival,flight_number,flight_distance,flight_duration,flight_price,departure_time,Arrival_date,arrival_time
0,firstClass,GoAir,2025-04-10 13:19:00,Lokpriya Gopinath Bordoloi International Airpo...,Sheikh ul-Alam International Airport (SXR),G81343G,1836.680899,02:15,8344.290039,13:19:00,2025-04-10 15:34:00,15:34:00
1,firstClass,Akasa Air,2025-04-10 19:36:00,Vijayawada Airport (VGA),Biju Patnaik International Airport (BBI),QP2350,671.626075,00:49,3336.770020,19:36:00,2025-04-10 20:25:00,20:25:00
2,firstClass,IndiGo,2025-04-18 09:05:00,Biju Patnaik International Airport (BAI),Maharana Pratap Airport (UDR),6E1901,1317.539107,01:35,6291.720215,09:05:00,2025-04-18 10:40:00,10:40:00
3,firstClass,SpiceJet,2025-04-01 07:38:00,Nashik International Airport (ISK),Biju Patnaik International Airport (BAI),SG3982,1242.222092,01:30,5997.950195,07:38:00,2025-04-01 09:08:00,09:08:00
4,firstClass,SpiceJet,2025-04-25 08:22:00,Ayodhya Airport (under construction),Sri Guru Ram Dass Jee International Airport (ATQ),SG4683,901.534106,01:05,4464.419922,08:22:00,2025-04-25 09:27:00,09:27:00
...,...,...,...,...,...,...,...,...,...,...,...,...
271883,firstClass,SpiceJet,2025-04-12 23:24:00,Puducherry Airport (PNY),Sheikh ul-Alam International Airport (SXR),SG3612,2536.928839,03:05,11215.459961,23:24:00,2025-04-13 02:29:00,02:29:00
271884,economic,Akasa Air,2025-04-23 06:19:00,Imphal International Airport (IMF),Mopa International Airport (GOX),QP4713D,2314.231288,02:49,20625.310547,06:19:00,2025-04-23 09:08:00,09:08:00
271885,economic,Air India,2025-04-28 01:04:00,Kempegowda International Airport (BLR),Sardar Vallabhbhai Patel International Airport...,AI1661,1221.726282,01:27,3351.899902,01:04:00,2025-04-28 02:31:00,02:31:00
271886,economic,SpiceJet,2025-04-02 20:34:00,Biju Patnaik International Airport (BAI),Goa International Airport (GOI),SG4733,1378.705163,01:40,3594.030029,20:34:00,2025-04-02 22:14:00,22:14:00
271887,economic,Akasa Air,2025-04-07 11:38:00,Indira Gandhi International Airport (DEL),Mopa International Airport (GOX),QP5133,1465.340539,01:47,16979.169922,11:38:00,2025-04-07 13:25:00,13:25:00

In [24]:
df = df[df['arrival'] != "Chhatrapati Shivaji Maharaj International Airport (BOmm)"]

In [25]:
df

,flight_type,flight_agency,departure_date,departure,arrival,flight_number,flight_distance,flight_duration,flight_price,departure_time,Arrival_date,arrival_time
0,firstClass,GoAir,2025-04-10 13:19:00,Lokpriya Gopinath Bordoloi International Airpo...,Sheikh ul-Alam International Airport (SXR),G81343G,1836.680899,02:15,8344.290039,13:19:00,2025-04-10 15:34:00,15:34:00
1,firstClass,Akasa Air,2025-04-10 19:36:00,Vijayawada Airport (VGA),Biju Patnaik International Airport (BBI),QP2350,671.626075,00:49,3336.770020,19:36:00,2025-04-10 20:25:00,20:25:00
2,firstClass,IndiGo,2025-04-18 09:05:00,Biju Patnaik International Airport (BAI),Maharana Pratap Airport (UDR),6E1901,1317.539107,01:35,6291.720215,09:05:00,2025-04-18 10:40:00,10:40:00
3,firstClass,SpiceJet,2025-04-01 07:38:00,Nashik International Airport (ISK),Biju Patnaik International Airport (BAI),SG3982,1242.222092,01:30,5997.950195,07:38:00,2025-04-01 09:08:00,09:08:00
4,firstClass,SpiceJet,2025-04-25 08:22:00,Ayodhya Airport (under construction),Sri Guru Ram Dass Jee International Airport (ATQ),SG4683,901.534106,01:05,4464.419922,08:22:00,2025-04-25 09:27:00,09:27:00
...,...,...,...,...,...,...,...,...,...,...,...,...
271883,firstClass,SpiceJet,2025-04-12 23:24:00,Puducherry Airport (PNY),Sheikh ul-Alam International Airport (SXR),SG3612,2536.928839,03:05,11215.459961,23:24:00,2025-04-13 02:29:00,02:29:00
271884,economic,Akasa Air,2025-04-23 06:19:00,Imphal International Airport (IMF),Mopa International Airport (GOX),QP4713D,2314.231288,02:49,20625.310547,06:19:00,2025-04-23 09:08:00,09:08:00
271885,economic,Air India,2025-04-28 01:04:00,Kempegowda International Airport (BLR),Sardar Vallabhbhai Patel International Airport...,AI1661,1221.726282,01:27,3351.899902,01:04:00,2025-04-28 02:31:00,02:31:00
271886,economic,SpiceJet,2025-04-02 20:34:00,Biju Patnaik International Airport (BAI),Goa International Airport (GOI),SG4733,1378.705163,01:40,3594.030029,20:34:00,2025-04-02 22:14:00,22:14:00
271887,economic,Akasa Air,2025-04-07 11:38:00,Indira Gandhi International Airport (DEL),Mopa International Airport (GOX),QP5133,1465.340539,01:47,16979.169922,11:38:00,2025-04-07 13:25:00,13:25:00

In [26]:
x = df[df['arrival'] == "Chhatrapati Shivaji Maharaj International Airport (BOmm)"]

In [27]:
x

Empty DataFrame
Columns: [flight_type, flight_agency, departure_date, departure, arrival, flight_number, flight_distance, flight_duration, flight_price, departure_time, Arrival_date, arrival_time]
Index: []

In [28]:
df[(df['arrival'] == "Chhatrapati Shivaji Maharaj International Airport (BOmm)") & 
   (df['departure'] == "Chhatrapati Shivaji Maharaj International Airport (BOmm)")]

Empty DataFrame
Columns: [flight_type, flight_agency, departure_date, departure, arrival, flight_number, flight_distance, flight_duration, flight_price, departure_time, Arrival_date, arrival_time]
Index: []

In [29]:
df_loc = pd.read_excel("AirportCoordinates.xlsx")

In [31]:
df_loc

,LocationID,Name,Address,City,Latitude,Longitude
0,1,Coimbatore International Airport (CJB),"Coimbatore International Airport, Avinashi Roa...",Coimbatore (CJB),11.030030,77.043380
1,2,Birsa Munda Airport (IXR),"Birsa Munda Airport, Hinoo, Ranchi, Jharkhand ...",Ranchi (IXR),23.314250,85.321670
2,3,Goa International Airport (GOI),"Goa International Airport, Airport Road, Dabol...",Dabolim (GOI),15.380830,73.831420
3,4,Sardar Vallabhbhai Patel International Airport...,Sardar Vallabhbhai Patel International Airport...,Ahmedabad (AMD),23.077240,72.634650
4,5,Rajiv Gandhi International Airport (HYD),"Rajiv Gandhi International Airport, Shamshabad...",Hyderabad (HYD),17.231320,78.429860
5,6,Agartala Airport (IXA),"Agartala Airport, Agartala, Tripura 799009",Khowai (IXA),23.886980,91.240450
6,7,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Navi Mumbai,19.088690,72.867920
7,8,Pune International Airport (PNQ),"Pune International Airport, Lohegaon, Pune, Ma...",Pune (PNQ),18.340000,73.550000
8,9,Vijayawada Airport (VGA),"Vijayawada Airport, Gannavaram, Andhra Pradesh...",Vijayawada (VGA),16.530430,80.796850
9,10,Gwalior Airport (GWL),"Gwalior Airport, Maharajpur, Gwalior, Madhya P...",Gwalior (GWL),26.293340,78.227750
10,11,Kempegowda International Airport (BLR),"Kempegowda International Airport, Devanahalli,...",Bengaluru (BLR),13.200710,77.708790
11,12,Lokpriya Gopinath Bordoloi International Airpo...,Lokpriya Gopinath Bordoloi International Airpo...,Guwahati (GAU),26.106090,91.585940
12,13,Bilaspur Airport (PAB),"Bilaspur Airport, Chakarbhata, Bilaspur, Chhat...",Bilaspur (PAB),21.988400,82.110980
13,14,Swami Vivekananda Airport (RPR),"Swami Vivekananda Airport, Ramchandi, Naya Rai...",Raipur (RPR),21.180400,81.738800
14,15,Puducherry Airport (PNY),"Puducherry Airport, Lawspet, Puducherry 605008",Puducherry (PNY),11.580000,79.480000
15,16,Sonari Airport (IXW),"Sonari Airport, Sonari, Jamshedpur, Jharkhand ...",Jamshedpur (IXW),22.480000,86.100000
16,17,Nashik International Airport (ISK),"Nashik International Airport, Ozar, Nashik, Ma...",Nashik (ISK),20.119444,73.913611
17,18,Mopa International Airport (GOX),"Mopa International Airport, Mopa, Pernem, Goa ...",Mopa (GOX),15.731300,73.868170
18,19,Prayagraj Airport (IXD),"Prayagraj Airport, Bamrauli, Prayagraj, Uttar ...",Prayagraj (IXD),25.440060,81.733870
19,20,Vadodara Airport (BDQ),"Vadodara Airport, Harni Road, Vadodara, Gujara...",Vadodara (BDQ),22.336200,73.226300
20,21,Ludhiana Airport (LUH),"Ludhiana Airport, Sahnewal, Ludhiana, Punjab 1...",Ludhiana (LUH),30.854700,75.952600
21,22,Raigarh Airport (None),"Raigarh Airport, Kondatarai, Raigarh, Chhattis...",Raigarh,21.823889,83.360278
22,23,Chennai International Airport (MAA),"Chennai International Airport, GST Road, Meena...",Chennai (MAA),12.988330,80.165780
23,24,Biju Patnaik International Airport (BAI),"Biju Patnaik International Airport, Airport Ro...",Puri (BAI),20.244360,85.817780
24,25,Tirupati Airport (TIR),"Tirupati Airport, Renigunta, Andhra Pradesh 51...",Tirupati (TIR),13.632500,79.543300
25,26,Dehradun Airport (DED),"Dehradun Airport, Jolly Grant, Dehradun, Uttar...",Dehradun (DED),30.189700,78.180300
26,27,Sheikh ul-Alam International Airport (SXR),"Sheikh ul-Alam International Airport, Aerodrom...",Srinagar (SXR),33.987100,74.774200
27,28,Indira Gandhi International Airport (DEL),"Indira Gandhi International Airport, New Delhi...",Delhi NCR (DEL),28.566500,77.103090
28,29,Donyi Polo Airport (HGI),"Donyi Polo Airport, Hollongi, Itanagar, Arunac...",Itanagar (HGI),26.970000,93.664722
29,30,Lal Bahadur Shastri International Airport (VNS),"Lal Bahadur Shastri International Airport, Bab...",Varanasi (VNS),25.452222,82.859444
30,31,Rupsi Airport (RUP),"Rupsi Airport, Rupsi, Assam 783372",Dhubri (RUP),26.141180,89.906870
31,32,Netaji Subhas Chandra Bose International Airpo...,Netaji Subhas Chandra Bose International Airpo...,Kolkata (CCU),22.654740,88.446720
32,33,Pakyong Airport (PYG),"Pakyong Airport, Pakyong, Sikkim 737106",Gangtok (PYG),27.227560,88.585960
33,34,Shillong Airport (SHL),"Shillong Airport, Umroi, Meghalaya 793103",Shillong (SHL),25.703600,91.978700
34,35,Sri Guru Ram Dass Jee International Airport (ATQ),"Sri Guru Ram Dass Jee International Airport, A...",Amritsar (ATQ),31.709590,74.797260
35,36,Raja Bhoj Airport (BHO),"Raja Bhoj Airport, Gandhi Nagar, Bhopal, Madhy...",Bhopal (BHO),23.287470,77.337370
36,37,Jaipur International Airport (JAI),"Jaipur International Airport, Airport Road, Sa...",Jaipur (JAI),26.824190,75.812160
37,38,Kullu–Manali Airport (KUU),"Kullu–Manali Airport, Bhuntar, Kullu, Himachal...",Kullu-Manali (KUU),31.876667,77.154444
38,39,Ayodhya Airport (under construction),"Ayodhya Airport, Ayodhya, Uttar Pradesh 224123",Ayodhya,26.748034,82.150781
39,40,Biju Patnaik International Airport (BBI),"Biju Patnaik International Airport, Airport Ro...",Bhubaneswar (BBI),20.244360,85.817780
40,41,Trivandrum International Airport (TRV),"Trivandrum International Airport, Vallakkadavu...",Thiruvananthapuram (TRV),8.482120,76.920110
41,42,Kota Airport (KTU),"Kota Airport, Aerodrome Circle, Kota, Rajastha...",Kota (KTU),25.160220,75.845630
42,43,Surat Airport (STV),"Surat Airport, Dumas Road, Surat, Gujarat 395007",Surat (STV),21.114100,72.741800
43,44,Maharana Pratap Airport (UDR),"Maharana Pratap Airport, NH 76, Dabok, Udaipur...",Udaipur (UDR),24.617840,73.896620
44,45,Diu Airport (DIU),"Diu Airport, Diu, Daman and Diu 362520",Diu (DIU),20.713100,70.921100
45,46,Chandigarh International Airport (IXC),"Chandigarh International Airport, Mohali, Punj...",Chandigarh (IXC),30.673500,76.788500
46,47,Shimla Airport (SLV),"Shimla Airport, Jubbarhatti, Shimla, Himachal ...",Shimla (SLV),31.081800,77.068000
47,48,Imphal International Airport (IMF),"Imphal International Airport, Imphal, Manipur ...",Imphal (IMF),24.759950,93.896700
48,49,Hisar Airport (HSS),"Hisar Airport, Hisar, Haryana 125001",Hisar (HSS),29.179440,75.755340
49,50,Visakhapatnam Airport (VTZ),"Visakhapatnam Airport, NAD Junction, Visakhapa...",Visakhapatnam (VTZ),17.721200,83.224500
50,51,Devi Ahilya Bai Holkar Airport (IDR),"Devi Ahilya Bai Holkar Airport, Indore, Madhya...",Indore (IDR),22.721667,75.800833
51,52,Mysore Airport (MYQ),"Mysore Airport, Mandakalli, Mysuru, Karnataka ...",Mysuru (MYQ),12.307200,76.649700
52,53,Jay Prakash Narayan Airport (PAT),"Jay Prakash Narayan Airport, Sheikhpura, Patna...",Patna (PAT),25.591389,85.089167
53,54,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Mumbai (BOM),19.088690,72.867920

In [32]:
code_to_name = dict(zip(df_loc['Name'], df_loc['City']))
df['Departure_City'] = df['departure'].map(code_to_name)
df['Arrival_City'] = df['arrival'].map(code_to_name)
df

,flight_type,flight_agency,departure_date,departure,arrival,flight_number,flight_distance,flight_duration,flight_price,departure_time,Arrival_date,arrival_time,Departure_City,Arrival_City
0,firstClass,GoAir,2025-04-10 13:19:00,Lokpriya Gopinath Bordoloi International Airpo...,Sheikh ul-Alam International Airport (SXR),G81343G,1836.680899,02:15,8344.290039,13:19:00,2025-04-10 15:34:00,15:34:00,Guwahati (GAU),Srinagar (SXR)
1,firstClass,Akasa Air,2025-04-10 19:36:00,Vijayawada Airport (VGA),Biju Patnaik International Airport (BBI),QP2350,671.626075,00:49,3336.770020,19:36:00,2025-04-10 20:25:00,20:25:00,Vijayawada (VGA),Bhubaneswar (BBI)
2,firstClass,IndiGo,2025-04-18 09:05:00,Biju Patnaik International Airport (BAI),Maharana Pratap Airport (UDR),6E1901,1317.539107,01:35,6291.720215,09:05:00,2025-04-18 10:40:00,10:40:00,Puri (BAI),Udaipur (UDR)
3,firstClass,SpiceJet,2025-04-01 07:38:00,Nashik International Airport (ISK),Biju Patnaik International Airport (BAI),SG3982,1242.222092,01:30,5997.950195,07:38:00,2025-04-01 09:08:00,09:08:00,Nashik (ISK),Puri (BAI)
4,firstClass,SpiceJet,2025-04-25 08:22:00,Ayodhya Airport (under construction),Sri Guru Ram Dass Jee International Airport (ATQ),SG4683,901.534106,01:05,4464.419922,08:22:00,2025-04-25 09:27:00,09:27:00,Ayodhya,Amritsar (ATQ)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271883,firstClass,SpiceJet,2025-04-12 23:24:00,Puducherry Airport (PNY),Sheikh ul-Alam International Airport (SXR),SG3612,2536.928839,03:05,11215.459961,23:24:00,2025-04-13 02:29:00,02:29:00,Puducherry (PNY),Srinagar (SXR)
271884,economic,Akasa Air,2025-04-23 06:19:00,Imphal International Airport (IMF),Mopa International Airport (GOX),QP4713D,2314.231288,02:49,20625.310547,06:19:00,2025-04-23 09:08:00,09:08:00,Imphal (IMF),Mopa (GOX)
271885,economic,Air India,2025-04-28 01:04:00,Kempegowda International Airport (BLR),Sardar Vallabhbhai Patel International Airport...,AI1661,1221.726282,01:27,3351.899902,01:04:00,2025-04-28 02:31:00,02:31:00,Bengaluru (BLR),Ahmedabad (AMD)
271886,economic,SpiceJet,2025-04-02 20:34:00,Biju Patnaik International Airport (BAI),Goa International Airport (GOI),SG4733,1378.705163,01:40,3594.030029,20:34:00,2025-04-02 22:14:00,22:14:00,Puri (BAI),Dabolim (GOI)
271887,economic,Akasa Air,2025-04-07 11:38:00,Indira Gandhi International Airport (DEL),Mopa International Airport (GOX),QP5133,1465.340539,01:47,16979.169922,11:38:00,2025-04-07 13:25:00,13:25:00,Delhi NCR (DEL),Mopa (GOX)

In [33]:
df.to_excel('April-May2025.xlsx', index=False)
from IPython.display import FileLink
FileLink('April-May2025.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\April-May2025.xlsx