In [93]:
import pandas as pd
import numpy as np

In [180]:
df = pd.read_excel("FinalFlightCTO.xlsx")

In [166]:
mid = len(df)//2
df = df.iloc[mid:]

In [182]:
df_filtered = df[
    (df['Departure'] == "Coimbatore International Airport (CJB)")
]
df_filtered

,travelCode,User_ID,Departure,Arrival,Departure_date,Departure_time,Arrival_Date,Arrival_time,flight_number,flightType,Flight_agency,Distance_km,EstimatedDuration_HHMM,Calculated_Flight_Price
0,0,0,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2019-09-26 03:59:00,03:59,2019-09-26 05:12:00,05:12,G84279,firstClass,GoAir,998.106548,01:13,4810.84
83,290,3,Coimbatore International Airport (CJB),Sheikh ul-Alam International Airport (SXR),2020-12-17 11:01:00,11:01,2020-12-17 14:08:00,14:08,SG4402I,firstClass,SpiceJet,2563.113925,03:07,11436.08
148,517,4,Coimbatore International Airport (CJB),Hisar Airport (HSS),2021-01-07 22:48:00,22:48,2021-01-08 01:15:00,01:15,QP5720,economic,Akasa Air,2022.546418,02:27,13977.42
321,1151,10,Coimbatore International Airport (CJB),Swami Vivekananda Airport (RPR),2020-06-25 02:08:00,02:08,2020-06-25 03:37:00,03:37,6E2240,firstClass,IndiGo,1234.779173,01:29,5811.68
347,1227,11,Coimbatore International Airport (CJB),Puducherry Airport (PNY),2020-09-17 01:20:00,01:20,2020-09-17 01:39:00,01:39,SG5541,premium,SpiceJet,272.628263,00:19,1515.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39747,135101,1330,Coimbatore International Airport (CJB),Mysore Airport (MYQ),2020-08-13 23:22:00,23:22,2020-08-13 23:32:00,23:32,I51501,firstClass,AirAsia India,148.344222,00:10,1219.20
39786,135241,1331,Coimbatore International Airport (CJB),Nashik International Airport (ISK),2020-03-26 10:32:00,10:32,2020-03-26 11:49:00,11:49,QP4082,firstClass,Akasa Air,1064.705580,01:17,5033.96
39858,135523,1332,Coimbatore International Airport (CJB),Devi Ahilya Bai Holkar Airport (IDR),2022-01-12 16:34:00,16:34,2022-01-12 18:09:00,18:09,QP4253M,premium,Akasa Air,1306.726870,01:35,4170.19
39864,135544,1333,Coimbatore International Airport (CJB),Indira Gandhi International Airport (DEL),2019-12-12 00:03:00,00:03,2019-12-12 02:22:00,02:22,AI418,firstClass,Air India,1949.976393,02:19,8892.68
39869,135564,1333,Coimbatore International Airport (CJB),Chhatrapati Shivaji Maharaj International Airp...,2020-04-30 15:16:00,15:16,2020-04-30 16:29:00,16:29,SG4611,firstClass,SpiceJet,1001.781760,01:13,4811.16

In [95]:
start_date = pd.Timestamp("2025-03-01")
end_date = pd.Timestamp("2025-05-15")

In [96]:
df["Departure_date"] = df["Departure_date"].apply(lambda _: start_date + pd.to_timedelta(np.random.randint(0, (end_date - start_date).days), unit='D'))

In [97]:
df = df.drop(columns={'Arrival_Date'})

In [67]:
df_filtered = df[
    (df['Departure_date'] == pd.to_datetime('2025-04-29')) &
    (df['Departure'] == "Coimbatore International Airport (CJB)")
]
df_filtered['Arrival'] = "Visakhapatnam Airport (VTZ)"
df_filtered

C:\Users\SURAJ\AppData\Local\Temp\ipykernel_17276\2532492139.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Arrival'] = "Visakhapatnam Airport (VTZ)"

,travelCode,User_ID,Departure,Arrival,Departure_date,Departure_time,Arrival_time,flight_number,flightType,Flight_agency,Distance_km,EstimatedDuration_HHMM,Calculated_Flight_Price
0,0,0,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,03:59,05:12,G84279,firstClass,GoAir,998.106548,01:13,4810.84
7988,26772,258,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,16:13,17:46,AI4771,firstClass,Air India,1306.726870,01:33,6142.60
12276,41362,401,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,12:07,12:25,QP1417,economic,Akasa Air,251.975169,00:18,1080.62
14101,47487,461,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,07:17,09:43,6E1768,premium,IndiGo,2022.546418,02:26,18190.65
14348,48391,474,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,09:54,11:31,QP1439,economic,Akasa Air,1332.486390,01:37,3632.50
14458,48785,478,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,21:55,23:32,G83989,firstClass,GoAir,1321.037145,01:37,6342.36
14833,50037,488,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,15:37,17:18,QP3560,economic,Akasa Air,1389.268586,01:41,3459.32
15202,51353,500,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,17:49,19:51,AI5035Q,premium,Air India,1716.495447,02:02,5328.31
17157,58027,565,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,14:46,16:59,QP3088,firstClass,Akasa Air,1827.820174,02:13,8325.52

In [98]:
df["Departure_date"] = pd.to_datetime(df["Departure_date"])
df["Departure_timee"] = pd.to_timedelta(df["Departure_time"] + ":00")
df["EstimatedDuration_HHmm"] = pd.to_timedelta(df["EstimatedDuration_HHMM"] + ":00") 
df["Arrival_Date"] = df["Departure_date"] + df["Departure_timee"] + df["EstimatedDuration_HHmm"]
df["Departure_date"] = df["Departure_date"] + df["Departure_timee"]

In [99]:
df = df.drop(columns={'Departure_timee','EstimatedDuration_HHmm'})

In [100]:
df["Departure_date"] = df["Departure_date"].dt.strftime('%Y-%m-%d')
df["Arrival_Date"] = df["Arrival_Date"].dt.strftime('%Y-%m-%d')

In [102]:
df

,travelCode,User_ID,Departure,Arrival,Departure_date,Departure_time,Arrival_time,flight_number,flightType,Flight_agency,Distance_km,EstimatedDuration_HHMM,Calculated_Flight_Price,Arrival_Date
0,0,0,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-03-05,03:59,05:12,G84279,firstClass,GoAir,998.106548,01:13,4810.84,2025-03-05
1,2,0,Birsa Munda Airport (IXR),Shillong Airport (SHL),2025-03-21,01:02,01:54,6E4357O,firstClass,IndiGo,723.904020,00:52,3580.20,2025-03-21
2,7,0,Goa International Airport (GOI),Birsa Munda Airport (IXR),2025-04-11,00:15,02:01,AI3905,economic,Air India,1492.553600,01:46,3785.16,2025-04-11
3,11,0,Sardar Vallabhbhai Patel International Airport...,Raigarh Airport (None),2025-04-26,17:35,18:56,SG2659K,premium,SpiceJet,1110.753989,01:21,3669.93,2025-04-26
4,13,0,Rajiv Gandhi International Airport (HYD),Netaji Subhas Chandra Bose International Airpo...,2025-03-20,18:18,19:46,G83184,firstClass,GoAir,1207.676138,01:28,5780.44,2025-03-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,Devi Ahilya Bai Holkar Airport (IDR),Goa International Airport (GOI),2025-03-29,04:28,05:28,AI5405C,premium,Air India,842.052913,01:00,2949.67,2025-03-29
39975,135939,1339,Sardar Vallabhbhai Patel International Airport...,Shillong Airport (SHL),2025-03-09,13:37,16:01,QP2071,premium,Akasa Air,1978.782106,02:24,5988.03,2025-03-09
39976,135940,1339,Prayagraj Airport (IXD),Visakhapatnam Airport (VTZ),2025-04-29,17:27,18:30,QP589J,firstClass,Akasa Air,871.997188,01:03,4272.88,2025-04-29
39977,135941,1339,Surat Airport (STV),Goa International Airport (GOI),2025-03-22,00:46,01:32,6E4801N,firstClass,IndiGo,647.800512,00:46,3349.72,2025-03-22
39978,135942,1339,Raja Bhoj Airport (BHO),Prayagraj Airport (IXD),2025-03-23,12:14,12:50,6E4290X,economic,IndiGo,505.527757,00:36,1673.92,2025-03-23

In [44]:
df.to_excel('FlightForFrontend.xlsx', index=False)
from IPython.display import FileLink
FileLink('FlightForFrontend.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\FlightForFrontend.xlsx

In [73]:
df_filtered = df_filtered.drop(columns={'Distance_km','EstimatedDuration_HHMM','Arrival_time'})

In [74]:
d = {'Distance_km': 998.106548, 'EstimatedDuration_HHMM': pd.to_timedelta("01:13:00")}

In [79]:
df_filtered['Flight_Distance'] = 998.106548

In [81]:
df_filtered['EstimatedDuration_HHMM'] = pd.to_timedelta("01:13:00")

In [82]:
df_filtered

,travelCode,User_ID,Departure,Arrival,Departure_date,Departure_time,flight_number,flightType,Flight_agency,Calculated_Flight_Price,Flight_Distance,EstimatedDuration_HHMM
0,0,0,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,03:59,G84279,firstClass,GoAir,4810.84,998.106548,0 days 01:13:00
7988,26772,258,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,16:13,AI4771,firstClass,Air India,6142.60,998.106548,0 days 01:13:00
12276,41362,401,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,12:07,QP1417,economic,Akasa Air,1080.62,998.106548,0 days 01:13:00
14101,47487,461,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,07:17,6E1768,premium,IndiGo,18190.65,998.106548,0 days 01:13:00
14348,48391,474,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,09:54,QP1439,economic,Akasa Air,3632.50,998.106548,0 days 01:13:00
14458,48785,478,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,21:55,G83989,firstClass,GoAir,6342.36,998.106548,0 days 01:13:00
14833,50037,488,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,15:37,QP3560,economic,Akasa Air,3459.32,998.106548,0 days 01:13:00
15202,51353,500,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,17:49,AI5035Q,premium,Air India,5328.31,998.106548,0 days 01:13:00
17157,58027,565,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,14:46,QP3088,firstClass,Akasa Air,8325.52,998.106548,0 days 01:13:00

In [107]:
df_filtered["Departure_date"] = pd.to_datetime(df_filtered["Departure_date"])
df_filtered["Departure_timee"] = pd.to_timedelta(df_filtered["Departure_time"] + ":00")
# df_filtered["EstimatedDuration_HHmm"] = pd.to_timedelta(df_filtered["EstimatedDuration_HHMM"] + ":00") 
# df_filtered["Arrival_Date"] = df_filtered["Departure_date"] + df_filtered["Departure_timee"] + df_filtered["EstimatedDuration_HHMM"]

In [89]:
df_filtered

,travelCode,User_ID,Departure,Arrival,Departure_date,Departure_time,flight_number,flightType,Flight_agency,Calculated_Flight_Price,Flight_Distance,EstimatedDuration_HHMM,Departure_timee,Arrival_Date
0,0,0,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,03:59,G84279,firstClass,GoAir,4810.84,998.106548,0 days 01:13:00,0 days 03:59:00,2025-04-29
7988,26772,258,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,16:13,AI4771,firstClass,Air India,6142.60,998.106548,0 days 01:13:00,0 days 16:13:00,2025-04-29
12276,41362,401,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,12:07,QP1417,economic,Akasa Air,1080.62,998.106548,0 days 01:13:00,0 days 12:07:00,2025-04-29
14101,47487,461,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,07:17,6E1768,premium,IndiGo,18190.65,998.106548,0 days 01:13:00,0 days 07:17:00,2025-04-29
14348,48391,474,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,09:54,QP1439,economic,Akasa Air,3632.50,998.106548,0 days 01:13:00,0 days 09:54:00,2025-04-29
14458,48785,478,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,21:55,G83989,firstClass,GoAir,6342.36,998.106548,0 days 01:13:00,0 days 21:55:00,2025-04-29
14833,50037,488,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,15:37,QP3560,economic,Akasa Air,3459.32,998.106548,0 days 01:13:00,0 days 15:37:00,2025-04-29
15202,51353,500,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,17:49,AI5035Q,premium,Air India,5328.31,998.106548,0 days 01:13:00,0 days 17:49:00,2025-04-29
17157,58027,565,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,14:46,QP3088,firstClass,Akasa Air,8325.52,998.106548,0 days 01:13:00,0 days 14:46:00,2025-04-29

In [88]:
df_filtered["Arrival_Date"] = df_filtered["Arrival_Date"].dt.strftime('%Y-%m-%d')

In [109]:
df_filtered = df_filtered.drop(columns={'Departure_timee'})

In [103]:
df

,travelCode,User_ID,Departure,Arrival,Departure_date,Departure_time,Arrival_time,flight_number,flightType,Flight_agency,Distance_km,EstimatedDuration_HHMM,Calculated_Flight_Price,Arrival_Date
0,0,0,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-03-05,03:59,05:12,G84279,firstClass,GoAir,998.106548,01:13,4810.84,2025-03-05
1,2,0,Birsa Munda Airport (IXR),Shillong Airport (SHL),2025-03-21,01:02,01:54,6E4357O,firstClass,IndiGo,723.904020,00:52,3580.20,2025-03-21
2,7,0,Goa International Airport (GOI),Birsa Munda Airport (IXR),2025-04-11,00:15,02:01,AI3905,economic,Air India,1492.553600,01:46,3785.16,2025-04-11
3,11,0,Sardar Vallabhbhai Patel International Airport...,Raigarh Airport (None),2025-04-26,17:35,18:56,SG2659K,premium,SpiceJet,1110.753989,01:21,3669.93,2025-04-26
4,13,0,Rajiv Gandhi International Airport (HYD),Netaji Subhas Chandra Bose International Airpo...,2025-03-20,18:18,19:46,G83184,firstClass,GoAir,1207.676138,01:28,5780.44,2025-03-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,Devi Ahilya Bai Holkar Airport (IDR),Goa International Airport (GOI),2025-03-29,04:28,05:28,AI5405C,premium,Air India,842.052913,01:00,2949.67,2025-03-29
39975,135939,1339,Sardar Vallabhbhai Patel International Airport...,Shillong Airport (SHL),2025-03-09,13:37,16:01,QP2071,premium,Akasa Air,1978.782106,02:24,5988.03,2025-03-09
39976,135940,1339,Prayagraj Airport (IXD),Visakhapatnam Airport (VTZ),2025-04-29,17:27,18:30,QP589J,firstClass,Akasa Air,871.997188,01:03,4272.88,2025-04-29
39977,135941,1339,Surat Airport (STV),Goa International Airport (GOI),2025-03-22,00:46,01:32,6E4801N,firstClass,IndiGo,647.800512,00:46,3349.72,2025-03-22
39978,135942,1339,Raja Bhoj Airport (BHO),Prayagraj Airport (IXD),2025-03-23,12:14,12:50,6E4290X,economic,IndiGo,505.527757,00:36,1673.92,2025-03-23

In [104]:
df_filtered

,travelCode,User_ID,Departure,Arrival,Departure_date,Departure_time,flight_number,flightType,Flight_agency,Calculated_Flight_Price,Flight_Distance,EstimatedDuration_HHMM,Arrival_Date
0,0,0,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,03:59,G84279,firstClass,GoAir,4810.84,998.106548,0 days 01:13:00,2025-04-29
7988,26772,258,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,16:13,AI4771,firstClass,Air India,6142.60,998.106548,0 days 01:13:00,2025-04-29
12276,41362,401,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,12:07,QP1417,economic,Akasa Air,1080.62,998.106548,0 days 01:13:00,2025-04-29
14101,47487,461,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,07:17,6E1768,premium,IndiGo,18190.65,998.106548,0 days 01:13:00,2025-04-29
14348,48391,474,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,09:54,QP1439,economic,Akasa Air,3632.50,998.106548,0 days 01:13:00,2025-04-29
14458,48785,478,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,21:55,G83989,firstClass,GoAir,6342.36,998.106548,0 days 01:13:00,2025-04-29
14833,50037,488,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,15:37,QP3560,economic,Akasa Air,3459.32,998.106548,0 days 01:13:00,2025-04-29
15202,51353,500,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,17:49,AI5035Q,premium,Air India,5328.31,998.106548,0 days 01:13:00,2025-04-29
17157,58027,565,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,14:46,QP3088,firstClass,Akasa Air,8325.52,998.106548,0 days 01:13:00,2025-04-29

In [108]:
df_filtered['Arrival_time'] = df_filtered["Departure_timee"] + df_filtered["EstimatedDuration_HHMM"]
df_filtered

,travelCode,User_ID,Departure,Arrival,Departure_date,Departure_time,flight_number,flightType,Flight_agency,Calculated_Flight_Price,Flight_Distance,EstimatedDuration_HHMM,Arrival_Date,Departure_timee,Arrival_time
0,0,0,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,03:59,G84279,firstClass,GoAir,4810.84,998.106548,0 days 01:13:00,2025-04-29,0 days 03:59:00,0 days 05:12:00
7988,26772,258,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,16:13,AI4771,firstClass,Air India,6142.60,998.106548,0 days 01:13:00,2025-04-29,0 days 16:13:00,0 days 17:26:00
12276,41362,401,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,12:07,QP1417,economic,Akasa Air,1080.62,998.106548,0 days 01:13:00,2025-04-29,0 days 12:07:00,0 days 13:20:00
14101,47487,461,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,07:17,6E1768,premium,IndiGo,18190.65,998.106548,0 days 01:13:00,2025-04-29,0 days 07:17:00,0 days 08:30:00
14348,48391,474,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,09:54,QP1439,economic,Akasa Air,3632.50,998.106548,0 days 01:13:00,2025-04-29,0 days 09:54:00,0 days 11:07:00
14458,48785,478,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,21:55,G83989,firstClass,GoAir,6342.36,998.106548,0 days 01:13:00,2025-04-29,0 days 21:55:00,0 days 23:08:00
14833,50037,488,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,15:37,QP3560,economic,Akasa Air,3459.32,998.106548,0 days 01:13:00,2025-04-29,0 days 15:37:00,0 days 16:50:00
15202,51353,500,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,17:49,AI5035Q,premium,Air India,5328.31,998.106548,0 days 01:13:00,2025-04-29,0 days 17:49:00,0 days 19:02:00
17157,58027,565,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,14:46,QP3088,firstClass,Akasa Air,8325.52,998.106548,0 days 01:13:00,2025-04-29,0 days 14:46:00,0 days 15:59:00

In [111]:
df_filtered['Arrival_time'] = pd.to_timedelta(df_filtered['Arrival_time'])

# Convert timedelta to HH:MM format
df_filtered['Arrival_time'] = df_filtered['Arrival_time'].dt.components.apply(
    lambda x: f"{x.hours:02}:{x.minutes:02}", axis=1
)

In [112]:
df_filtered

,travelCode,User_ID,Departure,Arrival,Departure_date,Departure_time,flight_number,flightType,Flight_agency,Calculated_Flight_Price,Flight_Distance,EstimatedDuration_HHMM,Arrival_Date,Arrival_time
0,0,0,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,03:59,G84279,firstClass,GoAir,4810.84,998.106548,0 days 01:13:00,2025-04-29,05:12
7988,26772,258,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,16:13,AI4771,firstClass,Air India,6142.60,998.106548,0 days 01:13:00,2025-04-29,17:26
12276,41362,401,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,12:07,QP1417,economic,Akasa Air,1080.62,998.106548,0 days 01:13:00,2025-04-29,13:20
14101,47487,461,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,07:17,6E1768,premium,IndiGo,18190.65,998.106548,0 days 01:13:00,2025-04-29,08:30
14348,48391,474,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,09:54,QP1439,economic,Akasa Air,3632.50,998.106548,0 days 01:13:00,2025-04-29,11:07
14458,48785,478,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,21:55,G83989,firstClass,GoAir,6342.36,998.106548,0 days 01:13:00,2025-04-29,23:08
14833,50037,488,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,15:37,QP3560,economic,Akasa Air,3459.32,998.106548,0 days 01:13:00,2025-04-29,16:50
15202,51353,500,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,17:49,AI5035Q,premium,Air India,5328.31,998.106548,0 days 01:13:00,2025-04-29,19:02
17157,58027,565,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,14:46,QP3088,firstClass,Akasa Air,8325.52,998.106548,0 days 01:13:00,2025-04-29,15:59

In [153]:
df = df.rename(columns={'Distance_km':'Flight_Distance'})

In [154]:
df

,travelCode,User_ID,Departure,Arrival,Departure_date,Departure_time,Arrival_Date,Arrival_time,flight_number,flightType,Flight_agency,Flight_Distance,EstimatedDuration_HHMM,Calculated_Flight_Price
19989,67875,658,Rajiv Gandhi International Airport (HYD),Coimbatore International Airport (CJB),2021-01-21 20:46:00,20:46,2021-01-21 21:37:00,21:37,SG1165T,premium,SpiceJet,705.554763,00:51,2804.32
19990,67876,658,Rajiv Gandhi International Airport (HYD),Lokpriya Gopinath Bordoloi International Airpo...,2021-01-28 11:36:00,11:36,2021-01-28 13:37:00,13:37,6E4506,premium,IndiGo,1677.957207,02:01,5195.24
19991,67879,658,Chhatrapati Shivaji Maharaj International Airp...,Rupsi Airport (RUP),2021-02-18 10:55:00,10:55,2021-02-18 13:15:00,13:15,SG4812,premium,SpiceJet,1914.316454,02:20,5822.44
19992,67880,658,Pune International Airport (PNQ),Biju Patnaik International Airport (BBI),2021-02-25 10:54:00,10:54,2021-02-25 12:27:00,12:27,AI5344,economic,Air India,1304.465724,01:33,3318.14
19993,67885,658,Lokpriya Gopinath Bordoloi International Airpo...,Sheikh ul-Alam International Airport (SXR),2021-01-04 12:03:00,12:03,2021-01-04 14:19:00,14:19,I5353,firstClass,AirAsia India,1836.680899,02:16,8358.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,Devi Ahilya Bai Holkar Airport (IDR),Goa International Airport (GOI),2020-06-18 04:28:00,04:28,2020-06-18 05:28:00,05:28,AI5405C,premium,Air India,842.052913,01:00,2949.67
39975,135939,1339,Sardar Vallabhbhai Patel International Airport...,Shillong Airport (SHL),2020-06-25 13:37:00,13:37,2020-06-25 16:01:00,16:01,QP2071,premium,Akasa Air,1978.782106,02:24,5988.03
39976,135940,1339,Prayagraj Airport (IXD),Visakhapatnam Airport (VTZ),2020-02-07 17:27:00,17:27,2020-02-07 18:30:00,18:30,QP589J,firstClass,Akasa Air,871.997188,01:03,4272.88
39977,135941,1339,Surat Airport (STV),Goa International Airport (GOI),2020-09-07 00:46:00,00:46,2020-09-07 01:32:00,01:32,6E4801N,firstClass,IndiGo,647.800512,00:46,3349.72
39978,135942,1339,Raja Bhoj Airport (BHO),Prayagraj Airport (IXD),2020-07-16 12:14:00,12:14,2020-07-16 12:50:00,12:50,6E4290X,economic,IndiGo,505.527757,00:36,1673.92

In [176]:
df0 = pd.concat([df_filtered, df], ignore_index=True)

In [155]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 17157
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   travelCode               9 non-null      int64
 1   User_ID                  9 non-null      int64
 2   Departure                9 non-null      object
 3   Arrival                  9 non-null      object
 4   Departure_date           9 non-null      object
 5   Departure_time           9 non-null      object
 6   flight_number            9 non-null      object
 7   flightType               9 non-null      object
 8   Flight_agency            9 non-null      object
 9   Calculated_Flight_Price  9 non-null      float64
 10  Flight_Distance          9 non-null      float64
 11  EstimatedDuration_HHMM   9 non-null      object
 12  Arrival_Date             9 non-null      object
 13  Arrival_time             9 non-null      object
dtypes: float64(2), int64(2), object(10)
memory usage: 1.1+ KB

In [179]:
df0.to_excel('Frontendd.xlsx', index=False)
from IPython.display import FileLink
FileLink('Frontendd.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\Frontendd.xlsx

In [169]:
df['Departure_date'] = df['Departure_date'].dt.strftime('%Y-%m-%d')
df['Arrival_Date'] = df['Arrival_Date'].dt.strftime('%Y-%m-%d')

In [172]:
df__

,travelCode,User_ID,Departure,Arrival,Departure_date,Departure_time,flight_number,flightType,Flight_agency,Calculated_Flight_Price,Flight_Distance,EstimatedDuration_HHMM,Arrival_Date,Arrival_time,Distance_km
0,0,0,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,03:59,G84279,firstClass,GoAir,4810.84,998.106548,01:13,2025-04-29,05:12,NaN
1,26772,258,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,16:13,AI4771,firstClass,Air India,6142.60,998.106548,01:13,2025-04-29,17:26,NaN
2,41362,401,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,12:07,QP1417,economic,Akasa Air,1080.62,998.106548,01:13,2025-04-29,13:20,NaN
3,47487,461,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,07:17,6E1768,premium,IndiGo,18190.65,998.106548,01:13,2025-04-29,08:30,NaN
4,48391,474,Coimbatore International Airport (CJB),Visakhapatnam Airport (VTZ),2025-04-29,09:54,QP1439,economic,Akasa Air,3632.50,998.106548,01:13,2025-04-29,11:07,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,135938,1339,Devi Ahilya Bai Holkar Airport (IDR),Goa International Airport (GOI),2020-06-18,04:28,AI5405C,premium,Air India,2949.67,NaN,01:00,2020-06-18,05:28,842.052913
19995,135939,1339,Sardar Vallabhbhai Patel International Airport...,Shillong Airport (SHL),2020-06-25,13:37,QP2071,premium,Akasa Air,5988.03,NaN,02:24,2020-06-25,16:01,1978.782106
19996,135940,1339,Prayagraj Airport (IXD),Visakhapatnam Airport (VTZ),2020-02-07,17:27,QP589J,firstClass,Akasa Air,4272.88,NaN,01:03,2020-02-07,18:30,871.997188
19997,135941,1339,Surat Airport (STV),Goa International Airport (GOI),2020-09-07,00:46,6E4801N,firstClass,IndiGo,3349.72,NaN,00:46,2020-09-07,01:32,647.800512
19998,135942,1339,Raja Bhoj Airport (BHO),Prayagraj Airport (IXD),2020-07-16,12:14,6E4290X,economic,IndiGo,1673.92,NaN,00:36,2020-07-16,12:50,505.527757

In [137]:
df['EstimatedDuration_HHMM'] = df['EstimatedDuration_HHMM'].dt.components.apply(
    lambda x: f"{x.hours:02}:{x.minutes:02}", axis=1
)

In [158]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19990 entries, 19989 to 39978
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   travelCode               19990 non-null  int64
 1   User_ID                  19990 non-null  int64
 2   Departure                19990 non-null  object
 3   Arrival                  19990 non-null  object
 4   Departure_date           19990 non-null  object
 5   Departure_time           19990 non-null  object
 6   Arrival_Date             19990 non-null  object
 7   Arrival_time             19990 non-null  object
 8   flight_number            19990 non-null  object
 9   flightType               19990 non-null  object
 10  Flight_agency            19990 non-null  object
 11  Flight_Distance          19990 non-null  float64
 12  EstimatedDuration_HHMM   19990 non-null  object
 13  Calculated_Flight_Price  19990 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.1+ MB

In [162]:
df

,travelCode,User_ID,Departure,Arrival,Departure_date,Departure_time,Arrival_Date,Arrival_time,flight_number,flightType,Flight_agency,Flight_Distance,EstimatedDuration_HHMM,Calculated_Flight_Price
19989,67875,658,Rajiv Gandhi International Airport (HYD),Coimbatore International Airport (CJB),2021-01-21 20:46:00,20:46,2021-01-21 21:37:00,21:37,SG1165T,premium,SpiceJet,705.554763,00:51,2804.32
19990,67876,658,Rajiv Gandhi International Airport (HYD),Lokpriya Gopinath Bordoloi International Airpo...,2021-01-28 11:36:00,11:36,2021-01-28 13:37:00,13:37,6E4506,premium,IndiGo,1677.957207,02:01,5195.24
19991,67879,658,Chhatrapati Shivaji Maharaj International Airp...,Rupsi Airport (RUP),2021-02-18 10:55:00,10:55,2021-02-18 13:15:00,13:15,SG4812,premium,SpiceJet,1914.316454,02:20,5822.44
19992,67880,658,Pune International Airport (PNQ),Biju Patnaik International Airport (BBI),2021-02-25 10:54:00,10:54,2021-02-25 12:27:00,12:27,AI5344,economic,Air India,1304.465724,01:33,3318.14
19993,67885,658,Lokpriya Gopinath Bordoloi International Airpo...,Sheikh ul-Alam International Airport (SXR),2021-01-04 12:03:00,12:03,2021-01-04 14:19:00,14:19,I5353,firstClass,AirAsia India,1836.680899,02:16,8358.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,Devi Ahilya Bai Holkar Airport (IDR),Goa International Airport (GOI),2020-06-18 04:28:00,04:28,2020-06-18 05:28:00,05:28,AI5405C,premium,Air India,842.052913,01:00,2949.67
39975,135939,1339,Sardar Vallabhbhai Patel International Airport...,Shillong Airport (SHL),2020-06-25 13:37:00,13:37,2020-06-25 16:01:00,16:01,QP2071,premium,Akasa Air,1978.782106,02:24,5988.03
39976,135940,1339,Prayagraj Airport (IXD),Visakhapatnam Airport (VTZ),2020-02-07 17:27:00,17:27,2020-02-07 18:30:00,18:30,QP589J,firstClass,Akasa Air,871.997188,01:03,4272.88
39977,135941,1339,Surat Airport (STV),Goa International Airport (GOI),2020-09-07 00:46:00,00:46,2020-09-07 01:32:00,01:32,6E4801N,firstClass,IndiGo,647.800512,00:46,3349.72
39978,135942,1339,Raja Bhoj Airport (BHO),Prayagraj Airport (IXD),2020-07-16 12:14:00,12:14,2020-07-16 12:50:00,12:50,6E4290X,economic,IndiGo,505.527757,00:36,1673.92

In [170]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19990 entries, 19989 to 39978
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   travelCode               19990 non-null  int64
 1   User_ID                  19990 non-null  int64
 2   Departure                19990 non-null  object
 3   Arrival                  19990 non-null  object
 4   Departure_date           19990 non-null  object
 5   Departure_time           19990 non-null  object
 6   Arrival_Date             19990 non-null  object
 7   Arrival_time             19990 non-null  object
 8   flight_number            19990 non-null  object
 9   flightType               19990 non-null  object
 10  Flight_agency            19990 non-null  object
 11  Distance_km              19990 non-null  float64
 12  EstimatedDuration_HHMM   19990 non-null  object
 13  Calculated_Flight_Price  19990 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.1+ MB

In [173]:
df__.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19999 entries, 0 to 19998
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   travelCode               19999 non-null  int64
 1   User_ID                  19999 non-null  int64
 2   Departure                19999 non-null  object
 3   Arrival                  19999 non-null  object
 4   Departure_date           19999 non-null  object
 5   Departure_time           19999 non-null  object
 6   flight_number            19999 non-null  object
 7   flightType               19999 non-null  object
 8   Flight_agency            19999 non-null  object
 9   Calculated_Flight_Price  19999 non-null  float64
 10  Flight_Distance          9 non-null      float64
 11  EstimatedDuration_HHMM   19999 non-null  object
 12  Arrival_Date             19999 non-null  object
 13  Arrival_time             19999 non-null  object
 14  Distance_km              19990 non-null  float64
dtypes: float64(3), int64(2), object(10)
memory usage: 2.3+ MB

In [175]:
df = df.rename(columns={'Distance_km':'Flight_Distance'})

In [178]:
df0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19999 entries, 0 to 19998
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   travelCode               19999 non-null  int64
 1   User_ID                  19999 non-null  int64
 2   Departure                19999 non-null  object
 3   Arrival                  19999 non-null  object
 4   Departure_date           19999 non-null  object
 5   Departure_time           19999 non-null  object
 6   flight_number            19999 non-null  object
 7   flightType               19999 non-null  object
 8   Flight_agency            19999 non-null  object
 9   Calculated_Flight_Price  19999 non-null  float64
 10  Flight_Distance          19999 non-null  float64
 11  EstimatedDuration_HHMM   19999 non-null  object
 12  Arrival_Date             19999 non-null  object
 13  Arrival_time             19999 non-null  object
dtypes: float64(2), int64(2), object(10)
memory usage: 2.1+ MB