In [1]:
import pandas as pd
import numpy as np

In [2]:
cities_name=['Tirupati','Visakhapatnam','Vijayawada','Itanagar','Dhubri','Guwahati','Patna','Raipur','Bilaspur','Raigarh','Mopa','Dabolim','Ahmedabad','Surat','Vadodara','Hisar','Shimla','Kullu-Manali','Jamshedpur','Ranchi','Bengaluru','Mysuru','Thiruvananthapuram','Gwalior','Indore','Bhopal','Mumbai','Navi Mumbai','Nashik','Pune','Imphal','Shillong','Puri','Bhubaneswar','Ludhiana','Amritsar','Jaipur','Udaipur','Kota','Gangtok','Coimbatore','Chennai','Hyderabad','Khowai','Ayodhya','Varanasi','Prayagraj','Dehradun','Kolkata','Delhi NCR','Chandigarh',
            'Puducherry','Diu','Srinagar']

In [3]:
len(cities_name)

54

In [4]:
df = pd.read_excel("FlightFINALdataset.xlsx")
df

,travelCode,User_ID,Departure,Arrival,flightType,Flight_price,Flight_duration,Flight_Distance,Flight_agency,Departure_date
0,0,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,26/09/2019
1,2,0,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019
2,7,0,Aracaju (SE),Salvador (BH),economic,964.83,2.16,830.86,CloudFy,14/11/2019
3,11,0,Brasilia (DF),Salvador (BH),premium,1268.97,1.76,676.56,Rainbow,12/12/2019
4,13,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,26/12/2019
...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,Florianopolis (SC),Brasilia (DF),premium,885.37,1.66,637.56,CloudFy,18/06/2020
40548,135939,1339,Florianopolis (SC),Brasilia (DF),premium,814.55,1.66,637.56,Rainbow,25/06/2020
40549,135940,1339,Florianopolis (SC),Campo Grande (MS),firstClass,857.32,1.49,573.81,Rainbow,07/02/2020
40550,135941,1339,Florianopolis (SC),Campo Grande (MS),firstClass,949.58,1.49,573.81,CloudFy,07/09/2020
40551,135942,1339,Florianopolis (SC),Natal (RN),economic,726.95,1.84,709.37,CloudFy,16/07/2020

In [5]:
num_entries = len(df)
data = []

In [6]:
df = df.drop(columns={'Departure','Arrival'})

In [8]:
import random 
for _ in range(num_entries):
    departure = random.choice(cities_name)
    arrival = random.choice([city for city in cities_name if city != departure])
    data.append((departure, arrival))

In [10]:
df_new = pd.DataFrame(data, columns=["Departure", "Arrival"])
df

,travelCode,User_ID,flightType,Flight_price,Flight_duration,Flight_Distance,Flight_agency,Departure_date
0,0,0,firstClass,1434.38,1.76,676.53,FlyingDrops,26/09/2019
1,2,0,firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019
2,7,0,economic,964.83,2.16,830.86,CloudFy,14/11/2019
3,11,0,premium,1268.97,1.76,676.56,Rainbow,12/12/2019
4,13,0,firstClass,1434.38,1.76,676.53,FlyingDrops,26/12/2019
...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,885.37,1.66,637.56,CloudFy,18/06/2020
40548,135939,1339,premium,814.55,1.66,637.56,Rainbow,25/06/2020
40549,135940,1339,firstClass,857.32,1.49,573.81,Rainbow,07/02/2020
40550,135941,1339,firstClass,949.58,1.49,573.81,CloudFy,07/09/2020
40551,135942,1339,economic,726.95,1.84,709.37,CloudFy,16/07/2020

In [11]:
df_new

        Departure        Arrival
0      Coimbatore  Visakhapatnam
1          Ranchi       Shillong
2         Dabolim         Ranchi
3       Ahmedabad        Raigarh
4       Hyderabad        Kolkata
...           ...            ...
40547      Indore        Dabolim
40548   Ahmedabad       Shillong
40549   Prayagraj  Visakhapatnam
40550       Surat        Dabolim
40551      Bhopal      Prayagraj

[40552 rows x 2 columns]

In [12]:
import requests
import math

def get_city_coordinates(city_name):
    """Fetches the coordinates of a given city using the GeoNames API."""
    username = 'tisha_agrawal_08'  # Replace with your GeoNames username
    url = f'http://api.geonames.org/searchJSON?q={city_name}&maxRows=1&username={username}'
    
    response = requests.get(url)
    
    if response.status_code == 200:
        data = response.json()
        if data['totalResultsCount'] > 0:
            city = data['geonames'][0]
            latitude = float(city['lat'])
            longitude = float(city['lng'])
            print(f"Coordinates of {city_name}: {latitude}, {longitude}")
            return latitude, longitude
        else:
            print(f"Could not find coordinates for {city_name}.")
    else:
        print(f"Error fetching city data: {response.status_code}")
    
    return None, None

def haversine(lat1, lon1, lat2, lon2):
    """Calculates the great-circle distance between two points using the Haversine formula."""
    R = 6371  # Radius of Earth in km
    
    # Convert degrees to radians
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    
    # Haversine formula
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
    c = 2 * math.asin(math.sqrt(a))
    
    return R * c  # Distance in km

def calculate_flight_duration(distance, speed=250):
    """Calculates estimated flight duration in hours (default speed: 900 km/h)."""
    duration = distance / speed  # Time = Distance / Speed
    hours = int(duration)
    minutes = int((duration - hours) * 60)
    return hours, minutes

In [13]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40552 entries, 0 to 40551
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Departure  40552 non-null  object
 1   Arrival    40552 non-null  object
dtypes: object(2)
memory usage: 633.8+ KB

In [18]:
df_new['Departure'].unique()

array(['Coimbatore', 'Ranchi', 'Dabolim', 'Ahmedabad', 'Hyderabad',
       'Khowai', 'Navi Mumbai', 'Pune', 'Vijayawada', 'Gwalior',
       'Bengaluru', 'Guwahati', 'Bilaspur', 'Raipur', 'Puducherry',
       'Jamshedpur', 'Nashik', 'Mopa', 'Prayagraj', 'Vadodara',
       'Ludhiana', 'Raigarh', 'Chennai', 'Puri', 'Tirupati', 'Dehradun',
       'Srinagar', 'Delhi NCR', 'Itanagar', 'Varanasi', 'Dhubri',
       'Kolkata', 'Gangtok', 'Shillong', 'Amritsar', 'Bhopal', 'Jaipur',
       'Kullu-Manali', 'Ayodhya', 'Bhubaneswar', 'Thiruvananthapuram',
       'Kota', 'Surat', 'Udaipur', 'Diu', 'Chandigarh', 'Shimla',
       'Imphal', 'Hisar', 'Visakhapatnam', 'Indore', 'Mysuru', 'Patna',
       'Mumbai'], dtype=object)

In [30]:
for row in df_new['Departure'].unique():
#     print(get_city_coordinates(row))
    df_coordinates = get_city_coordinates(row)
df_coordinates

Coordinates of Coimbatore: 11.00555, 76.96612
Coordinates of Ranchi: 23.34316, 85.3094
Coordinates of Dabolim: 15.38083, 73.83142
Coordinates of Ahmedabad: 23.02579, 72.58727
Coordinates of Hyderabad: 17.38405, 78.45636
Coordinates of Khowai: 24.0619, 91.6039
Coordinates of Navi Mumbai: 19.03681, 73.01582
Coordinates of Pune: 18.51957, 73.85535
Coordinates of Vijayawada: 16.50745, 80.6466
Coordinates of Gwalior: 26.22983, 78.17337
Coordinates of Bengaluru: 12.97194, 77.59369
Coordinates of Guwahati: 26.1844, 91.7458
Coordinates of Bilaspur: 22.08005, 82.15543
Coordinates of Raipur: 21.23333, 81.63333
Coordinates of Puducherry: 11.93381, 79.82979
Coordinates of Jamshedpur: 22.80278, 86.18545
Coordinates of Nashik: 19.99727, 73.79096
Coordinates of Mopa: 8.10332, 5.87847
Coordinates of Prayagraj: 25.44478, 81.84322
Coordinates of Vadodara: 22.29941, 73.20812
Coordinates of Ludhiana: 30.91204, 75.85379
Coordinates of Raigarh: 21.89764, 83.3966
Coordinates of Chennai: 13.08784, 80.27847
Coordinates of Puri: 19.79825, 85.82494
Coordinates of Tirupati: 13.63551, 79.41989
Coordinates of Dehradun: 30.32443, 78.03392
Coordinates of Srinagar: 34.08565, 74.80555
Coordinates of Delhi NCR: 28.66047, 77.07733
Coordinates of Itanagar: 27.08694, 93.60987
Coordinates of Varanasi: 25.31668, 83.01041
Coordinates of Dhubri: 26.01856, 89.98564
Coordinates of Kolkata: 22.56263, 88.36304
Coordinates of Gangtok: 27.32574, 88.61216
Coordinates of Shillong: 25.56892, 91.88313
Coordinates of Amritsar: 31.62234, 74.87534
Coordinates of Bhopal: 23.25469, 77.40289
Coordinates of Jaipur: 26.91962, 75.78781
Coordinates of Kullu-Manali: 31.8767, 77.1544
Coordinates of Ayodhya: 26.79909, 82.2047
Coordinates of Bhubaneswar: 20.27241, 85.83385
Coordinates of Thiruvananthapuram: 8.4855, 76.94924
Coordinates of Kota: 25.5, 51.25
Coordinates of Surat: 21.19594, 72.83023
Coordinates of Udaipur: 24.58584, 73.71346
Coordinates of Diu: 20.71405, 70.98224
Coordinates of Chandigarh: 30.73629, 76.7884
Coordinates of Shimla: 31.10442, 77.16662
Coordinates of Imphal: 24.80805, 93.9442
Coordinates of Hisar: 41.28083, 21.14389
Coordinates of Visakhapatnam: 17.68009, 83.20161
Coordinates of Indore: 22.71792, 75.8333
Coordinates of Mysuru: 12.29791, 76.63925
Coordinates of Patna: 25.59408, 85.13563
Coordinates of Mumbai: 19.07283, 72.88261

(19.07283, 72.88261)

In [24]:
df_new['Arrival'].unique()

array(['Visakhapatnam', 'Shillong', 'Ranchi', 'Raigarh', 'Kolkata',
       'Amritsar', 'Pune', 'Mumbai', 'Raipur', 'Srinagar', 'Delhi NCR',
       'Ludhiana', 'Indore', 'Khowai', 'Gwalior', 'Ahmedabad',
       'Prayagraj', 'Dhubri', 'Chandigarh', 'Puri', 'Kullu-Manali',
       'Mysuru', 'Surat', 'Shimla', 'Guwahati', 'Puducherry', 'Varanasi',
       'Hyderabad', 'Mopa', 'Diu', 'Bengaluru', 'Gangtok', 'Udaipur',
       'Kota', 'Jaipur', 'Thiruvananthapuram', 'Bhubaneswar', 'Dabolim',
       'Vadodara', 'Ayodhya', 'Dehradun', 'Coimbatore', 'Nashik', 'Patna',
       'Jamshedpur', 'Imphal', 'Navi Mumbai', 'Vijayawada', 'Itanagar',
       'Bilaspur', 'Tirupati', 'Hisar', 'Bhopal', 'Chennai'], dtype=object)

In [26]:
df_new.to_excel('place_India.xlsx',index=False)
from IPython.display import FileLink
FileLink('place_India.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\place_India.xlsx

In [37]:
import pandas as pd
import math
from itertools import combinations

# Function to calculate Haversine distance
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Radius of Earth in km
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
    c = 2 * math.asin(math.sqrt(a))
    return R * c  # Distance in km

# Function to calculate estimated flight duration
def calculate_flight_duration(distance, speed=900):
    duration = distance / speed  # Time = Distance / Speed
    hours = int(duration)
    minutes = int((duration - hours) * 60)
    return f"{hours:02d}:{minutes:02d}"  # Format hh:mm

# Creating a DataFrame from your given data
data = [
    ("Coimbatore", 11.00555, 76.96612),
    ("Ranchi", 23.34316, 85.30940),
    ("Dabolim", 15.38083, 73.83142),
    ("Ahmedabad", 23.02579, 72.58727),
    ("Hyderabad", 17.38405, 78.45636),
    ("Khowai", 24.06190, 91.60390),
    ("Navi Mumbai", 19.03681, 73.01582),
    ("Pune", 18.51957, 73.85535),
    ("Vijayawada", 16.50745, 80.64660),
    ("Gwalior", 26.22983, 78.17337),
    ("Bengaluru", 12.97194, 77.59369),
    ("Guwahati", 26.18440, 91.74580),
    ("Bilaspur", 22.08005, 82.15543),
    ("Raipur", 21.23333, 81.63333),
    ("Puducherry", 11.93381, 79.82979),
    ("Jamshedpur", 22.80278, 86.18545),
    ("Nashik", 19.99727, 73.79096),
    ("Mopa", 8.10332, 5.87847),
    ("Prayagraj", 25.44478, 81.84322),
    ("Vadodara", 22.29941, 73.20812),
    ("Ludhiana", 30.91204, 75.85379),
    ("Raigarh", 21.89764, 83.39660),
    ("Chennai", 13.08784, 80.27847),
    ("Puri", 19.79825, 85.82494),
    ("Tirupati", 13.63551, 79.41989),
    ("Dehradun", 30.32443, 78.03392),
    ("Srinagar", 34.08565, 74.80555),
    ("Delhi NCR", 28.66047, 77.07733),
    ("Itanagar", 27.08694, 93.60987),
    ("Varanasi", 25.31668, 83.01041),
    ("Dhubri", 26.01856, 89.98564),
    ("Kolkata", 22.56263, 88.36304),
    ("Gangtok", 27.32574, 88.61216),
    ("Shillong", 25.56892, 91.88313),
    ("Amritsar", 31.62234, 74.87534),
    ("Bhopal", 23.25469, 77.40289),
    ("Jaipur", 26.91962, 75.78781),
    ("Kullu-Manali", 31.87670, 77.15440),
    ("Ayodhya", 26.79909, 82.20470),
    ("Bhubaneswar", 20.27241, 85.83385),
    ("Thiruvananthapuram", 8.48550, 76.94924),
    ("Kota", 25.50000, 51.25000),
    ("Surat", 21.19594, 72.83023),
    ("Udaipur", 24.58584, 73.71346),
    ("Diu", 20.71405, 70.98224),
    ("Chandigarh", 30.73629, 76.78840),
    ("Shimla", 31.10442, 77.16662),
    ("Imphal", 24.80805, 93.94420),
    ("Hisar", 41.28083, 21.14389),
    ("Visakhapatnam", 17.68009, 83.20161),
    ("Indore", 22.71792, 75.83330),
    ("Mysuru", 12.29791, 76.63925),
    ("Patna", 25.59408, 85.13563),
    ("Mumbai", 19.07283, 72.88261)
]

df = pd.DataFrame(data, columns=["city_name", "latitude", "longitude"])

# Generate all possible city pairs
city_pairs = list(combinations(df.itertuples(index=False), 2))

# Calculate distances and durations
distance_data = []

for city1, city2 in city_pairs:
    distance = haversine(city1.latitude, city1.longitude, city2.latitude, city2.longitude)
    duration = calculate_flight_duration(distance)
    
    distance_data.append({
        "Source City": city1.city_name,
        "Destination City": city2.city_name,
        "Source Latitude": city1.latitude,
        "Source Longitude": city1.longitude,
        "Destination Latitude": city2.latitude,
        "Destination Longitude": city2.longitude,
        "Flight Distance (km)": round(distance, 2),
        "Flight Duration (hh:mm)": duration
    })

# Convert to DataFrame
df_neww = pd.DataFrame(distance_data)

# Display the first few rows
df_neww

,Source City,Destination City,Source Latitude,Source Longitude,Destination Latitude,Destination Longitude,Flight Distance (km),Flight Duration (hh:mm)
0,Coimbatore,Ranchi,11.00555,76.96612,23.34316,85.30940,1632.07,01:48
1,Coimbatore,Dabolim,11.00555,76.96612,15.38083,73.83142,593.12,00:39
2,Coimbatore,Ahmedabad,11.00555,76.96612,23.02579,72.58727,1415.00,01:34
3,Coimbatore,Hyderabad,11.00555,76.96612,17.38405,78.45636,727.20,00:48
4,Coimbatore,Khowai,11.00555,76.96612,24.06190,91.60390,2121.73,02:21
...,...,...,...,...,...,...,...,...
1426,Indore,Patna,22.71792,75.83330,25.59408,85.13563,996.20,01:06
1427,Indore,Mumbai,22.71792,75.83330,19.07283,72.88261,508.12,00:33
1428,Mysuru,Patna,12.29791,76.63925,25.59408,85.13563,1726.07,01:55
1429,Mysuru,Mumbai,12.29791,76.63925,19.07283,72.88261,853.82,00:56
1430,Patna,Mumbai,25.59408,85.13563,19.07283,72.88261,1452.80,01:36

In [31]:
import pandas as pd

data = [
    ("Coimbatore", 11.00555, 76.96612),
    ("Ranchi", 23.34316, 85.3094),
    ("Dabolim", 15.38083, 73.83142),
    ("Ahmedabad", 23.02579, 72.58727),
    ("Hyderabad", 17.38405, 78.45636),
    ("Khowai", 24.0619, 91.6039),
    ("Navi Mumbai", 19.03681, 73.01582),
    ("Pune", 18.51957, 73.85535),
    ("Vijayawada", 16.50745, 80.6466),
    ("Gwalior", 26.22983, 78.17337),
    ("Bengaluru", 12.97194, 77.59369),
    ("Guwahati", 26.1844, 91.7458),
    ("Bilaspur", 22.08005, 82.15543),
    ("Raipur", 21.23333, 81.63333),
    ("Puducherry", 11.93381, 79.82979),
    ("Jamshedpur", 22.80278, 86.18545),
    ("Nashik", 19.99727, 73.79096),
    ("Mopa", 8.10332, 5.87847),
    ("Prayagraj", 25.44478, 81.84322),
    ("Vadodara", 22.29941, 73.20812),
    ("Ludhiana", 30.91204, 75.85379),
    ("Raigarh", 21.89764, 83.3966),
    ("Chennai", 13.08784, 80.27847),
    ("Puri", 19.79825, 85.82494),
    ("Tirupati", 13.63551, 79.41989),
    ("Dehradun", 30.32443, 78.03392),
    ("Srinagar", 34.08565, 74.80555),
    ("Delhi NCR", 28.66047, 77.07733),
    ("Itanagar", 27.08694, 93.60987),
    ("Varanasi", 25.31668, 83.01041),
    ("Dhubri", 26.01856, 89.98564),
    ("Kolkata", 22.56263, 88.36304),
    ("Gangtok", 27.32574, 88.61216),
    ("Shillong", 25.56892, 91.88313),
    ("Amritsar", 31.62234, 74.87534),
    ("Bhopal", 23.25469, 77.40289),
    ("Jaipur", 26.91962, 75.78781),
    ("Kullu-Manali", 31.8767, 77.1544),
    ("Ayodhya", 26.79909, 82.2047),
    ("Bhubaneswar", 20.27241, 85.83385),
    ("Thiruvananthapuram", 8.4855, 76.94924),
    ("Kota", 25.5, 51.25),
    ("Surat", 21.19594, 72.83023),
    ("Udaipur", 24.58584, 73.71346),
    ("Diu", 20.71405, 70.98224),
    ("Chandigarh", 30.73629, 76.7884),
    ("Shimla", 31.10442, 77.16662),
    ("Imphal", 24.80805, 93.9442),
    ("Hisar", 41.28083, 21.14389),
    ("Visakhapatnam", 17.68009, 83.20161),
    ("Indore", 22.71792, 75.8333),
    ("Mysuru", 12.29791, 76.63925),
    ("Patna", 25.59408, 85.13563),
    ("Mumbai", 19.07283, 72.88261)
]

df_co = pd.DataFrame(data, columns=["city_name", "latitude", "longitude"])

print(df_co)

             city_name  latitude  longitude
0           Coimbatore  11.00555   76.96612
1               Ranchi  23.34316   85.30940
2              Dabolim  15.38083   73.83142
3            Ahmedabad  23.02579   72.58727
4            Hyderabad  17.38405   78.45636
5               Khowai  24.06190   91.60390
6          Navi Mumbai  19.03681   73.01582
7                 Pune  18.51957   73.85535
8           Vijayawada  16.50745   80.64660
9              Gwalior  26.22983   78.17337
10           Bengaluru  12.97194   77.59369
11            Guwahati  26.18440   91.74580
12            Bilaspur  22.08005   82.15543
13              Raipur  21.23333   81.63333
14          Puducherry  11.93381   79.82979
15          Jamshedpur  22.80278   86.18545
16              Nashik  19.99727   73.79096
17                Mopa   8.10332    5.87847
18           Prayagraj  25.44478   81.84322
19            Vadodara  22.29941   73.20812
20            Ludhiana  30.91204   75.85379
21             Raigarh  21.89764   83.39660
22             Chennai  13.08784   80.27847
23                Puri  19.79825   85.82494
24            Tirupati  13.63551   79.41989
25            Dehradun  30.32443   78.03392
26            Srinagar  34.08565   74.80555
27           Delhi NCR  28.66047   77.07733
28            Itanagar  27.08694   93.60987
29            Varanasi  25.31668   83.01041
30              Dhubri  26.01856   89.98564
31             Kolkata  22.56263   88.36304
32             Gangtok  27.32574   88.61216
33            Shillong  25.56892   91.88313
34            Amritsar  31.62234   74.87534
35              Bhopal  23.25469   77.40289
36              Jaipur  26.91962   75.78781
37        Kullu-Manali  31.87670   77.15440
38             Ayodhya  26.79909   82.20470
39         Bhubaneswar  20.27241   85.83385
40  Thiruvananthapuram   8.48550   76.94924
41                Kota  25.50000   51.25000
42               Surat  21.19594   72.83023
43             Udaipur  24.58584   73.71346
44                 Diu  20.71405   70.98224
45          Chandigarh  30.73629   76.78840
46              Shimla  31.10442   77.16662
47              Imphal  24.80805   93.94420
48               Hisar  41.28083   21.14389
49       Visakhapatnam  17.68009   83.20161
50              Indore  22.71792   75.83330
51              Mysuru  12.29791   76.63925
52               Patna  25.59408   85.13563
53              Mumbai  19.07283   72.88261

In [39]:
df = pd.read_excel("FlightFINALdataset.xlsx")
df

,travelCode,User_ID,Departure,Arrival,flightType,Flight_price,Flight_duration,Flight_Distance,Flight_agency,Departure_date
0,0,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,26/09/2019
1,2,0,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019
2,7,0,Aracaju (SE),Salvador (BH),economic,964.83,2.16,830.86,CloudFy,14/11/2019
3,11,0,Brasilia (DF),Salvador (BH),premium,1268.97,1.76,676.56,Rainbow,12/12/2019
4,13,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,26/12/2019
...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,Florianopolis (SC),Brasilia (DF),premium,885.37,1.66,637.56,CloudFy,18/06/2020
40548,135939,1339,Florianopolis (SC),Brasilia (DF),premium,814.55,1.66,637.56,Rainbow,25/06/2020
40549,135940,1339,Florianopolis (SC),Campo Grande (MS),firstClass,857.32,1.49,573.81,Rainbow,07/02/2020
40550,135941,1339,Florianopolis (SC),Campo Grande (MS),firstClass,949.58,1.49,573.81,CloudFy,07/09/2020
40551,135942,1339,Florianopolis (SC),Natal (RN),economic,726.95,1.84,709.37,CloudFy,16/07/2020

In [42]:
df = df.drop(columns={'Departure','Arrival'})

In [43]:
df

,travelCode,User_ID,flightType,Flight_price,Flight_duration,Flight_Distance,Flight_agency,Departure_date
0,0,0,firstClass,1434.38,1.76,676.53,FlyingDrops,26/09/2019
1,2,0,firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019
2,7,0,economic,964.83,2.16,830.86,CloudFy,14/11/2019
3,11,0,premium,1268.97,1.76,676.56,Rainbow,12/12/2019
4,13,0,firstClass,1434.38,1.76,676.53,FlyingDrops,26/12/2019
...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,885.37,1.66,637.56,CloudFy,18/06/2020
40548,135939,1339,premium,814.55,1.66,637.56,Rainbow,25/06/2020
40549,135940,1339,firstClass,857.32,1.49,573.81,Rainbow,07/02/2020
40550,135941,1339,firstClass,949.58,1.49,573.81,CloudFy,07/09/2020
40551,135942,1339,economic,726.95,1.84,709.37,CloudFy,16/07/2020

In [44]:
df_new

        Departure        Arrival
0      Coimbatore  Visakhapatnam
1          Ranchi       Shillong
2         Dabolim         Ranchi
3       Ahmedabad        Raigarh
4       Hyderabad        Kolkata
...           ...            ...
40547      Indore        Dabolim
40548   Ahmedabad       Shillong
40549   Prayagraj  Visakhapatnam
40550       Surat        Dabolim
40551      Bhopal      Prayagraj

[40552 rows x 2 columns]

In [45]:
df_Flight = pd.concat([df, df_new], axis=1)

In [46]:
df_Flight

,travelCode,User_ID,flightType,Flight_price,Flight_duration,Flight_Distance,Flight_agency,Departure_date,Departure,Arrival
0,0,0,firstClass,1434.38,1.76,676.53,FlyingDrops,26/09/2019,Coimbatore,Visakhapatnam
1,2,0,firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019,Ranchi,Shillong
2,7,0,economic,964.83,2.16,830.86,CloudFy,14/11/2019,Dabolim,Ranchi
3,11,0,premium,1268.97,1.76,676.56,Rainbow,12/12/2019,Ahmedabad,Raigarh
4,13,0,firstClass,1434.38,1.76,676.53,FlyingDrops,26/12/2019,Hyderabad,Kolkata
...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,885.37,1.66,637.56,CloudFy,18/06/2020,Indore,Dabolim
40548,135939,1339,premium,814.55,1.66,637.56,Rainbow,25/06/2020,Ahmedabad,Shillong
40549,135940,1339,firstClass,857.32,1.49,573.81,Rainbow,07/02/2020,Prayagraj,Visakhapatnam
40550,135941,1339,firstClass,949.58,1.49,573.81,CloudFy,07/09/2020,Surat,Dabolim
40551,135942,1339,economic,726.95,1.84,709.37,CloudFy,16/07/2020,Bhopal,Prayagraj

In [48]:
df_neww

,Source City,Destination City,Source Latitude,Source Longitude,Destination Latitude,Destination Longitude,Flight Distance (km),Flight Duration (hh:mm)
0,Coimbatore,Ranchi,11.00555,76.96612,23.34316,85.30940,1632.07,01:48
1,Coimbatore,Dabolim,11.00555,76.96612,15.38083,73.83142,593.12,00:39
2,Coimbatore,Ahmedabad,11.00555,76.96612,23.02579,72.58727,1415.00,01:34
3,Coimbatore,Hyderabad,11.00555,76.96612,17.38405,78.45636,727.20,00:48
4,Coimbatore,Khowai,11.00555,76.96612,24.06190,91.60390,2121.73,02:21
...,...,...,...,...,...,...,...,...
1426,Indore,Patna,22.71792,75.83330,25.59408,85.13563,996.20,01:06
1427,Indore,Mumbai,22.71792,75.83330,19.07283,72.88261,508.12,00:33
1428,Mysuru,Patna,12.29791,76.63925,25.59408,85.13563,1726.07,01:55
1429,Mysuru,Mumbai,12.29791,76.63925,19.07283,72.88261,853.82,00:56
1430,Patna,Mumbai,25.59408,85.13563,19.07283,72.88261,1452.80,01:36

In [50]:
df_neww = df_neww.rename(columns={'Source City':'Departure', 'Destination City' : 'Arrival'})

In [53]:
flight_india = pd.merge(df_Flight, df_neww, on=['Departure', 'Arrival'], how= 'left')

In [54]:
flight_india

,travelCode,User_ID,flightType,Flight_price,Flight_duration,Flight_Distance,Flight_agency,Departure_date,Departure,Arrival,Source Latitude,Source Longitude,Destination Latitude,Destination Longitude,Flight Distance (km),Flight Duration (hh:mm)
0,0,0,firstClass,1434.38,1.76,676.53,FlyingDrops,26/09/2019,Coimbatore,Visakhapatnam,11.00555,76.96612,17.68009,83.20161,1000.71,01:06
1,2,0,firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019,Ranchi,Shillong,23.34316,85.30940,25.56892,91.88313,709.80,00:47
2,7,0,economic,964.83,2.16,830.86,CloudFy,14/11/2019,Dabolim,Ranchi,NaN,NaN,NaN,NaN,NaN,NaN
3,11,0,premium,1268.97,1.76,676.56,Rainbow,12/12/2019,Ahmedabad,Raigarh,23.02579,72.58727,21.89764,83.39660,1117.55,01:14
4,13,0,firstClass,1434.38,1.76,676.53,FlyingDrops,26/12/2019,Hyderabad,Kolkata,17.38405,78.45636,22.56263,88.36304,1184.11,01:18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,885.37,1.66,637.56,CloudFy,18/06/2020,Indore,Dabolim,NaN,NaN,NaN,NaN,NaN,NaN
40548,135939,1339,premium,814.55,1.66,637.56,Rainbow,25/06/2020,Ahmedabad,Shillong,23.02579,72.58727,25.56892,91.88313,1974.07,02:11
40549,135940,1339,firstClass,857.32,1.49,573.81,Rainbow,07/02/2020,Prayagraj,Visakhapatnam,25.44478,81.84322,17.68009,83.20161,874.72,00:58
40550,135941,1339,firstClass,949.58,1.49,573.81,CloudFy,07/09/2020,Surat,Dabolim,NaN,NaN,NaN,NaN,NaN,NaN
40551,135942,1339,economic,726.95,1.84,709.37,CloudFy,16/07/2020,Bhopal,Prayagraj,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
df_newww = df_neww.copy()

In [56]:
df_newww

,Departure,Arrival,Source Latitude,Source Longitude,Destination Latitude,Destination Longitude,Flight Distance (km),Flight Duration (hh:mm)
0,Coimbatore,Ranchi,11.00555,76.96612,23.34316,85.30940,1632.07,01:48
1,Coimbatore,Dabolim,11.00555,76.96612,15.38083,73.83142,593.12,00:39
2,Coimbatore,Ahmedabad,11.00555,76.96612,23.02579,72.58727,1415.00,01:34
3,Coimbatore,Hyderabad,11.00555,76.96612,17.38405,78.45636,727.20,00:48
4,Coimbatore,Khowai,11.00555,76.96612,24.06190,91.60390,2121.73,02:21
...,...,...,...,...,...,...,...,...
1426,Indore,Patna,22.71792,75.83330,25.59408,85.13563,996.20,01:06
1427,Indore,Mumbai,22.71792,75.83330,19.07283,72.88261,508.12,00:33
1428,Mysuru,Patna,12.29791,76.63925,25.59408,85.13563,1726.07,01:55
1429,Mysuru,Mumbai,12.29791,76.63925,19.07283,72.88261,853.82,00:56
1430,Patna,Mumbai,25.59408,85.13563,19.07283,72.88261,1452.80,01:36

In [59]:
df_newww = df_newww.rename(columns={'Departure' : 'Arrival1'})

In [60]:
df_newww = df_newww.rename(columns={'Arrival' : 'Departure'})

In [61]:
df_newww = df_newww.rename(columns={'Arrival1' : 'Arrival'})
df_newww

,Arrival,Departure,Source Latitude,Source Longitude,Destination Latitude,Destination Longitude,Flight Distance (km),Flight Duration (hh:mm)
0,Coimbatore,Ranchi,11.00555,76.96612,23.34316,85.30940,1632.07,01:48
1,Coimbatore,Dabolim,11.00555,76.96612,15.38083,73.83142,593.12,00:39
2,Coimbatore,Ahmedabad,11.00555,76.96612,23.02579,72.58727,1415.00,01:34
3,Coimbatore,Hyderabad,11.00555,76.96612,17.38405,78.45636,727.20,00:48
4,Coimbatore,Khowai,11.00555,76.96612,24.06190,91.60390,2121.73,02:21
...,...,...,...,...,...,...,...,...
1426,Indore,Patna,22.71792,75.83330,25.59408,85.13563,996.20,01:06
1427,Indore,Mumbai,22.71792,75.83330,19.07283,72.88261,508.12,00:33
1428,Mysuru,Patna,12.29791,76.63925,25.59408,85.13563,1726.07,01:55
1429,Mysuru,Mumbai,12.29791,76.63925,19.07283,72.88261,853.82,00:56
1430,Patna,Mumbai,25.59408,85.13563,19.07283,72.88261,1452.80,01:36

In [64]:
 coordinate_final = pd.concat([df_neww, df_newww], axis=0,ignore_index=True)

In [79]:
India_datas = pd.merge(df_Flight, coordinate_final, on=['Departure', 'Arrival'], how= 'left')

In [80]:
India_datas

,travelCode,User_ID,flightType,Flight_price,Flight_duration,Flight_Distance,Flight_agency,Departure_date,Departure,Arrival,Source Latitude,Source Longitude,Destination Latitude,Destination Longitude,Flight Distance (km),Flight Duration (hh:mm)
0,0,0,firstClass,1434.38,1.76,676.53,FlyingDrops,26/09/2019,Coimbatore,Visakhapatnam,11.00555,76.96612,17.68009,83.20161,1000.71,01:06
1,2,0,firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019,Ranchi,Shillong,23.34316,85.30940,25.56892,91.88313,709.80,00:47
2,7,0,economic,964.83,2.16,830.86,CloudFy,14/11/2019,Dabolim,Ranchi,23.34316,85.30940,15.38083,73.83142,1493.33,01:39
3,11,0,premium,1268.97,1.76,676.56,Rainbow,12/12/2019,Ahmedabad,Raigarh,23.02579,72.58727,21.89764,83.39660,1117.55,01:14
4,13,0,firstClass,1434.38,1.76,676.53,FlyingDrops,26/12/2019,Hyderabad,Kolkata,17.38405,78.45636,22.56263,88.36304,1184.11,01:18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,885.37,1.66,637.56,CloudFy,18/06/2020,Indore,Dabolim,15.38083,73.83142,22.71792,75.83330,842.49,00:56
40548,135939,1339,premium,814.55,1.66,637.56,Rainbow,25/06/2020,Ahmedabad,Shillong,23.02579,72.58727,25.56892,91.88313,1974.07,02:11
40549,135940,1339,firstClass,857.32,1.49,573.81,Rainbow,07/02/2020,Prayagraj,Visakhapatnam,25.44478,81.84322,17.68009,83.20161,874.72,00:58
40550,135941,1339,firstClass,949.58,1.49,573.81,CloudFy,07/09/2020,Surat,Dabolim,15.38083,73.83142,21.19594,72.83023,655.18,00:43
40551,135942,1339,economic,726.95,1.84,709.37,CloudFy,16/07/2020,Bhopal,Prayagraj,25.44478,81.84322,23.25469,77.40289,511.46,00:34

In [67]:
India_datas.to_excel('Final_India.xlsx',index=False)
from IPython.display import FileLink
FileLink('Final_India.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\Final_India.xlsx

In [68]:
coordinate_final.to_excel('Subset.xlsx',index=False)
from IPython.display import FileLink
FileLink('Subset.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\Subset.xlsx

In [69]:
airlines = ['Air India','IndiGo','SpiceJet','AirAsia India','Akasa Air','GoAir']

In [70]:
India_datas['Flight_agency'].unique()

array(['FlyingDrops', 'CloudFy', 'Rainbow'], dtype=object)

In [71]:
India_datas['Flight_agency'].value_counts()

Flight_agency
CloudFy        17410
Rainbow        17392
FlyingDrops     5750
Name: count, dtype: int64

In [72]:
mapping = {
    'CloudFy': ['Air India', 'IndiGo'],
    'Rainbow': ['SpiceJet', 'Akasa Air'],
    'FlyingDrops': ['AirAsia India','GoAir']
}

In [81]:
import random

newww = []
for item in India_datas['Flight_agency']:
    if item in mapping:
        newww.append(random.choice(mapping[item]))  # Append the randomly chosen value
    else:
        newww.append(item)  # Append the original value if not in mapping

In [84]:
len(newww)

40552

In [85]:
India_datas['Flight_agency'] = newww

In [86]:
India_datas

,travelCode,User_ID,flightType,Flight_price,Flight_duration,Flight_Distance,Flight_agency,Departure_date,Departure,Arrival,Source Latitude,Source Longitude,Destination Latitude,Destination Longitude,Flight Distance (km),Flight Duration (hh:mm)
0,0,0,firstClass,1434.38,1.76,676.53,GoAir,26/09/2019,Coimbatore,Visakhapatnam,11.00555,76.96612,17.68009,83.20161,1000.71,01:06
1,2,0,firstClass,1684.05,2.16,830.86,IndiGo,10/10/2019,Ranchi,Shillong,23.34316,85.30940,25.56892,91.88313,709.80,00:47
2,7,0,economic,964.83,2.16,830.86,Air India,14/11/2019,Dabolim,Ranchi,23.34316,85.30940,15.38083,73.83142,1493.33,01:39
3,11,0,premium,1268.97,1.76,676.56,SpiceJet,12/12/2019,Ahmedabad,Raigarh,23.02579,72.58727,21.89764,83.39660,1117.55,01:14
4,13,0,firstClass,1434.38,1.76,676.53,GoAir,26/12/2019,Hyderabad,Kolkata,17.38405,78.45636,22.56263,88.36304,1184.11,01:18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,885.37,1.66,637.56,Air India,18/06/2020,Indore,Dabolim,15.38083,73.83142,22.71792,75.83330,842.49,00:56
40548,135939,1339,premium,814.55,1.66,637.56,Akasa Air,25/06/2020,Ahmedabad,Shillong,23.02579,72.58727,25.56892,91.88313,1974.07,02:11
40549,135940,1339,firstClass,857.32,1.49,573.81,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,25.44478,81.84322,17.68009,83.20161,874.72,00:58
40550,135941,1339,firstClass,949.58,1.49,573.81,IndiGo,07/09/2020,Surat,Dabolim,15.38083,73.83142,21.19594,72.83023,655.18,00:43
40551,135942,1339,economic,726.95,1.84,709.37,IndiGo,16/07/2020,Bhopal,Prayagraj,25.44478,81.84322,23.25469,77.40289,511.46,00:34

In [87]:
India_datas['Flight_agency'].value_counts()

Flight_agency
Akasa Air        8750
IndiGo           8724
Air India        8686
SpiceJet         8642
AirAsia India    2887
GoAir            2863
Name: count, dtype: int64

In [89]:
India_datas = India_datas.drop(columns={'Flight_Distance','Flight_duration'})

In [92]:
India_datas = India_datas.drop(columns={'Source Latitude','Source Longitude','Destination Latitude','Destination Longitude'})

In [93]:
India_datas

,travelCode,User_ID,flightType,Flight_price,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm)
0,0,0,firstClass,1434.38,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06
1,2,0,firstClass,1684.05,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47
2,7,0,economic,964.83,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39
3,11,0,premium,1268.97,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14
4,13,0,firstClass,1434.38,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18
...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,885.37,Air India,18/06/2020,Indore,Dabolim,842.49,00:56
40548,135939,1339,premium,814.55,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11
40549,135940,1339,firstClass,857.32,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58
40550,135941,1339,firstClass,949.58,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43
40551,135942,1339,economic,726.95,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34

In [94]:
India_datas.to_excel('Final_India_time.xlsx',index=False)
from IPython.display import FileLink
FileLink('Final_India_time.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\Final_India_time.xlsx

In [96]:
from datetime import datetime, timedelta

def generate_random_time():
    hour = np.random.randint(0, 24)  # Random hour (0-23)
    minute = np.random.randint(0, 60)  # Random minute (0-59)
    return f"{hour:02}:{minute:02}"

# Convert Flight Duration to timedelta and compute arrival time
def calculate_arrival_time(departure_time, duration):
    try:
        dep_time = datetime.strptime(departure_time, "%H:%M")
        duration_parts = list(map(int, duration.split(":")))
        flight_duration = timedelta(hours=duration_parts[0], minutes=duration_parts[1])
        arrival_time = dep_time + flight_duration
        return arrival_time.strftime("%H:%M")
    except Exception:
        return None  # Handle any potential errors

# Generate departure times and calculate arrival times
India_datas["Departure Time"] = [generate_random_time() for _ in range(len(India_datas))]
India_datas["Arrival Time"] = India_datas.apply(lambda row: calculate_arrival_time(row["Departure Time"], row["Flight Duration (hh:mm)"]), axis=1)

In [97]:
India_datas

,travelCode,User_ID,flightType,Flight_price,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time
0,0,0,firstClass,1434.38,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05
1,2,0,firstClass,1684.05,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49
2,7,0,economic,964.83,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54
3,11,0,premium,1268.97,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49
4,13,0,firstClass,1434.38,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36
...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,885.37,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24
40548,135939,1339,premium,814.55,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48
40549,135940,1339,firstClass,857.32,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25
40550,135941,1339,firstClass,949.58,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29
40551,135942,1339,economic,726.95,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48

In [98]:
India_datas.to_excel('Final_India_with_time.xlsx',index=False)
from IPython.display import FileLink
FileLink('Final_India_with_time.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\Final_India_with_time.xlsx

In [100]:
India_Datas = India_datas.drop(columns={'Flight_price'})

In [101]:
India_Datas

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05
1,2,0,firstClass,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49
2,7,0,economic,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54
3,11,0,premium,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49
4,13,0,firstClass,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36
...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24
40548,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48
40549,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25
40550,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29
40551,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48

In [102]:
import pandas as pd

# Function to convert flight duration from hh:mm to total minutes
def convert_duration_to_minutes(duration):
    hours, minutes = map(int, duration.split(":"))
    return hours * 60 + minutes

# Function to calculate flight price
def calculate_flight_price(row):
    base_price = 500  # Base price for any flight

    # Adjusting price based on flight type
    type_multiplier = {
        "economic": 1.0,
        "premium": 1.3,
        "business": 1.6,
        "firstClass": 2.0
    }
    
    flight_type = row["flightType"]
    multiplier = type_multiplier.get(flight_type, 1.0)
    
    # Distance-based cost (per km charge)
    distance_cost = row["Flight Distance (km)"] * 2
    
    # Duration-based cost (per minute charge)
    duration_cost = convert_duration_to_minutes(row["Flight Duration (hh:mm)"]) * 1.5
    
    # Airline surcharge (mock values for different airlines)
    agency_surcharge = {
        "IndiGo": 100,
        "SpiceJet": 120,
        "GoAir": 110,
        "Air India": 150
    }
    
    agency_cost = agency_surcharge.get(row["Flight_agency"], 100)
    
    # Departure time effect (peak hours: 6 AM - 10 AM & 6 PM - 10 PM increase price)
    departure_hour = int(row["Departure Time"].split(":")[0])
    peak_hour_surcharge = 200 if (6 <= departure_hour < 10 or 18 <= departure_hour < 22) else 0

    # Final price calculation
    price = base_price + (distance_cost + duration_cost) * multiplier + agency_cost + peak_hour_surcharge
    return round(price, 2)

# Load the dataset


# Apply function to calculate price
India_Datas["Calculated_Flight_Price"] = India_Datas.apply(calculate_flight_price, axis=1)

India_Datas

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,4810.84
1,2,0,firstClass,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,3580.20
2,7,0,economic,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,3785.16
3,11,0,premium,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,3669.93
4,13,0,firstClass,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,5780.44
...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,2949.67
40548,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,5988.03
40549,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,4272.88
40550,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,3349.72
40551,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,1673.92

In [103]:
import pandas as pd

# Function to convert flight duration from hh:mm to total minutes
def convert_duration_to_minutes(duration):
    hours, minutes = map(int, duration.split(":"))
    return hours * 60 + minutes

# Function to calculate flight price
def calculate_flight_price(row):
    base_price = 500  # Base price for any flight

    # Adjusting price based on flight type
    type_multiplier = {
        "economic": 1.5,
        "premium": 1.8,
        "business": 2.1,
        "firstClass": 2.5
    }
    
    flight_type = row["flightType"]
    multiplier = type_multiplier.get(flight_type, 1.0)
    
    # Distance-based cost (per km charge)
    distance_cost = row["Flight Distance (km)"] * 2
    
    # Duration-based cost (per minute charge)
    duration_cost = convert_duration_to_minutes(row["Flight Duration (hh:mm)"]) * 1.5
    
    # Airline surcharge (mock values for different airlines)
    agency_surcharge = {
        "IndiGo": 100,
        "SpiceJet": 120,
        "GoAir": 110,
        "Air India": 150
    }
    
    agency_cost = agency_surcharge.get(row["Flight_agency"], 100)
    
    # Departure time effect (peak hours: 6 AM - 10 AM & 6 PM - 10 PM increase price)
    departure_hour = int(row["Departure Time"].split(":")[0])
    peak_hour_surcharge = 200 if (6 <= departure_hour < 10 or 18 <= departure_hour < 22) else 0

    # Final price calculation
    price = base_price + (distance_cost + duration_cost) * multiplier + agency_cost + peak_hour_surcharge
    return round(price, 2)



df = India_datas.drop(columns={'Flight_price'})
# Apply function to calculate price
df["Calculated_Flight_Price"] = df.apply(calculate_flight_price, axis=1)

# Save updated file
df.to_excel("Updated_Flight_Data.xlsx", index=False)

print("Flight price calculation completed and saved!")

Flight price calculation completed and saved!

In [104]:
df

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,5861.05
1,2,0,firstClass,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,4325.25
2,7,0,economic,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,5352.74
3,11,0,premium,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,4842.98
4,13,0,firstClass,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,7023.05
...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,3834.16
40548,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,8060.35
40549,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,5191.10
40550,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,4037.15
40551,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,2210.88

In [105]:
df['flightType'].value_counts()

flightType
firstClass    17304
premium       11656
economic      11592
Name: count, dtype: int64

In [106]:
df['Flight_agency'].value_counts()

Flight_agency
Akasa Air        8750
IndiGo           8724
Air India        8686
SpiceJet         8642
AirAsia India    2887
GoAir            2863
Name: count, dtype: int64

In [107]:
df_neww

,Departure,Arrival,Source Latitude,Source Longitude,Destination Latitude,Destination Longitude,Flight Distance (km),Flight Duration (hh:mm)
0,Coimbatore,Ranchi,11.00555,76.96612,23.34316,85.30940,1632.07,01:48
1,Coimbatore,Dabolim,11.00555,76.96612,15.38083,73.83142,593.12,00:39
2,Coimbatore,Ahmedabad,11.00555,76.96612,23.02579,72.58727,1415.00,01:34
3,Coimbatore,Hyderabad,11.00555,76.96612,17.38405,78.45636,727.20,00:48
4,Coimbatore,Khowai,11.00555,76.96612,24.06190,91.60390,2121.73,02:21
...,...,...,...,...,...,...,...,...
1426,Indore,Patna,22.71792,75.83330,25.59408,85.13563,996.20,01:06
1427,Indore,Mumbai,22.71792,75.83330,19.07283,72.88261,508.12,00:33
1428,Mysuru,Patna,12.29791,76.63925,25.59408,85.13563,1726.07,01:55
1429,Mysuru,Mumbai,12.29791,76.63925,19.07283,72.88261,853.82,00:56
1430,Patna,Mumbai,25.59408,85.13563,19.07283,72.88261,1452.80,01:36

In [108]:
prd = pd.read_excel("FlightFINALdataset.xlsx")
prd

,travelCode,User_ID,Departure,Arrival,flightType,Flight_price,Flight_duration,Flight_Distance,Flight_agency,Departure_date
0,0,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,26/09/2019
1,2,0,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019
2,7,0,Aracaju (SE),Salvador (BH),economic,964.83,2.16,830.86,CloudFy,14/11/2019
3,11,0,Brasilia (DF),Salvador (BH),premium,1268.97,1.76,676.56,Rainbow,12/12/2019
4,13,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,26/12/2019
...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,Florianopolis (SC),Brasilia (DF),premium,885.37,1.66,637.56,CloudFy,18/06/2020
40548,135939,1339,Florianopolis (SC),Brasilia (DF),premium,814.55,1.66,637.56,Rainbow,25/06/2020
40549,135940,1339,Florianopolis (SC),Campo Grande (MS),firstClass,857.32,1.49,573.81,Rainbow,07/02/2020
40550,135941,1339,Florianopolis (SC),Campo Grande (MS),firstClass,949.58,1.49,573.81,CloudFy,07/09/2020
40551,135942,1339,Florianopolis (SC),Natal (RN),economic,726.95,1.84,709.37,CloudFy,16/07/2020

In [109]:
df_prd = prd.iloc[:20276].copy(deep=True)

In [110]:
df_prd

,travelCode,User_ID,Departure,Arrival,flightType,Flight_price,Flight_duration,Flight_Distance,Flight_agency,Departure_date
0,0,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,26/09/2019
1,2,0,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019
2,7,0,Aracaju (SE),Salvador (BH),economic,964.83,2.16,830.86,CloudFy,14/11/2019
3,11,0,Brasilia (DF),Salvador (BH),premium,1268.97,1.76,676.56,Rainbow,12/12/2019
4,13,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,26/12/2019
...,...,...,...,...,...,...,...,...,...,...
20271,67818,658,Aracaju (SE),Natal (RN),premium,427.25,0.46,176.33,Rainbow,19/12/2019
20272,67819,658,Natal (RN),Recife (PE),economic,406.36,0.58,222.67,Rainbow,26/12/2019
20273,67824,658,Aracaju (SE),Rio de Janeiro (RJ),premium,930.12,1.55,597.61,Rainbow,30/01/2020
20274,67826,658,Aracaju (SE),Florianopolis (SC),firstClass,1499.93,2.10,808.85,FlyingDrops,13/02/2020
20275,67830,658,Natal (RN),Brasilia (DF),firstClass,1192.62,1.43,550.69,FlyingDrops,03/12/2020

In [114]:
import pandas as pd

# Load the dataset
# file_path = "Updated_Flight_Data.xlsx"
# df = pd.read_excel(file_path, sheet_name="Sheet1")

# Convert 'Departure_date' to datetime format
df_PRDD["Departure_date"] = pd.to_datetime(df["Departure_date"], dayfirst=True)

# Sort by 'User_ID' and 'Departure_date'
df_PRDD.sort_values(by=["User_ID", "Departure_date"], inplace=True)

# Iterate through the DataFrame to update the departure date when a user returns
for i in range(1, len(df)):
    if (
        df_PRDD.loc[i, "User_ID"] == df_PRDD.loc[i - 1, "User_ID"] and
        df_PRDD.loc[i, "Departure"] == df_PRDD.loc[i - 1, "Arrival"]
    ):
        df_PRDD.loc[i, "Departure_date"] = df_PRDD.loc[i - 1, "Departure_date"]

# Save the modified DataFrame to a new file
# df.to_excel("Modified_Flight_Data.xlsx", index=False)

In [115]:
# df_PRDD = df.copy()
df_PRDD

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,0,0,firstClass,GoAir,2019-09-26,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,5861.05
1,2,0,firstClass,IndiGo,2019-10-10,Ranchi,Shillong,709.80,00:47,01:02,01:49,4325.25
2,7,0,economic,Air India,2019-11-14,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,5352.74
3,11,0,premium,SpiceJet,2019-12-12,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,4842.98
4,13,0,firstClass,GoAir,2019-12-26,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,7023.05
...,...,...,...,...,...,...,...,...,...,...,...,...
40542,135919,1339,premium,IndiGo,2020-06-02,Dehradun,Bhubaneswar,1364.32,01:30,17:45,19:15,5754.55
40547,135938,1339,premium,Air India,2020-06-18,Indore,Dabolim,842.49,00:56,04:28,05:24,3834.16
40548,135939,1339,premium,Akasa Air,2020-06-25,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,8060.35
40551,135942,1339,economic,IndiGo,2020-07-16,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,2210.88
40550,135941,1339,firstClass,IndiGo,2020-09-07,Surat,Dabolim,655.18,00:43,00:46,01:29,4037.15

In [139]:
df_fil= df[
    (round_trip_d["Departure_outbound"] == round_trip_d["Arrival_return"]) &
    (round_trip_d["Arrival_outbound"] == round_trip_d["Departure_return"]) &
    (round_trip_d["travelCode_outbound"] != round_trip_d["travelCode_return"])

]

df_fil

C:\Users\SURAJ\AppData\Local\Temp\ipykernel_5032\1567875806.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_fil= df[

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
6851,22601,220,firstClass,Akasa Air,29/09/2022,Mumbai,Dabolim,422.71,00:28,10:50,11:18,2818.55
8226,27176,261,premium,Akasa Air,04/08/2021,Varanasi,Udaipur,940.61,01:02,12:51,13:53,4153.60
17990,59977,581,firstClass,GoAir,17/06/2021,Kullu-Manali,Dabolim,1864.90,02:04,01:01,03:05,10399.50
18382,61282,599,premium,Akasa Air,17/09/2020,Bilaspur,Kullu-Manali,1196.31,01:19,21:45,23:04,5320.02
19939,66699,646,firstClass,GoAir,13/10/2022,Shimla,Indore,941.83,01:02,02:53,03:55,5551.65
21871,73420,712,firstClass,SpiceJet,28/01/2021,Nashik,Chennai,1033.30,01:08,11:06,12:14,6041.50
25485,85655,843,firstClass,AirAsia India,22/04/2021,Jamshedpur,Visakhapatnam,649.06,00:43,22:45,23:28,4006.55
25563,85912,847,firstClass,AirAsia India,07/09/2020,Mumbai,Ahmedabad,440.62,00:29,23:36,00:05,2911.85
28851,96897,958,premium,Air India,09/03/2020,Visakhapatnam,Chennai,599.08,00:39,22:10,22:49,2911.99
29735,99896,992,firstClass,GoAir,24/06/2021,Srinagar,Mopa,7566.74,08:24,09:15,17:39,40533.70
33600,112864,1120,premium,Akasa Air,16/07/2020,Coimbatore,Hisar,6370.71,07:04,14:20,21:24,24679.36
34132,114564,1139,premium,Air India,12/09/2021,Coimbatore,Hisar,6370.71,07:04,15:35,22:39,24729.36
39849,133596,1316,premium,SpiceJet,26/03/2020,Khowai,Shillong,169.93,00:11,10:18,10:29,1261.45
40330,135132,1330,firstClass,Air India,18/03/2021,Ahmedabad,Navi Mumbai,445.78,00:29,23:20,23:49,2987.65
40343,135186,1330,economic,Akasa Air,31/03/2022,Shillong,Jamshedpur,654.58,00:43,16:23,17:06,2660.49

In [138]:
round_trip_d = df_PRRRR.merge(df_PRRRR, on="User_ID", suffixes=("_outbound", "_return"))

In [134]:
df_PRRRR = df.copy()

In [135]:
df_PRRRR

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,5861.05
1,2,0,firstClass,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,4325.25
2,7,0,economic,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,5352.74
3,11,0,premium,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,4842.98
4,13,0,firstClass,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,7023.05
...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,3834.16
40548,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,8060.35
40549,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,5191.10
40550,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,4037.15
40551,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,2210.88

In [140]:
df

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,5861.05
1,2,0,firstClass,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,4325.25
2,7,0,economic,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,5352.74
3,11,0,premium,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,4842.98
4,13,0,firstClass,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,7023.05
...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,3834.16
40548,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,8060.35
40549,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,5191.10
40550,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,4037.15
40551,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,2210.88

In [150]:
import pandas as pd

def filter_round_trips(file_path, sheet_name="Sheet1"):
    # Load the Excel file
    df = pd.read_excel(file_path, sheet_name=sheet_name)
    
    # Creating a set of tuples for user travel history (Departure -> Arrival)
    user_trips = set(zip(df["User_ID"], df["Departure"], df["Arrival"]))
    
    # Identifying round trips (Arrival -> Departure exists for the same user)
    round_trips = {(user, arr, dep) for (user, dep, arr) in user_trips if (user, arr, dep) in user_trips}
    
    # Filtering out round trips from the dataframe
    filtered_df = df[~df.apply(lambda row: (row["User_ID"], row["Departure"], row["Arrival"]) in round_trips, axis=1)]
    
    return filtered_df

# Example usage
file_path = "df_INDIA.xlsx"  # Update this with the actual file path
filtered_data = filter_round_trips(file_path)

# Save the filtered data
filtered_data.to_excel("Filter_Flight_Data.xlsx", index=False)

print("Filtered data has been saved to 'Filter_Flight_Data.xlsx'")

Filtered data has been saved to 'Filter_Flight_Data.xlsx'

In [142]:
India_datas

,travelCode,User_ID,flightType,Flight_price,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time
0,0,0,firstClass,1434.38,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05
1,2,0,firstClass,1684.05,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49
2,7,0,economic,964.83,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54
3,11,0,premium,1268.97,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49
4,13,0,firstClass,1434.38,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36
...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,885.37,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24
40548,135939,1339,premium,814.55,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48
40549,135940,1339,firstClass,857.32,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25
40550,135941,1339,firstClass,949.58,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29
40551,135942,1339,economic,726.95,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48

In [147]:
df_INDIA = India_Datas.copy()

In [143]:
India_Datas

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,4810.84
1,2,0,firstClass,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,3580.20
2,7,0,economic,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,3785.16
3,11,0,premium,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,3669.93
4,13,0,firstClass,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,5780.44
...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,2949.67
40548,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,5988.03
40549,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,4272.88
40550,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,3349.72
40551,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,1673.92

In [149]:
df_INDIA.to_excel('df_INDIA.xlsx',index=False)
from IPython.display import FileLink
FileLink('df_INDIA.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\df_INDIA.xlsx

In [148]:
df_INDIA

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,4810.84
1,2,0,firstClass,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,3580.20
2,7,0,economic,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,3785.16
3,11,0,premium,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,3669.93
4,13,0,firstClass,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,5780.44
...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,2949.67
40548,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,5988.03
40549,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,4272.88
40550,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,3349.72
40551,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,1673.92

In [151]:
Hetvi = pd.read_excel("Final_India_with_time_updated_by_Hetvi.xlsx")

In [152]:
Hetvi

,travelCode,User_ID,flightType,Flight_price,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,flight_number
0,0,0,firstClass,1434.38,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,G81069B
1,2,0,firstClass,1684.05,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,6E828
2,7,0,economic,964.83,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,AI297
3,11,0,premium,1268.97,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,SG6667
4,13,0,firstClass,1434.38,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,G81820C
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,885.37,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,AI690D
40548,135939,1339,premium,814.55,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,QP1902B
40549,135940,1339,firstClass,857.32,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,QP1196D
40550,135941,1339,firstClass,949.58,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,6E978
40551,135942,1339,economic,726.95,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,6E276

In [153]:
# Ensure required columns exist
required_columns = {'User_ID', 'Departure', 'Arrival'}
if not required_columns.issubset(df.columns):
    raise ValueError(f"Missing required columns: {required_columns - set(df.columns)}")

# Create trip and reverse trip identifiers
df['Trip_Key'] = list(zip(df['User_ID'], df['Departure'], df['Arrival']))
df['Reverse_Trip_Key'] = list(zip(df['User_ID'], df['Arrival'], df['Departure']))

# Find round trips by checking if Reverse_Trip_Key exists in Trip_Key
round_trip_df = df[df['Reverse_Trip_Key'].isin(df['Trip_Key'])]

# Drop helper columns
round_trip_df = round_trip_df.drop(columns=['Trip_Key', 'Reverse_Trip_Key'])

# Display the first few rows
round_trip_df

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
146,503,4,firstClass,Air India,25/03/2021,Itanagar,Surat,2204.62,02:26,00:56,03:22,12220.60
171,590,4,economic,SpiceJet,24/11/2022,Surat,Itanagar,2204.62,02:26,04:18,06:44,7562.36
426,1479,13,economic,IndiGo,07/09/2020,Bengaluru,Visakhapatnam,797.17,00:53,01:41,02:34,3110.76
434,1507,13,economic,SpiceJet,21/01/2021,Visakhapatnam,Bengaluru,797.17,00:53,08:07,09:00,3330.76
472,1666,15,firstClass,Air India,28/11/2019,Chandigarh,Navi Mumbai,1355.13,01:30,11:12,12:42,7763.15
...,...,...,...,...,...,...,...,...,...,...,...,...
39839,133540,1315,economic,Akasa Air,04/07/2022,Delhi NCR,Shimla,271.89,00:18,13:48,14:06,1456.17
40151,134586,1323,premium,Air India,16/12/2021,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84
40161,134613,1323,firstClass,Akasa Air,23/06/2022,Dehradun,Hyderabad,1439.54,01:35,22:00,23:35,8153.95
40470,135670,1335,firstClass,IndiGo,28/11/2019,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25
40502,135799,1335,premium,Akasa Air,19/05/2022,Kota,Raigarh,3289.60,03:39,22:43,02:22,13033.86

In [154]:
round_trip_df.to_excel('round_trip_df.xlsx',index=False)
from IPython.display import FileLink
FileLink('round_trip_df.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\round_trip_df.xlsx

In [158]:
arr = round_trip_df['User_ID'].unique()

In [159]:
len(arr)

238

In [160]:
Hetvi

,travelCode,User_ID,flightType,Flight_price,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,flight_number
0,0,0,firstClass,1434.38,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,G81069B
1,2,0,firstClass,1684.05,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,6E828
2,7,0,economic,964.83,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,AI297
3,11,0,premium,1268.97,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,SG6667
4,13,0,firstClass,1434.38,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,G81820C
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,885.37,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,AI690D
40548,135939,1339,premium,814.55,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,QP1902B
40549,135940,1339,firstClass,857.32,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,QP1196D
40550,135941,1339,firstClass,949.58,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,6E978
40551,135942,1339,economic,726.95,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,6E276

In [165]:
Hetvi = Hetvi.drop(columns={'Flight_price'})
Hetvi

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,flight_number
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,G81069B
1,2,0,firstClass,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,6E828
2,7,0,economic,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,AI297
3,11,0,premium,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,SG6667
4,13,0,firstClass,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,G81820C
...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,AI690D
40548,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,QP1902B
40549,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,QP1196D
40550,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,6E978
40551,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,6E276

In [166]:
round_trip_df['User_ID'].value_counts()

User_ID
1286    6
93      6
1041    6
737     6
641     6
       ..
479     2
483     2
484     2
485     2
1335    2
Name: count, Length: 238, dtype: int64

In [175]:
user_count = round_trip_df["User_ID"].value_counts()

In [181]:
users_2

Index([ 717,  749,  900,  905,  731,  928,  907,  714,  696,  923,
       ...
        449,  454,  456,  458,  466,  479,  483,  484,  485, 1335],
      dtype='int64', name='User_ID', length=194)

In [177]:
users_2 = user_count[user_count == 2].index
users_4 = user_count[user_count == 4].index
users_6 = user_count[user_count == 6].index

In [192]:
round_trip_df_2 = round_trip_df[round_trip_df["User_ID"].isin(users_2)]
round_trip_df_4 = round_trip_df[round_trip_df["User_ID"].isin(users_4)]
round_trip_df_6 = round_trip_df[round_trip_df["User_ID"].isin(users_6)]

In [194]:
round_trip_df_4

Empty DataFrame
Columns: [travelCode, User_ID, flightType, Flight_agency, Departure_date, Departure, Arrival, Flight Distance (km), Flight Duration (hh:mm), Departure Time, Arrival Time, Calculated_Flight_Price]
Index: []

In [182]:
round_trip_df

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
146,503,4,firstClass,Air India,25/03/2021,Itanagar,Surat,2204.62,02:26,00:56,03:22,12220.60
171,590,4,economic,SpiceJet,24/11/2022,Surat,Itanagar,2204.62,02:26,04:18,06:44,7562.36
426,1479,13,economic,IndiGo,07/09/2020,Bengaluru,Visakhapatnam,797.17,00:53,01:41,02:34,3110.76
434,1507,13,economic,SpiceJet,21/01/2021,Visakhapatnam,Bengaluru,797.17,00:53,08:07,09:00,3330.76
472,1666,15,firstClass,Air India,28/11/2019,Chandigarh,Navi Mumbai,1355.13,01:30,11:12,12:42,7763.15
...,...,...,...,...,...,...,...,...,...,...,...,...
39839,133540,1315,economic,Akasa Air,04/07/2022,Delhi NCR,Shimla,271.89,00:18,13:48,14:06,1456.17
40151,134586,1323,premium,Air India,16/12/2021,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84
40161,134613,1323,firstClass,Akasa Air,23/06/2022,Dehradun,Hyderabad,1439.54,01:35,22:00,23:35,8153.95
40470,135670,1335,firstClass,IndiGo,28/11/2019,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25
40502,135799,1335,premium,Akasa Air,19/05/2022,Kota,Raigarh,3289.60,03:39,22:43,02:22,13033.86

In [199]:
import pandas as pd

# Load the dataset
file_path = "round_trip_df.xlsx"  # Update with the correct path
Check_Hetvi = pd.read_excel(file_path, sheet_name="Sheet1")

# Count occurrences of each User_ID
user_counts = df["User_ID"].value_counts()

# Get User_IDs with occurrence counts of 2, 4, and 6
users_2 = user_counts[user_counts == 2].index
users_4 = user_counts[user_counts == 4].index
users_6 = user_counts[user_counts == 6].index

# Filter the dataset
df_2 = Check_Hetvi[Check_Hetvi["User_ID"].isin(users_2)].copy()
df_4 = Check_Hetvi[Check_Hetvi["User_ID"].isin(users_4)].copy()
df_6 = Check_Hetvi[Check_Hetvi["User_ID"].isin(users_6)].copy()

# Save to new Excel files
# df_2.to_excel("dataset_user_2.xlsx", index=False)
# df_4.to_excel("dataset_user_4.xlsx", index=False)
# df_6.to_excel("dataset_user_6.xlsx", index=False)

# print("Datasets have been successfully created and saved!")

In [197]:
Check_Hetvi["User_ID"] = Check_Hetvi["User_ID"].astype(str)  
user_counts.index = user_counts.index.astype(str)  # Ensure index of value_counts matches

In [200]:
df_6

Empty DataFrame
Columns: [travelCode, User_ID, flightType, Flight_agency, Departure_date, Departure, Arrival, Flight Distance (km), Flight Duration (hh:mm), Departure Time, Arrival Time, Calculated_Flight_Price]
Index: []

In [201]:
Hetvi_2_UserId = pd.read_excel('dataset_user_2.xlsx')
Hetvi_4_UserId = pd.read_excel('dataset_user_4.xlsx')
Hetvi_6_UserId = pd.read_excel('dataset_user_6.xlsx')

In [202]:
Hetvi_2_UserId

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,503,4,firstClass,Air India,25/03/2021,Itanagar,Surat,2204.62,02:26,00:56,03:22,12220.60
1,590,4,economic,SpiceJet,24/11/2022,Surat,Itanagar,2204.62,02:26,04:18,06:44,7562.36
2,1479,13,economic,IndiGo,07/09/2020,Bengaluru,Visakhapatnam,797.17,00:53,01:41,02:34,3110.76
3,1507,13,economic,SpiceJet,21/01/2021,Visakhapatnam,Bengaluru,797.17,00:53,08:07,09:00,3330.76
4,1666,15,firstClass,Air India,28/11/2019,Chandigarh,Navi Mumbai,1355.13,01:30,11:12,12:42,7763.15
...,...,...,...,...,...,...,...,...,...,...,...,...
383,133540,1315,economic,Akasa Air,04/07/2022,Delhi NCR,Shimla,271.89,00:18,13:48,14:06,1456.17
384,134586,1323,premium,Air India,16/12/2021,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84
385,134613,1323,firstClass,Akasa Air,23/06/2022,Dehradun,Hyderabad,1439.54,01:35,22:00,23:35,8153.95
386,135670,1335,firstClass,IndiGo,28/11/2019,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25
387,135799,1335,premium,Akasa Air,19/05/2022,Kota,Raigarh,3289.60,03:39,22:43,02:22,13033.86

In [210]:
Hetvi_4_UserId

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,3392,34,firstClass,GoAir,05/07/2020,Ayodhya,Khowai,991.41,01:06,01:34,02:40,5814.55
1,3441,34,premium,Air India,15/04/2021,Mysuru,Bhopal,1221.01,01:21,19:40,21:01,5464.34
2,3442,34,premium,Air India,22/04/2021,Khowai,Ayodhya,991.41,01:06,23:29,00:35,4397.28
3,3498,34,firstClass,Air India,19/05/2022,Bhopal,Mysuru,1221.01,01:21,07:30,08:51,7258.80
4,6385,63,firstClass,SpiceJet,11/07/2019,Thiruvananthapuram,Vijayawada,977.99,01:05,21:57,23:02,5953.70
...,...,...,...,...,...,...,...,...,...,...,...,...
135,111482,1104,firstClass,GoAir,12/09/2021,Jamshedpur,Amritsar,1485.71,01:39,04:27,06:06,8409.80
136,117586,1165,economic,Akasa Air,31/10/2019,Kullu-Manali,Bhubaneswar,1552.98,01:43,10:49,12:32,5490.69
137,117598,1165,economic,IndiGo,23/01/2020,Bhubaneswar,Kullu-Manali,1552.98,01:43,19:50,21:33,5690.69
138,117647,1165,firstClass,Air India,31/12/2020,Kota,Indore,2510.59,02:47,06:25,09:12,14029.20
139,117742,1165,firstClass,GoAir,27/10/2022,Indore,Kota,2510.59,02:47,21:21,00:08,13989.20

In [216]:
Hetvi_6_UserId

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,9126,93,economic,Akasa Air,11/07/2019,Ludhiana,Dabolim,1739.21,01:55,04:33,06:28,6076.38
1,9137,93,premium,IndiGo,23/01/2020,Hyderabad,Bilaspur,649.95,00:43,13:22,14:05,3055.92
2,9148,93,economic,Akasa Air,04/09/2020,Guwahati,Puducherry,2016.86,02:14,14:32,16:46,6952.08
3,9175,93,economic,IndiGo,15/10/2020,Dabolim,Ludhiana,1739.21,01:55,19:29,21:24,6276.38
4,9218,93,firstClass,AirAsia India,08/12/2021,Puducherry,Guwahati,2016.86,02:14,14:39,16:53,11186.80
5,9231,93,economic,Akasa Air,11/11/2021,Bilaspur,Hyderabad,649.95,00:43,04:22,05:05,2646.60
6,65993,641,firstClass,Akasa Air,13/08/2020,Surat,Hyderabad,726.71,00:48,15:24,16:12,4413.55
7,66020,641,firstClass,AirAsia India,18/02/2021,Hyderabad,Surat,726.71,00:48,17:28,18:16,4413.55
8,66027,641,firstClass,Akasa Air,04/08/2021,Surat,Nashik,166.63,00:11,15:57,16:08,1474.40
9,66044,641,economic,Akasa Air,08/05/2021,Navi Mumbai,Dabolim,415.65,00:27,11:37,12:04,1907.70
10,66046,641,economic,Akasa Air,19/08/2021,Nashik,Surat,166.63,00:11,05:34,05:45,1124.64
11,66048,641,economic,Air India,09/02/2021,Dabolim,Navi Mumbai,415.65,00:27,01:11,01:38,1957.70
12,75623,737,premium,Air India,10/10/2019,Coimbatore,Puri,1362.16,01:30,20:17,21:47,5996.78
13,75625,737,firstClass,Air India,24/10/2019,Puri,Coimbatore,1362.16,01:30,20:20,21:50,7998.30
14,75645,737,premium,Air India,03/12/2020,Puducherry,Puri,1084.01,01:12,22:19,23:31,4746.84
15,75681,737,economic,Akasa Air,19/11/2020,Jaipur,Mumbai,921.69,01:01,10:02,11:03,3502.32
16,75724,737,firstClass,GoAir,16/09/2021,Mumbai,Jaipur,921.69,01:01,20:17,21:18,5647.20
17,75750,737,premium,IndiGo,17/03/2022,Puri,Puducherry,1084.01,01:12,09:34,10:46,4896.84
18,104683,1039,firstClass,SpiceJet,29/04/2021,Visakhapatnam,Raigarh,469.41,00:31,18:18,18:49,3283.30
19,104725,1039,premium,Air India,17/02/2022,Bilaspur,Ranchi,352.67,00:23,06:26,06:49,2181.71
20,104726,1039,economic,Akasa Air,24/02/2022,Raigarh,Visakhapatnam,469.41,00:31,03:29,04:00,2077.98
21,104731,1039,firstClass,SpiceJet,31/03/2022,Ranchi,Bilaspur,352.67,00:23,06:00,06:23,2669.60
22,104733,1039,firstClass,AirAsia India,14/04/2022,Delhi NCR,Amritsar,391.51,00:26,02:50,03:16,2655.05
23,104753,1039,economic,IndiGo,09/01/2022,Amritsar,Delhi NCR,391.51,00:26,03:06,03:32,1833.03
24,104985,1041,firstClass,Air India,23/07/2020,Chandigarh,Kullu-Manali,131.49,00:08,10:29,10:37,1337.45
25,105002,1041,firstClass,SpiceJet,19/11/2020,Chennai,Mysuru,404.42,00:26,14:19,14:45,2739.60
26,105006,1041,economic,Akasa Air,17/12/2020,Kullu-Manali,Chandigarh,131.49,00:08,22:27,22:35,1012.47
27,105088,1041,firstClass,AirAsia India,14/07/2022,Guwahati,Thiruvananthapuram,2512.60,02:47,07:21,10:08,13989.25
28,105129,1041,premium,Air India,27/04/2023,Thiruvananthapuram,Guwahati,2512.60,02:47,18:38,21:25,10346.26
29,105134,1041,economic,IndiGo,06/01/2023,Mysuru,Chennai,404.42,00:26,12:51,13:17,1871.76
30,130646,1286,firstClass,SpiceJet,25/06/2020,Shimla,Jamshedpur,1283.89,01:25,11:11,12:36,7358.20
31,130650,1286,firstClass,SpiceJet,23/07/2020,Mopa,Srinagar,7566.74,08:24,09:11,17:35,40543.70
32,130685,1286,firstClass,Air India,25/03/2021,Srinagar,Mopa,7566.74,08:24,17:11,01:35,40373.70
33,130688,1286,premium,Air India,15/04/2021,Chennai,Puducherry,137.25,00:09,09:08,09:17,1368.40
34,130696,1286,firstClass,GoAir,06/10/2021,Puducherry,Chennai,137.25,00:09,19:13,19:22,1530.00
35,130775,1286,firstClass,Air India,15/12/2022,Jamshedpur,Shimla,1283.89,01:25,05:35,07:00,7388.20

In [219]:
Hetvi_3_UserId = pd.read_excel('users_3_occurrences.xlsx')

In [220]:
Hetvi_3_UserId

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,46192,450,firstClass,GoAir,13/02/2020,Puducherry,Varanasi,1525.15,01:41,02:00,03:41,8614.50
1,46247,450,firstClass,Air India,2020-02-26 00:00:00,Varanasi,Puducherry,1525.15,01:41,23:36,01:17,8654.50
2,46309,450,economic,Air India,05/12/2022,Puducherry,Varanasi,1525.15,01:41,10:29,12:10,5452.70
3,96876,958,firstClass,AirAsia India,04/09/2020,Mopa,Amritsar,7551.25,08:23,00:31,08:54,40242.50
4,96954,958,premium,IndiGo,2020-09-10 00:00:00,Amritsar,Mopa,7551.25,08:23,11:04,19:27,29142.60
5,96982,958,economic,Akasa Air,21/04/2022,Amritsar,Mopa,7551.25,08:23,06:25,14:48,24585.50
6,111856,1108,premium,Akasa Air,14/05/2020,Hisar,Shillong,6610.02,07:20,21:09,04:29,25784.07
7,111935,1108,premium,IndiGo,18/11/2021,Hisar,Shillong,6610.02,07:20,19:11,02:31,25784.07
8,111957,1108,firstClass,AirAsia India,2021-11-28 00:00:00,Shillong,Hisar,6610.02,07:20,14:56,22:16,35300.10

In [209]:
Hetvi_modified_2 = pd.read_excel('modified_dataset.xlsx')
Hetvi_modified_2

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,503,4,firstClass,Air India,2021-03-25,Itanagar,Surat,2204.62,02:26,00:56,03:22,12220.60
1,590,4,economic,SpiceJet,2021-04-02,Surat,Itanagar,2204.62,02:26,04:18,06:44,7562.36
2,1479,13,economic,IndiGo,2020-09-07,Bengaluru,Visakhapatnam,797.17,00:53,01:41,02:34,3110.76
3,1507,13,economic,SpiceJet,2020-09-15,Visakhapatnam,Bengaluru,797.17,00:53,08:07,09:00,3330.76
4,1666,15,firstClass,Air India,2019-11-28,Chandigarh,Navi Mumbai,1355.13,01:30,11:12,12:42,7763.15
...,...,...,...,...,...,...,...,...,...,...,...,...
383,133540,1315,economic,Akasa Air,2021-06-17,Delhi NCR,Shimla,271.89,00:18,13:48,14:06,1456.17
384,134586,1323,premium,Air India,2021-12-16,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84
385,134613,1323,firstClass,Akasa Air,2021-12-30,Dehradun,Hyderabad,1439.54,01:35,22:00,23:35,8153.95
386,135670,1335,firstClass,IndiGo,2019-11-28,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25
387,135799,1335,premium,Akasa Air,2019-12-06,Kota,Raigarh,3289.60,03:39,22:43,02:22,13033.86

In [211]:
Hetvi_4_UserId = pd.read_excel('dataset_user_4.xlsx')

In [212]:
Hetvi_4_UserId

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,3392,34,firstClass,GoAir,05/07/2020,Ayodhya,Khowai,991.41,01:06,01:34,02:40,5814.55
1,3441,34,premium,Air India,15/04/2021,Mysuru,Bhopal,1221.01,01:21,19:40,21:01,5464.34
2,3442,34,premium,Air India,2020-07-12 00:00:00,Khowai,Ayodhya,991.41,01:06,23:29,00:35,4397.28
3,3498,34,firstClass,Air India,2021-05-22 00:00:00,Bhopal,Mysuru,1221.01,01:21,07:30,08:51,7258.80
4,6385,63,firstClass,SpiceJet,11/07/2019,Thiruvananthapuram,Vijayawada,977.99,01:05,21:57,23:02,5953.70
...,...,...,...,...,...,...,...,...,...,...,...,...
135,111482,1104,firstClass,GoAir,2021-01-02 00:00:00,Jamshedpur,Amritsar,1485.71,01:39,04:27,06:06,8409.80
136,117586,1165,economic,Akasa Air,31/10/2019,Kullu-Manali,Bhubaneswar,1552.98,01:43,10:49,12:32,5490.69
137,117598,1165,economic,IndiGo,2019-11-03 00:00:00,Bhubaneswar,Kullu-Manali,1552.98,01:43,19:50,21:33,5690.69
138,117647,1165,firstClass,Air India,31/12/2020,Kota,Indore,2510.59,02:47,06:25,09:12,14029.20
139,117742,1165,firstClass,GoAir,2021-01-02 00:00:00,Indore,Kota,2510.59,02:47,21:21,00:08,13989.20

In [213]:
Hetvi_modified_4 = Hetvi_4_UserId.copy()

In [214]:
Hetvi_modified_4

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,3392,34,firstClass,GoAir,05/07/2020,Ayodhya,Khowai,991.41,01:06,01:34,02:40,5814.55
1,3441,34,premium,Air India,15/04/2021,Mysuru,Bhopal,1221.01,01:21,19:40,21:01,5464.34
2,3442,34,premium,Air India,2020-07-12 00:00:00,Khowai,Ayodhya,991.41,01:06,23:29,00:35,4397.28
3,3498,34,firstClass,Air India,2021-05-22 00:00:00,Bhopal,Mysuru,1221.01,01:21,07:30,08:51,7258.80
4,6385,63,firstClass,SpiceJet,11/07/2019,Thiruvananthapuram,Vijayawada,977.99,01:05,21:57,23:02,5953.70
...,...,...,...,...,...,...,...,...,...,...,...,...
135,111482,1104,firstClass,GoAir,2021-01-02 00:00:00,Jamshedpur,Amritsar,1485.71,01:39,04:27,06:06,8409.80
136,117586,1165,economic,Akasa Air,31/10/2019,Kullu-Manali,Bhubaneswar,1552.98,01:43,10:49,12:32,5490.69
137,117598,1165,economic,IndiGo,2019-11-03 00:00:00,Bhubaneswar,Kullu-Manali,1552.98,01:43,19:50,21:33,5690.69
138,117647,1165,firstClass,Air India,31/12/2020,Kota,Indore,2510.59,02:47,06:25,09:12,14029.20
139,117742,1165,firstClass,GoAir,2021-01-02 00:00:00,Indore,Kota,2510.59,02:47,21:21,00:08,13989.20

In [217]:
Hetvi_6_UserId = pd.read_excel('dataset_user_6.xlsx')

In [218]:
Hetvi_modified_6 = Hetvi_6_UserId.copy()
Hetvi_6_UserId

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,9126,93,economic,Akasa Air,11/07/2019,Ludhiana,Dabolim,1739.21,01:55,04:33,06:28,6076.38
1,9137,93,premium,IndiGo,23/01/2020,Hyderabad,Bilaspur,649.95,00:43,13:22,14:05,3055.92
2,9148,93,economic,Akasa Air,04/09/2020,Guwahati,Puducherry,2016.86,02:14,14:32,16:46,6952.08
3,9175,93,economic,IndiGo,2019-07-15 00:00:00,Dabolim,Ludhiana,1739.21,01:55,19:29,21:24,6276.38
4,9218,93,firstClass,AirAsia India,2020-09-08 00:00:00,Puducherry,Guwahati,2016.86,02:14,14:39,16:53,11186.80
5,9231,93,economic,Akasa Air,2020-01-30 00:00:00,Bilaspur,Hyderabad,649.95,00:43,04:22,05:05,2646.60
6,65993,641,firstClass,Akasa Air,13/08/2020,Surat,Hyderabad,726.71,00:48,15:24,16:12,4413.55
7,66020,641,firstClass,AirAsia India,2020-08-18 00:00:00,Hyderabad,Surat,726.71,00:48,17:28,18:16,4413.55
8,66027,641,firstClass,Akasa Air,04/08/2021,Surat,Nashik,166.63,00:11,15:57,16:08,1474.40
9,66044,641,economic,Akasa Air,08/05/2021,Navi Mumbai,Dabolim,415.65,00:27,11:37,12:04,1907.70
10,66046,641,economic,Akasa Air,2021-08-19 00:00:00,Nashik,Surat,166.63,00:11,05:34,05:45,1124.64
11,66048,641,economic,Air India,2021-05-19 00:00:00,Dabolim,Navi Mumbai,415.65,00:27,01:11,01:38,1957.70
12,75623,737,premium,Air India,10/10/2019,Coimbatore,Puri,1362.16,01:30,20:17,21:47,5996.78
13,75625,737,firstClass,Air India,24/10/2019,Puri,Coimbatore,1362.16,01:30,20:20,21:50,7998.30
14,75645,737,premium,Air India,03/12/2020,Puducherry,Puri,1084.01,01:12,22:19,23:31,4746.84
15,75681,737,economic,Akasa Air,19/11/2020,Jaipur,Mumbai,921.69,01:01,10:02,11:03,3502.32
16,75724,737,firstClass,GoAir,2020-11-26 00:00:00,Mumbai,Jaipur,921.69,01:01,20:17,21:18,5647.20
17,75750,737,premium,IndiGo,2020-12-17 00:00:00,Puri,Puducherry,1084.01,01:12,09:34,10:46,4896.84
18,104683,1039,firstClass,SpiceJet,2021-04-29 00:00:00,Visakhapatnam,Raigarh,469.41,00:31,18:18,18:49,3283.30
19,104725,1039,premium,Air India,2022-02-17 00:00:00,Bilaspur,Ranchi,352.67,00:23,06:26,06:49,2181.71
20,104726,1039,economic,Akasa Air,2021-05-09 00:00:00,Raigarh,Visakhapatnam,469.41,00:31,03:29,04:00,2077.98
21,104731,1039,firstClass,SpiceJet,31/02/2022,Ranchi,Bilaspur,352.67,00:23,06:00,06:23,2669.60
22,104733,1039,firstClass,AirAsia India,14/04/2022,Delhi NCR,Amritsar,391.51,00:26,02:50,03:16,2655.05
23,104753,1039,economic,IndiGo,2022-04-19 00:00:00,Amritsar,Delhi NCR,391.51,00:26,03:06,03:32,1833.03
24,104985,1041,firstClass,Air India,23/07/2020,Chandigarh,Kullu-Manali,131.49,00:08,10:29,10:37,1337.45
25,105002,1041,firstClass,SpiceJet,19/11/2020,Chennai,Mysuru,404.42,00:26,14:19,14:45,2739.60
26,105006,1041,economic,Akasa Air,2020-08-01 00:00:00,Kullu-Manali,Chandigarh,131.49,00:08,22:27,22:35,1012.47
27,105088,1041,firstClass,AirAsia India,14/07/2022,Guwahati,Thiruvananthapuram,2512.60,02:47,07:21,10:08,13989.25
28,105129,1041,premium,Air India,2022-07-27 00:00:00,Thiruvananthapuram,Guwahati,2512.60,02:47,18:38,21:25,10346.26
29,105134,1041,economic,IndiGo,2020-11-26 00:00:00,Mysuru,Chennai,404.42,00:26,12:51,13:17,1871.76
30,130646,1286,firstClass,SpiceJet,25/06/2020,Shimla,Jamshedpur,1283.89,01:25,11:11,12:36,7358.20
31,130650,1286,firstClass,SpiceJet,23/07/2020,Mopa,Srinagar,7566.74,08:24,09:11,17:35,40543.70
32,130685,1286,firstClass,Air India,2020-07-28 00:00:00,Srinagar,Mopa,7566.74,08:24,17:11,01:35,40373.70
33,130688,1286,premium,Air India,15/04/2021,Chennai,Puducherry,137.25,00:09,09:08,09:17,1368.40
34,130696,1286,firstClass,GoAir,2021-04-26 00:00:00,Puducherry,Chennai,137.25,00:09,19:13,19:22,1530.00
35,130775,1286,firstClass,Air India,2020-06-28 00:00:00,Jamshedpur,Shimla,1283.89,01:25,05:35,07:00,7388.20

In [222]:
Hetvi_modified_3 = Hetvi_3_UserId.copy()
Hetvi_3_UserId

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,46192,450,firstClass,GoAir,13/02/2020,Puducherry,Varanasi,1525.15,01:41,02:00,03:41,8614.50
1,46247,450,firstClass,Air India,2020-02-26 00:00:00,Varanasi,Puducherry,1525.15,01:41,23:36,01:17,8654.50
2,46309,450,economic,Air India,05/12/2022,Puducherry,Varanasi,1525.15,01:41,10:29,12:10,5452.70
3,96876,958,firstClass,AirAsia India,04/09/2020,Mopa,Amritsar,7551.25,08:23,00:31,08:54,40242.50
4,96954,958,premium,IndiGo,2020-09-10 00:00:00,Amritsar,Mopa,7551.25,08:23,11:04,19:27,29142.60
5,96982,958,economic,Akasa Air,21/04/2022,Amritsar,Mopa,7551.25,08:23,06:25,14:48,24585.50
6,111856,1108,premium,Akasa Air,14/05/2020,Hisar,Shillong,6610.02,07:20,21:09,04:29,25784.07
7,111935,1108,premium,IndiGo,18/11/2021,Hisar,Shillong,6610.02,07:20,19:11,02:31,25784.07
8,111957,1108,firstClass,AirAsia India,2021-11-28 00:00:00,Shillong,Hisar,6610.02,07:20,14:56,22:16,35300.10

In [224]:
merged_hetvi = pd.concat([Hetvi_3_UserId, Hetvi_6_UserId, Hetvi_modified_4, Hetvi_modified_2])
merged_hetvi

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,46192,450,firstClass,GoAir,13/02/2020,Puducherry,Varanasi,1525.15,01:41,02:00,03:41,8614.50
1,46247,450,firstClass,Air India,2020-02-26 00:00:00,Varanasi,Puducherry,1525.15,01:41,23:36,01:17,8654.50
2,46309,450,economic,Air India,05/12/2022,Puducherry,Varanasi,1525.15,01:41,10:29,12:10,5452.70
3,96876,958,firstClass,AirAsia India,04/09/2020,Mopa,Amritsar,7551.25,08:23,00:31,08:54,40242.50
4,96954,958,premium,IndiGo,2020-09-10 00:00:00,Amritsar,Mopa,7551.25,08:23,11:04,19:27,29142.60
...,...,...,...,...,...,...,...,...,...,...,...,...
383,133540,1315,economic,Akasa Air,2021-06-17 00:00:00,Delhi NCR,Shimla,271.89,00:18,13:48,14:06,1456.17
384,134586,1323,premium,Air India,2021-12-16 00:00:00,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84
385,134613,1323,firstClass,Akasa Air,2021-12-30 00:00:00,Dehradun,Hyderabad,1439.54,01:35,22:00,23:35,8153.95
386,135670,1335,firstClass,IndiGo,2019-11-28 00:00:00,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25
387,135799,1335,premium,Akasa Air,2019-12-06 00:00:00,Kota,Raigarh,3289.60,03:39,22:43,02:22,13033.86

In [225]:
merged_hetvi = merged_hetvi.sort_values(by="User_ID", ascending=True)
merged_hetvi

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
1,590,4,economic,SpiceJet,2021-04-02 00:00:00,Surat,Itanagar,2204.62,02:26,04:18,06:44,7562.36
0,503,4,firstClass,Air India,2021-03-25 00:00:00,Itanagar,Surat,2204.62,02:26,00:56,03:22,12220.60
3,1507,13,economic,SpiceJet,2020-09-15 00:00:00,Visakhapatnam,Bengaluru,797.17,00:53,08:07,09:00,3330.76
2,1479,13,economic,IndiGo,2020-09-07 00:00:00,Bengaluru,Visakhapatnam,797.17,00:53,01:41,02:34,3110.76
4,1666,15,firstClass,Air India,2019-11-28 00:00:00,Chandigarh,Navi Mumbai,1355.13,01:30,11:12,12:42,7763.15
...,...,...,...,...,...,...,...,...,...,...,...,...
383,133540,1315,economic,Akasa Air,2021-06-17 00:00:00,Delhi NCR,Shimla,271.89,00:18,13:48,14:06,1456.17
384,134586,1323,premium,Air India,2021-12-16 00:00:00,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84
385,134613,1323,firstClass,Akasa Air,2021-12-30 00:00:00,Dehradun,Hyderabad,1439.54,01:35,22:00,23:35,8153.95
386,135670,1335,firstClass,IndiGo,2019-11-28 00:00:00,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25
387,135799,1335,premium,Akasa Air,2019-12-06 00:00:00,Kota,Raigarh,3289.60,03:39,22:43,02:22,13033.86

In [226]:
Round_Trip_Final = merged_hetvi.copy()

In [227]:
Round_Trip_Final

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
1,590,4,economic,SpiceJet,2021-04-02 00:00:00,Surat,Itanagar,2204.62,02:26,04:18,06:44,7562.36
0,503,4,firstClass,Air India,2021-03-25 00:00:00,Itanagar,Surat,2204.62,02:26,00:56,03:22,12220.60
3,1507,13,economic,SpiceJet,2020-09-15 00:00:00,Visakhapatnam,Bengaluru,797.17,00:53,08:07,09:00,3330.76
2,1479,13,economic,IndiGo,2020-09-07 00:00:00,Bengaluru,Visakhapatnam,797.17,00:53,01:41,02:34,3110.76
4,1666,15,firstClass,Air India,2019-11-28 00:00:00,Chandigarh,Navi Mumbai,1355.13,01:30,11:12,12:42,7763.15
...,...,...,...,...,...,...,...,...,...,...,...,...
383,133540,1315,economic,Akasa Air,2021-06-17 00:00:00,Delhi NCR,Shimla,271.89,00:18,13:48,14:06,1456.17
384,134586,1323,premium,Air India,2021-12-16 00:00:00,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84
385,134613,1323,firstClass,Akasa Air,2021-12-30 00:00:00,Dehradun,Hyderabad,1439.54,01:35,22:00,23:35,8153.95
386,135670,1335,firstClass,IndiGo,2019-11-28 00:00:00,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25
387,135799,1335,premium,Akasa Air,2019-12-06 00:00:00,Kota,Raigarh,3289.60,03:39,22:43,02:22,13033.86

In [231]:
Hetviii = Hetvi.copy()
Hetviii

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,flight_number
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,G81069B
1,2,0,firstClass,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,6E828
2,7,0,economic,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,AI297
3,11,0,premium,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,SG6667
4,13,0,firstClass,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,G81820C
...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,AI690D
40548,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,QP1902B
40549,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,QP1196D
40550,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,6E978
40551,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,6E276

In [229]:
hetviii = hetviii[~hetviii.index.isin(Round_Trip_Final.index)]
hetviii

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,flight_number
388,1371,12,economic,Akasa Air,17/10/2019,Vadodara,Shimla,1054.83,01:10,09:05,10:15,QP1726B
389,1378,12,firstClass,SpiceJet,12/05/2019,Kolkata,Raigarh,516.49,00:34,00:59,01:33,SG7506B
390,1380,12,economic,IndiGo,19/12/2019,Srinagar,Vadodara,1319.83,01:27,06:00,07:27,6E633D
391,1383,12,firstClass,GoAir,01/09/2020,Prayagraj,Puri,749.01,00:49,15:09,15:58,G81184F
392,1388,12,firstClass,SpiceJet,13/02/2020,Bengaluru,Mysuru,127.83,00:08,06:01,06:09,SG4056B
...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,AI690D
40548,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,QP1902B
40549,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,QP1196D
40550,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,6E978
40551,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,6E276

In [232]:
Hetviii.index

RangeIndex(start=0, stop=40552, step=1)

In [233]:
Round_Trip_Final.index

Index([  1,   0,   3,   2,   4,   5,   6,   7,   8,   9,
       ...
       379, 378, 380, 381, 382, 383, 384, 385, 386, 387],
      dtype='int64', length=573)

In [234]:
round_trip_df.index

Index([  146,   171,   426,   434,   472,   514,   597,   599,   691,   708,
       ...
       39595, 39599, 39679, 39686, 39828, 39839, 40151, 40161, 40470, 40502],
      dtype='int64', length=573)

In [235]:
Hetviii[~Hetviii.index.isin(Round_Trip_Final.index)]

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,flight_number
388,1371,12,economic,Akasa Air,17/10/2019,Vadodara,Shimla,1054.83,01:10,09:05,10:15,QP1726B
389,1378,12,firstClass,SpiceJet,12/05/2019,Kolkata,Raigarh,516.49,00:34,00:59,01:33,SG7506B
390,1380,12,economic,IndiGo,19/12/2019,Srinagar,Vadodara,1319.83,01:27,06:00,07:27,6E633D
391,1383,12,firstClass,GoAir,01/09/2020,Prayagraj,Puri,749.01,00:49,15:09,15:58,G81184F
392,1388,12,firstClass,SpiceJet,13/02/2020,Bengaluru,Mysuru,127.83,00:08,06:01,06:09,SG4056B
...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,AI690D
40548,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,QP1902B
40549,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,QP1196D
40550,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,6E978
40551,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,6E276

In [238]:
oneway_Trip_Final = Hetviii[~Hetviii['travelCode'].isin(round_trip_df['travelCode'])]
oneway_Trip_Final

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,flight_number
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,G81069B
1,2,0,firstClass,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,6E828
2,7,0,economic,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,AI297
3,11,0,premium,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,SG6667
4,13,0,firstClass,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,G81820C
...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,AI690D
40548,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,QP1902B
40549,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,QP1196D
40550,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,6E978
40551,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,6E276

In [244]:
Round_Trip_Final = Round_Trip_Final.reset_index(drop=True)
Round_Trip_Final

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,503,4,firstClass,Air India,2021-03-25 00:00:00,Itanagar,Surat,2204.62,02:26,00:56,03:22,12220.60
1,590,4,economic,SpiceJet,2021-04-02 00:00:00,Surat,Itanagar,2204.62,02:26,04:18,06:44,7562.36
2,1479,13,economic,IndiGo,2020-09-07 00:00:00,Bengaluru,Visakhapatnam,797.17,00:53,01:41,02:34,3110.76
3,1507,13,economic,SpiceJet,2020-09-15 00:00:00,Visakhapatnam,Bengaluru,797.17,00:53,08:07,09:00,3330.76
4,1666,15,firstClass,Air India,2019-11-28 00:00:00,Chandigarh,Navi Mumbai,1355.13,01:30,11:12,12:42,7763.15
...,...,...,...,...,...,...,...,...,...,...,...,...
568,133540,1315,economic,Akasa Air,2021-06-17 00:00:00,Delhi NCR,Shimla,271.89,00:18,13:48,14:06,1456.17
569,134586,1323,premium,Air India,2021-12-16 00:00:00,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84
570,134613,1323,firstClass,Akasa Air,2021-12-30 00:00:00,Dehradun,Hyderabad,1439.54,01:35,22:00,23:35,8153.95
571,135670,1335,firstClass,IndiGo,2019-11-28 00:00:00,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25
572,135799,1335,premium,Akasa Air,2019-12-06 00:00:00,Kota,Raigarh,3289.60,03:39,22:43,02:22,13033.86

In [243]:
Round_Trip_Final = Round_Trip_Final.sort_values(by="travelCode", ascending=True)
Round_Trip_Final

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
1,503,4,firstClass,Air India,2021-03-25 00:00:00,Itanagar,Surat,2204.62,02:26,00:56,03:22,12220.60
0,590,4,economic,SpiceJet,2021-04-02 00:00:00,Surat,Itanagar,2204.62,02:26,04:18,06:44,7562.36
3,1479,13,economic,IndiGo,2020-09-07 00:00:00,Bengaluru,Visakhapatnam,797.17,00:53,01:41,02:34,3110.76
2,1507,13,economic,SpiceJet,2020-09-15 00:00:00,Visakhapatnam,Bengaluru,797.17,00:53,08:07,09:00,3330.76
4,1666,15,firstClass,Air India,2019-11-28 00:00:00,Chandigarh,Navi Mumbai,1355.13,01:30,11:12,12:42,7763.15
...,...,...,...,...,...,...,...,...,...,...,...,...
568,133540,1315,economic,Akasa Air,2021-06-17 00:00:00,Delhi NCR,Shimla,271.89,00:18,13:48,14:06,1456.17
569,134586,1323,premium,Air India,2021-12-16 00:00:00,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84
570,134613,1323,firstClass,Akasa Air,2021-12-30 00:00:00,Dehradun,Hyderabad,1439.54,01:35,22:00,23:35,8153.95
571,135670,1335,firstClass,IndiGo,2019-11-28 00:00:00,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25
572,135799,1335,premium,Akasa Air,2019-12-06 00:00:00,Kota,Raigarh,3289.60,03:39,22:43,02:22,13033.86

In [245]:
Round_Trip_Final

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price
0,503,4,firstClass,Air India,2021-03-25 00:00:00,Itanagar,Surat,2204.62,02:26,00:56,03:22,12220.60
1,590,4,economic,SpiceJet,2021-04-02 00:00:00,Surat,Itanagar,2204.62,02:26,04:18,06:44,7562.36
2,1479,13,economic,IndiGo,2020-09-07 00:00:00,Bengaluru,Visakhapatnam,797.17,00:53,01:41,02:34,3110.76
3,1507,13,economic,SpiceJet,2020-09-15 00:00:00,Visakhapatnam,Bengaluru,797.17,00:53,08:07,09:00,3330.76
4,1666,15,firstClass,Air India,2019-11-28 00:00:00,Chandigarh,Navi Mumbai,1355.13,01:30,11:12,12:42,7763.15
...,...,...,...,...,...,...,...,...,...,...,...,...
568,133540,1315,economic,Akasa Air,2021-06-17 00:00:00,Delhi NCR,Shimla,271.89,00:18,13:48,14:06,1456.17
569,134586,1323,premium,Air India,2021-12-16 00:00:00,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84
570,134613,1323,firstClass,Akasa Air,2021-12-30 00:00:00,Dehradun,Hyderabad,1439.54,01:35,22:00,23:35,8153.95
571,135670,1335,firstClass,IndiGo,2019-11-28 00:00:00,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25
572,135799,1335,premium,Akasa Air,2019-12-06 00:00:00,Kota,Raigarh,3289.60,03:39,22:43,02:22,13033.86

In [246]:
Round_Trip_Final.to_excel('Round_Trip_Final.xlsx',index=False)
from IPython.display import FileLink
FileLink('Round_Trip_Final.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\Round_Trip_Final.xlsx

In [247]:
oneway_Trip_Final.to_excel('oneway_Trip_Final.xlsx',index=False)
from IPython.display import FileLink
FileLink('oneway_Trip_Final.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\oneway_Trip_Final.xlsx

In [248]:
Hetvi

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,flight_number
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,G81069B
1,2,0,firstClass,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,6E828
2,7,0,economic,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,AI297
3,11,0,premium,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,SG6667
4,13,0,firstClass,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,G81820C
...,...,...,...,...,...,...,...,...,...,...,...,...
40547,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,AI690D
40548,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,QP1902B
40549,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,QP1196D
40550,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,6E978
40551,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,6E276

In [252]:
Cities_ = Hetvi['Departure'].unique()

In [258]:
Location_Table = pd.DataFrame({'City': Cities_})
Location_Table

                  City
0           Coimbatore
1               Ranchi
2              Dabolim
3            Ahmedabad
4            Hyderabad
5               Khowai
6          Navi Mumbai
7                 Pune
8           Vijayawada
9              Gwalior
10           Bengaluru
11            Guwahati
12            Bilaspur
13              Raipur
14          Puducherry
15          Jamshedpur
16              Nashik
17                Mopa
18           Prayagraj
19            Vadodara
20            Ludhiana
21             Raigarh
22             Chennai
23                Puri
24            Tirupati
25            Dehradun
26            Srinagar
27           Delhi NCR
28            Itanagar
29            Varanasi
30              Dhubri
31             Kolkata
32             Gangtok
33            Shillong
34            Amritsar
35              Bhopal
36              Jaipur
37        Kullu-Manali
38             Ayodhya
39         Bhubaneswar
40  Thiruvananthapuram
41                Kota
42               Surat
43             Udaipur
44                 Diu
45          Chandigarh
46              Shimla
47              Imphal
48               Hisar
49       Visakhapatnam
50              Indore
51              Mysuru
52               Patna
53              Mumbai

In [259]:
nearest_airports = [
    "Coimbatore International Airport (CJB)",
    "Birsa Munda Airport (IXR)",
    "Goa International Airport (GOI)",
    "Sardar Vallabhbhai Patel International Airport (AMD)",
    "Rajiv Gandhi International Airport (HYD)",
    "Agartala Airport (IXA)",
    "Chhatrapati Shivaji Maharaj International Airport (BOM)",
    "Pune International Airport (PNQ)",
    "Vijayawada Airport (VGA)",
    "Gwalior Airport (GWL)",
    "Kempegowda International Airport (BLR)",
    "Lokpriya Gopinath Bordoloi International Airport (GAU)",
    "Bilaspur Airport (PAB)",
    "Swami Vivekananda Airport (RPR)",
    "Puducherry Airport (PNY)",
    "Sonari Airport (IXW)",
    "Nashik International Airport (ISK)",
    "Mopa International Airport (GOX)",
    "Prayagraj Airport (IXD)",
    "Vadodara Airport (BDQ)",
    "Ludhiana Airport (LUH)",
    "Raigarh Airport (None)",
    "Chennai International Airport (MAA)",
    "Biju Patnaik International Airport (BBI)",
    "Tirupati Airport (TIR)",
    "Dehradun Airport (DED)",
    "Sheikh ul-Alam International Airport (SXR)",
    "Indira Gandhi International Airport (DEL)",
    "Donyi Polo Airport (HGI)",
    "Lal Bahadur Shastri International Airport (VNS)",
    "Rupsi Airport (RUP)",
    "Netaji Subhas Chandra Bose International Airport (CCU)",
    "Pakyong Airport (PYG)",
    "Shillong Airport (SHL)",
    "Sri Guru Ram Dass Jee International Airport (ATQ)",
    "Raja Bhoj Airport (BHO)",
    "Jaipur International Airport (JAI)",
    "Kullu–Manali Airport (KUU)",
    "Ayodhya Airport (under construction)",
    "Biju Patnaik International Airport (BBI)",
    "Trivandrum International Airport (TRV)",
    "Kota Airport (KTU)",
    "Surat Airport (STV)",
    "Maharana Pratap Airport (UDR)",
    "Diu Airport (DIU)",
    "Chandigarh International Airport (IXC)",
    "Shimla Airport (SLV)",
    "Imphal International Airport (IMF)",
    "Hisar Airport (HSS)",
    "Visakhapatnam Airport (VTZ)",
    "Devi Ahilya Bai Holkar Airport (IDR)",
    "Mysore Airport (MYQ)",
    "Jay Prakash Narayan Airport (PAT)",
    "Chhatrapati Shivaji Maharaj International Airport (BOM)"
]

In [264]:
Location_Table = pd.DataFrame({'Name': nearest_airports, 'Address': nearest_airport_addresses, 'City': Cities_})
Location_Table

,Name,Address,City
0,Coimbatore International Airport (CJB),"Coimbatore International Airport, Avinashi Roa...",Coimbatore
1,Birsa Munda Airport (IXR),"Birsa Munda Airport, Hinoo, Ranchi, Jharkhand ...",Ranchi
2,Goa International Airport (GOI),"Goa International Airport, Airport Road, Dabol...",Dabolim
3,Sardar Vallabhbhai Patel International Airport...,Sardar Vallabhbhai Patel International Airport...,Ahmedabad
4,Rajiv Gandhi International Airport (HYD),"Rajiv Gandhi International Airport, Shamshabad...",Hyderabad
5,Agartala Airport (IXA),"Agartala Airport, Agartala, Tripura 799009",Khowai
6,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Navi Mumbai
7,Pune International Airport (PNQ),"Pune International Airport, Lohegaon, Pune, Ma...",Pune
8,Vijayawada Airport (VGA),"Vijayawada Airport, Gannavaram, Andhra Pradesh...",Vijayawada
9,Gwalior Airport (GWL),"Gwalior Airport, Maharajpur, Gwalior, Madhya P...",Gwalior
10,Kempegowda International Airport (BLR),"Kempegowda International Airport, Devanahalli,...",Bengaluru
11,Lokpriya Gopinath Bordoloi International Airpo...,Lokpriya Gopinath Bordoloi International Airpo...,Guwahati
12,Bilaspur Airport (PAB),"Bilaspur Airport, Chakarbhata, Bilaspur, Chhat...",Bilaspur
13,Swami Vivekananda Airport (RPR),"Swami Vivekananda Airport, Ramchandi, Naya Rai...",Raipur
14,Puducherry Airport (PNY),"Puducherry Airport, Lawspet, Puducherry 605008",Puducherry
15,Sonari Airport (IXW),"Sonari Airport, Sonari, Jamshedpur, Jharkhand ...",Jamshedpur
16,Nashik International Airport (ISK),"Nashik International Airport, Ozar, Nashik, Ma...",Nashik
17,Mopa International Airport (GOX),"Mopa International Airport, Mopa, Pernem, Goa ...",Mopa
18,Prayagraj Airport (IXD),"Prayagraj Airport, Bamrauli, Prayagraj, Uttar ...",Prayagraj
19,Vadodara Airport (BDQ),"Vadodara Airport, Harni Road, Vadodara, Gujara...",Vadodara
20,Ludhiana Airport (LUH),"Ludhiana Airport, Sahnewal, Ludhiana, Punjab 1...",Ludhiana
21,Raigarh Airport (None),"Raigarh Airport, Kondatarai, Raigarh, Chhattis...",Raigarh
22,Chennai International Airport (MAA),"Chennai International Airport, GST Road, Meena...",Chennai
23,Biju Patnaik International Airport (BBI),"Biju Patnaik International Airport, Airport Ro...",Puri
24,Tirupati Airport (TIR),"Tirupati Airport, Renigunta, Andhra Pradesh 51...",Tirupati
25,Dehradun Airport (DED),"Dehradun Airport, Jolly Grant, Dehradun, Uttar...",Dehradun
26,Sheikh ul-Alam International Airport (SXR),"Sheikh ul-Alam International Airport, Aerodrom...",Srinagar
27,Indira Gandhi International Airport (DEL),"Indira Gandhi International Airport, New Delhi...",Delhi NCR
28,Donyi Polo Airport (HGI),"Donyi Polo Airport, Hollongi, Itanagar, Arunac...",Itanagar
29,Lal Bahadur Shastri International Airport (VNS),"Lal Bahadur Shastri International Airport, Bab...",Varanasi
30,Rupsi Airport (RUP),"Rupsi Airport, Rupsi, Assam 783372",Dhubri
31,Netaji Subhas Chandra Bose International Airpo...,Netaji Subhas Chandra Bose International Airpo...,Kolkata
32,Pakyong Airport (PYG),"Pakyong Airport, Pakyong, Sikkim 737106",Gangtok
33,Shillong Airport (SHL),"Shillong Airport, Umroi, Meghalaya 793103",Shillong
34,Sri Guru Ram Dass Jee International Airport (ATQ),"Sri Guru Ram Dass Jee International Airport, A...",Amritsar
35,Raja Bhoj Airport (BHO),"Raja Bhoj Airport, Gandhi Nagar, Bhopal, Madhy...",Bhopal
36,Jaipur International Airport (JAI),"Jaipur International Airport, Airport Road, Sa...",Jaipur
37,Kullu–Manali Airport (KUU),"Kullu–Manali Airport, Bhuntar, Kullu, Himachal...",Kullu-Manali
38,Ayodhya Airport (under construction),"Ayodhya Airport, Ayodhya, Uttar Pradesh 224123",Ayodhya
39,Biju Patnaik International Airport (BBI),"Biju Patnaik International Airport, Airport Ro...",Bhubaneswar
40,Trivandrum International Airport (TRV),"Trivandrum International Airport, Vallakkadavu...",Thiruvananthapuram
41,Kota Airport (KTU),"Kota Airport, Aerodrome Circle, Kota, Rajastha...",Kota
42,Surat Airport (STV),"Surat Airport, Dumas Road, Surat, Gujarat 395007",Surat
43,Maharana Pratap Airport (UDR),"Maharana Pratap Airport, NH 76, Dabok, Udaipur...",Udaipur
44,Diu Airport (DIU),"Diu Airport, Diu, Daman and Diu 362520",Diu
45,Chandigarh International Airport (IXC),"Chandigarh International Airport, Mohali, Punj...",Chandigarh
46,Shimla Airport (SLV),"Shimla Airport, Jubbarhatti, Shimla, Himachal ...",Shimla
47,Imphal International Airport (IMF),"Imphal International Airport, Imphal, Manipur ...",Imphal
48,Hisar Airport (HSS),"Hisar Airport, Hisar, Haryana 125001",Hisar
49,Visakhapatnam Airport (VTZ),"Visakhapatnam Airport, NAD Junction, Visakhapa...",Visakhapatnam
50,Devi Ahilya Bai Holkar Airport (IDR),"Devi Ahilya Bai Holkar Airport, Indore, Madhya...",Indore
51,Mysore Airport (MYQ),"Mysore Airport, Mandakalli, Mysuru, Karnataka ...",Mysuru
52,Jay Prakash Narayan Airport (PAT),"Jay Prakash Narayan Airport, Sheikhpura, Patna...",Patna
53,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Mumbai

In [263]:
nearest_airport_addresses = [
    "Coimbatore International Airport, Avinashi Road, Peelamedu, Coimbatore, Tamil Nadu 641014",
    "Birsa Munda Airport, Hinoo, Ranchi, Jharkhand 834002",
    "Goa International Airport, Airport Road, Dabolim, Goa 403801",
    "Sardar Vallabhbhai Patel International Airport, Hansol, Ahmedabad, Gujarat 380003",
    "Rajiv Gandhi International Airport, Shamshabad, Hyderabad, Telangana 500409",
    "Agartala Airport, Agartala, Tripura 799009",
    "Chhatrapati Shivaji Maharaj International Airport, Sahar, Andheri East, Mumbai, Maharashtra 400099",
    "Pune International Airport, Lohegaon, Pune, Maharashtra 411032",
    "Vijayawada Airport, Gannavaram, Andhra Pradesh 521102",
    "Gwalior Airport, Maharajpur, Gwalior, Madhya Pradesh 474020",
    "Kempegowda International Airport, Devanahalli, Bengaluru, Karnataka 560300",
    "Lokpriya Gopinath Bordoloi International Airport, Borjhar, Guwahati, Assam 781015",
    "Bilaspur Airport, Chakarbhata, Bilaspur, Chhattisgarh 495220",
    "Swami Vivekananda Airport, Ramchandi, Naya Raipur, Chhattisgarh 492015",
    "Puducherry Airport, Lawspet, Puducherry 605008",
    "Sonari Airport, Sonari, Jamshedpur, Jharkhand 831011",
    "Nashik International Airport, Ozar, Nashik, Maharashtra 422221",
    "Mopa International Airport, Mopa, Pernem, Goa 403512",
    "Prayagraj Airport, Bamrauli, Prayagraj, Uttar Pradesh 211012",
    "Vadodara Airport, Harni Road, Vadodara, Gujarat 390022",
    "Ludhiana Airport, Sahnewal, Ludhiana, Punjab 141120",
    "Raigarh Airport, Kondatarai, Raigarh, Chhattisgarh 496001",
    "Chennai International Airport, GST Road, Meenambakkam, Chennai, Tamil Nadu 600027",
    "Biju Patnaik International Airport, Airport Road, Bhubaneswar, Odisha 751020",
    "Tirupati Airport, Renigunta, Andhra Pradesh 517520",
    "Dehradun Airport, Jolly Grant, Dehradun, Uttarakhand 248140",
    "Sheikh ul-Alam International Airport, Aerodrome Road, Srinagar, Jammu and Kashmir 190007",
    "Indira Gandhi International Airport, New Delhi, Delhi 110037",
    "Donyi Polo Airport, Hollongi, Itanagar, Arunachal Pradesh 791123",
    "Lal Bahadur Shastri International Airport, Babatpur, Varanasi, Uttar Pradesh 221006",
    "Rupsi Airport, Rupsi, Assam 783372",
    "Netaji Subhas Chandra Bose International Airport, Jessore Road, Dum Dum, Kolkata, West Bengal 700052",
    "Pakyong Airport, Pakyong, Sikkim 737106",
    "Shillong Airport, Umroi, Meghalaya 793103",
    "Sri Guru Ram Dass Jee International Airport, Ajnala Road, Amritsar, Punjab 143101",
    "Raja Bhoj Airport, Gandhi Nagar, Bhopal, Madhya Pradesh 462036",
    "Jaipur International Airport, Airport Road, Sanganer, Jaipur, Rajasthan 302029",
    "Kullu–Manali Airport, Bhuntar, Kullu, Himachal Pradesh 175125",
    "Ayodhya Airport, Ayodhya, Uttar Pradesh 224123",
    "Biju Patnaik International Airport, Airport Road, Bhubaneswar, Odisha 751020",
    "Trivandrum International Airport, Vallakkadavu, Thiruvananthapuram, Kerala 695008",
    "Kota Airport, Aerodrome Circle, Kota, Rajasthan 324007",
    "Surat Airport, Dumas Road, Surat, Gujarat 395007",
    "Maharana Pratap Airport, NH 76, Dabok, Udaipur, Rajasthan 313022",
    "Diu Airport, Diu, Daman and Diu 362520",
    "Chandigarh International Airport, Mohali, Punjab 160004",
    "Shimla Airport, Jubbarhatti, Shimla, Himachal Pradesh 171011",
    "Imphal International Airport, Imphal, Manipur 795140",
    "Hisar Airport, Hisar, Haryana 125001",
    "Visakhapatnam Airport, NAD Junction, Visakhapatnam, Andhra Pradesh 530009",
    "Devi Ahilya Bai Holkar Airport, Indore, Madhya Pradesh 452005",
    "Mysore Airport, Mandakalli, Mysuru, Karnataka 570008",
    "Jay Prakash Narayan Airport, Sheikhpura, Patna, Bihar 800014",
    "Chhatrapati Shivaji Maharaj International Airport, Sahar, Andheri East, Mumbai, Maharashtra 400099"
]

In [268]:

Location_Table = Location_Table.drop(columns={'ID'})

In [269]:
Location_Table['LocationID'] = range(1, len(Location_Table) + 1)
Location_Table

,Name,Address,City,LocationID
0,Coimbatore International Airport (CJB),"Coimbatore International Airport, Avinashi Roa...",Coimbatore,1
1,Birsa Munda Airport (IXR),"Birsa Munda Airport, Hinoo, Ranchi, Jharkhand ...",Ranchi,2
2,Goa International Airport (GOI),"Goa International Airport, Airport Road, Dabol...",Dabolim,3
3,Sardar Vallabhbhai Patel International Airport...,Sardar Vallabhbhai Patel International Airport...,Ahmedabad,4
4,Rajiv Gandhi International Airport (HYD),"Rajiv Gandhi International Airport, Shamshabad...",Hyderabad,5
5,Agartala Airport (IXA),"Agartala Airport, Agartala, Tripura 799009",Khowai,6
6,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Navi Mumbai,7
7,Pune International Airport (PNQ),"Pune International Airport, Lohegaon, Pune, Ma...",Pune,8
8,Vijayawada Airport (VGA),"Vijayawada Airport, Gannavaram, Andhra Pradesh...",Vijayawada,9
9,Gwalior Airport (GWL),"Gwalior Airport, Maharajpur, Gwalior, Madhya P...",Gwalior,10
10,Kempegowda International Airport (BLR),"Kempegowda International Airport, Devanahalli,...",Bengaluru,11
11,Lokpriya Gopinath Bordoloi International Airpo...,Lokpriya Gopinath Bordoloi International Airpo...,Guwahati,12
12,Bilaspur Airport (PAB),"Bilaspur Airport, Chakarbhata, Bilaspur, Chhat...",Bilaspur,13
13,Swami Vivekananda Airport (RPR),"Swami Vivekananda Airport, Ramchandi, Naya Rai...",Raipur,14
14,Puducherry Airport (PNY),"Puducherry Airport, Lawspet, Puducherry 605008",Puducherry,15
15,Sonari Airport (IXW),"Sonari Airport, Sonari, Jamshedpur, Jharkhand ...",Jamshedpur,16
16,Nashik International Airport (ISK),"Nashik International Airport, Ozar, Nashik, Ma...",Nashik,17
17,Mopa International Airport (GOX),"Mopa International Airport, Mopa, Pernem, Goa ...",Mopa,18
18,Prayagraj Airport (IXD),"Prayagraj Airport, Bamrauli, Prayagraj, Uttar ...",Prayagraj,19
19,Vadodara Airport (BDQ),"Vadodara Airport, Harni Road, Vadodara, Gujara...",Vadodara,20
20,Ludhiana Airport (LUH),"Ludhiana Airport, Sahnewal, Ludhiana, Punjab 1...",Ludhiana,21
21,Raigarh Airport (None),"Raigarh Airport, Kondatarai, Raigarh, Chhattis...",Raigarh,22
22,Chennai International Airport (MAA),"Chennai International Airport, GST Road, Meena...",Chennai,23
23,Biju Patnaik International Airport (BBI),"Biju Patnaik International Airport, Airport Ro...",Puri,24
24,Tirupati Airport (TIR),"Tirupati Airport, Renigunta, Andhra Pradesh 51...",Tirupati,25
25,Dehradun Airport (DED),"Dehradun Airport, Jolly Grant, Dehradun, Uttar...",Dehradun,26
26,Sheikh ul-Alam International Airport (SXR),"Sheikh ul-Alam International Airport, Aerodrom...",Srinagar,27
27,Indira Gandhi International Airport (DEL),"Indira Gandhi International Airport, New Delhi...",Delhi NCR,28
28,Donyi Polo Airport (HGI),"Donyi Polo Airport, Hollongi, Itanagar, Arunac...",Itanagar,29
29,Lal Bahadur Shastri International Airport (VNS),"Lal Bahadur Shastri International Airport, Bab...",Varanasi,30
30,Rupsi Airport (RUP),"Rupsi Airport, Rupsi, Assam 783372",Dhubri,31
31,Netaji Subhas Chandra Bose International Airpo...,Netaji Subhas Chandra Bose International Airpo...,Kolkata,32
32,Pakyong Airport (PYG),"Pakyong Airport, Pakyong, Sikkim 737106",Gangtok,33
33,Shillong Airport (SHL),"Shillong Airport, Umroi, Meghalaya 793103",Shillong,34
34,Sri Guru Ram Dass Jee International Airport (ATQ),"Sri Guru Ram Dass Jee International Airport, A...",Amritsar,35
35,Raja Bhoj Airport (BHO),"Raja Bhoj Airport, Gandhi Nagar, Bhopal, Madhy...",Bhopal,36
36,Jaipur International Airport (JAI),"Jaipur International Airport, Airport Road, Sa...",Jaipur,37
37,Kullu–Manali Airport (KUU),"Kullu–Manali Airport, Bhuntar, Kullu, Himachal...",Kullu-Manali,38
38,Ayodhya Airport (under construction),"Ayodhya Airport, Ayodhya, Uttar Pradesh 224123",Ayodhya,39
39,Biju Patnaik International Airport (BBI),"Biju Patnaik International Airport, Airport Ro...",Bhubaneswar,40
40,Trivandrum International Airport (TRV),"Trivandrum International Airport, Vallakkadavu...",Thiruvananthapuram,41
41,Kota Airport (KTU),"Kota Airport, Aerodrome Circle, Kota, Rajastha...",Kota,42
42,Surat Airport (STV),"Surat Airport, Dumas Road, Surat, Gujarat 395007",Surat,43
43,Maharana Pratap Airport (UDR),"Maharana Pratap Airport, NH 76, Dabok, Udaipur...",Udaipur,44
44,Diu Airport (DIU),"Diu Airport, Diu, Daman and Diu 362520",Diu,45
45,Chandigarh International Airport (IXC),"Chandigarh International Airport, Mohali, Punj...",Chandigarh,46
46,Shimla Airport (SLV),"Shimla Airport, Jubbarhatti, Shimla, Himachal ...",Shimla,47
47,Imphal International Airport (IMF),"Imphal International Airport, Imphal, Manipur ...",Imphal,48
48,Hisar Airport (HSS),"Hisar Airport, Hisar, Haryana 125001",Hisar,49
49,Visakhapatnam Airport (VTZ),"Visakhapatnam Airport, NAD Junction, Visakhapa...",Visakhapatnam,50
50,Devi Ahilya Bai Holkar Airport (IDR),"Devi Ahilya Bai Holkar Airport, Indore, Madhya...",Indore,51
51,Mysore Airport (MYQ),"Mysore Airport, Mandakalli, Mysuru, Karnataka ...",Mysuru,52
52,Jay Prakash Narayan Airport (PAT),"Jay Prakash Narayan Airport, Sheikhpura, Patna...",Patna,53
53,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Mumbai,54

In [270]:
column_order = ['LocationID', 'Name', 'Address', 'City']  # Example order
Location_Table = Location_Table[column_order]
Location_Table

,LocationID,Name,Address,City
0,1,Coimbatore International Airport (CJB),"Coimbatore International Airport, Avinashi Roa...",Coimbatore
1,2,Birsa Munda Airport (IXR),"Birsa Munda Airport, Hinoo, Ranchi, Jharkhand ...",Ranchi
2,3,Goa International Airport (GOI),"Goa International Airport, Airport Road, Dabol...",Dabolim
3,4,Sardar Vallabhbhai Patel International Airport...,Sardar Vallabhbhai Patel International Airport...,Ahmedabad
4,5,Rajiv Gandhi International Airport (HYD),"Rajiv Gandhi International Airport, Shamshabad...",Hyderabad
5,6,Agartala Airport (IXA),"Agartala Airport, Agartala, Tripura 799009",Khowai
6,7,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Navi Mumbai
7,8,Pune International Airport (PNQ),"Pune International Airport, Lohegaon, Pune, Ma...",Pune
8,9,Vijayawada Airport (VGA),"Vijayawada Airport, Gannavaram, Andhra Pradesh...",Vijayawada
9,10,Gwalior Airport (GWL),"Gwalior Airport, Maharajpur, Gwalior, Madhya P...",Gwalior
10,11,Kempegowda International Airport (BLR),"Kempegowda International Airport, Devanahalli,...",Bengaluru
11,12,Lokpriya Gopinath Bordoloi International Airpo...,Lokpriya Gopinath Bordoloi International Airpo...,Guwahati
12,13,Bilaspur Airport (PAB),"Bilaspur Airport, Chakarbhata, Bilaspur, Chhat...",Bilaspur
13,14,Swami Vivekananda Airport (RPR),"Swami Vivekananda Airport, Ramchandi, Naya Rai...",Raipur
14,15,Puducherry Airport (PNY),"Puducherry Airport, Lawspet, Puducherry 605008",Puducherry
15,16,Sonari Airport (IXW),"Sonari Airport, Sonari, Jamshedpur, Jharkhand ...",Jamshedpur
16,17,Nashik International Airport (ISK),"Nashik International Airport, Ozar, Nashik, Ma...",Nashik
17,18,Mopa International Airport (GOX),"Mopa International Airport, Mopa, Pernem, Goa ...",Mopa
18,19,Prayagraj Airport (IXD),"Prayagraj Airport, Bamrauli, Prayagraj, Uttar ...",Prayagraj
19,20,Vadodara Airport (BDQ),"Vadodara Airport, Harni Road, Vadodara, Gujara...",Vadodara
20,21,Ludhiana Airport (LUH),"Ludhiana Airport, Sahnewal, Ludhiana, Punjab 1...",Ludhiana
21,22,Raigarh Airport (None),"Raigarh Airport, Kondatarai, Raigarh, Chhattis...",Raigarh
22,23,Chennai International Airport (MAA),"Chennai International Airport, GST Road, Meena...",Chennai
23,24,Biju Patnaik International Airport (BBI),"Biju Patnaik International Airport, Airport Ro...",Puri
24,25,Tirupati Airport (TIR),"Tirupati Airport, Renigunta, Andhra Pradesh 51...",Tirupati
25,26,Dehradun Airport (DED),"Dehradun Airport, Jolly Grant, Dehradun, Uttar...",Dehradun
26,27,Sheikh ul-Alam International Airport (SXR),"Sheikh ul-Alam International Airport, Aerodrom...",Srinagar
27,28,Indira Gandhi International Airport (DEL),"Indira Gandhi International Airport, New Delhi...",Delhi NCR
28,29,Donyi Polo Airport (HGI),"Donyi Polo Airport, Hollongi, Itanagar, Arunac...",Itanagar
29,30,Lal Bahadur Shastri International Airport (VNS),"Lal Bahadur Shastri International Airport, Bab...",Varanasi
30,31,Rupsi Airport (RUP),"Rupsi Airport, Rupsi, Assam 783372",Dhubri
31,32,Netaji Subhas Chandra Bose International Airpo...,Netaji Subhas Chandra Bose International Airpo...,Kolkata
32,33,Pakyong Airport (PYG),"Pakyong Airport, Pakyong, Sikkim 737106",Gangtok
33,34,Shillong Airport (SHL),"Shillong Airport, Umroi, Meghalaya 793103",Shillong
34,35,Sri Guru Ram Dass Jee International Airport (ATQ),"Sri Guru Ram Dass Jee International Airport, A...",Amritsar
35,36,Raja Bhoj Airport (BHO),"Raja Bhoj Airport, Gandhi Nagar, Bhopal, Madhy...",Bhopal
36,37,Jaipur International Airport (JAI),"Jaipur International Airport, Airport Road, Sa...",Jaipur
37,38,Kullu–Manali Airport (KUU),"Kullu–Manali Airport, Bhuntar, Kullu, Himachal...",Kullu-Manali
38,39,Ayodhya Airport (under construction),"Ayodhya Airport, Ayodhya, Uttar Pradesh 224123",Ayodhya
39,40,Biju Patnaik International Airport (BBI),"Biju Patnaik International Airport, Airport Ro...",Bhubaneswar
40,41,Trivandrum International Airport (TRV),"Trivandrum International Airport, Vallakkadavu...",Thiruvananthapuram
41,42,Kota Airport (KTU),"Kota Airport, Aerodrome Circle, Kota, Rajastha...",Kota
42,43,Surat Airport (STV),"Surat Airport, Dumas Road, Surat, Gujarat 395007",Surat
43,44,Maharana Pratap Airport (UDR),"Maharana Pratap Airport, NH 76, Dabok, Udaipur...",Udaipur
44,45,Diu Airport (DIU),"Diu Airport, Diu, Daman and Diu 362520",Diu
45,46,Chandigarh International Airport (IXC),"Chandigarh International Airport, Mohali, Punj...",Chandigarh
46,47,Shimla Airport (SLV),"Shimla Airport, Jubbarhatti, Shimla, Himachal ...",Shimla
47,48,Imphal International Airport (IMF),"Imphal International Airport, Imphal, Manipur ...",Imphal
48,49,Hisar Airport (HSS),"Hisar Airport, Hisar, Haryana 125001",Hisar
49,50,Visakhapatnam Airport (VTZ),"Visakhapatnam Airport, NAD Junction, Visakhapa...",Visakhapatnam
50,51,Devi Ahilya Bai Holkar Airport (IDR),"Devi Ahilya Bai Holkar Airport, Indore, Madhya...",Indore
51,52,Mysore Airport (MYQ),"Mysore Airport, Mandakalli, Mysuru, Karnataka ...",Mysuru
52,53,Jay Prakash Narayan Airport (PAT),"Jay Prakash Narayan Airport, Sheikhpura, Patna...",Patna
53,54,Chhatrapati Shivaji Maharaj International Airp...,Chhatrapati Shivaji Maharaj International Airp...,Mumbai

In [271]:
Location_Table.to_excel('Location_Table.xlsx',index=False)
from IPython.display import FileLink
FileLink('Location_Table.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\Location_Table.xlsx

In [273]:
RoundTripHetvi = pd.read_csv('RoundTripHetvi.csv')
RoundTripHetvi

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price,flight_number
0,503,4,firstClass,Air India,2021-03-25 00:00:00,Itanagar,Surat,2204.62,02:26,00:56,03:22,12220.60,AI2544
1,590,4,economic,SpiceJet,2021-04-02 00:00:00,Surat,Itanagar,2204.62,02:26,04:18,06:44,7562.36,SG5951
2,1479,13,economic,IndiGo,2020-09-07 00:00:00,Bengaluru,Visakhapatnam,797.17,00:53,01:41,02:34,3110.76,6E406
3,1507,13,economic,SpiceJet,2020-09-15 00:00:00,Visakhapatnam,Bengaluru,797.17,00:53,08:07,09:00,3330.76,SG2322V
4,1666,15,firstClass,Air India,2019-11-28 00:00:00,Chandigarh,Navi Mumbai,1355.13,01:30,11:12,12:42,7763.15,AI4743
...,...,...,...,...,...,...,...,...,...,...,...,...,...
568,133540,1315,economic,Akasa Air,2021-06-17 00:00:00,Delhi NCR,Shimla,271.89,00:18,13:48,14:06,1456.17,QP4135
569,134586,1323,premium,Air India,2021-12-16 00:00:00,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84,AI5473
570,134613,1323,firstClass,Akasa Air,2021-12-30 00:00:00,Dehradun,Hyderabad,1439.54,01:35,22:00,23:35,8153.95,QP1329I
571,135670,1335,firstClass,IndiGo,2019-11-28 00:00:00,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25,6E1467L
572,135799,1335,premium,Akasa Air,2019-12-06 00:00:00,Kota,Raigarh,3289.60,03:39,22:43,02:22,13033.86,QP2867P

In [277]:
RoundTripHetvi['flight_number'].nunique()

558

In [278]:
OneWayHetvi = pd.read_csv('OneWayHetvi.csv')
OneWayHetvi

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,flight_number
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,G84279
1,2,0,firstClass,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,6E4357O
2,7,0,economic,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,AI3905
3,11,0,premium,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,SG2659K
4,13,0,firstClass,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,G83184
...,...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,AI5405C
39975,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,QP2071
39976,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,QP589J
39977,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,6E4801N
39978,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,6E4290X

In [279]:
def calculate_flight_price(row):
    base_price = 500  # Base price for any flight

    # Adjusting price based on flight type
    type_multiplier = {
        "economic": 1.0,
        "premium": 1.3,
        "business": 1.6,
        "firstClass": 2.0
    }
    
    flight_type = row["flightType"]
    multiplier = type_multiplier.get(flight_type, 1.0)
    
    # Distance-based cost (per km charge)
    distance_cost = row["Flight Distance (km)"] * 2
    
    # Duration-based cost (per minute charge)
    duration_cost = convert_duration_to_minutes(row["Flight Duration (hh:mm)"]) * 1.5
    
    # Airline surcharge (mock values for different airlines)
    agency_surcharge = {
        "IndiGo": 100,
        "SpiceJet": 120,
        "GoAir": 110,
        "Air India": 150
    }
    
    agency_cost = agency_surcharge.get(row["Flight_agency"], 100)
    
    # Departure time effect (peak hours: 6 AM - 10 AM & 6 PM - 10 PM increase price)
    departure_hour = int(row["Departure Time"].split(":")[0])
    peak_hour_surcharge = 200 if (6 <= departure_hour < 10 or 18 <= departure_hour < 22) else 0

    # Final price calculation
    price = base_price + (distance_cost + duration_cost) * multiplier + agency_cost + peak_hour_surcharge
    return round(price, 2)

# Load the dataset


# Apply function to calculate price
OneWayHetvi["Calculated_Flight_Price"] = OneWayHetvi.apply(calculate_flight_price, axis=1)

OneWayHetvi

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,flight_number,Calculated_Flight_Price
0,0,0,firstClass,GoAir,26/09/2019,Coimbatore,Visakhapatnam,1000.71,01:06,03:59,05:05,G84279,4810.84
1,2,0,firstClass,IndiGo,10/10/2019,Ranchi,Shillong,709.80,00:47,01:02,01:49,6E4357O,3580.20
2,7,0,economic,Air India,14/11/2019,Dabolim,Ranchi,1493.33,01:39,00:15,01:54,AI3905,3785.16
3,11,0,premium,SpiceJet,12/12/2019,Ahmedabad,Raigarh,1117.55,01:14,17:35,18:49,SG2659K,3669.93
4,13,0,firstClass,GoAir,26/12/2019,Hyderabad,Kolkata,1184.11,01:18,18:18,19:36,G83184,5780.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,premium,Air India,18/06/2020,Indore,Dabolim,842.49,00:56,04:28,05:24,AI5405C,2949.67
39975,135939,1339,premium,Akasa Air,25/06/2020,Ahmedabad,Shillong,1974.07,02:11,13:37,15:48,QP2071,5988.03
39976,135940,1339,firstClass,Akasa Air,07/02/2020,Prayagraj,Visakhapatnam,874.72,00:58,17:27,18:25,QP589J,4272.88
39977,135941,1339,firstClass,IndiGo,07/09/2020,Surat,Dabolim,655.18,00:43,00:46,01:29,6E4801N,3349.72
39978,135942,1339,economic,IndiGo,16/07/2020,Bhopal,Prayagraj,511.46,00:34,12:14,12:48,6E4290X,1673.92

In [280]:
OneWayHetvi.to_excel('OneWayHetvii.xlsx',index=False)
from IPython.display import FileLink
FileLink('OneWayHetvii.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\OneWayHetvii.xlsx

In [282]:
OneWayHetvii = OneWayHetvi.copy()
OneWayHetvii["Departure_date"] = pd.to_datetime(OneWayHetvii["Departure_date"], format="%d/%m/%Y")

OneWayHetvii["Departure Time"] = pd.to_timedelta(OneWayHetvii["Departure Time"] + ":00")

OneWayHetvii["Departure DateTime"] = OneWayHetvii["Departure_date"] + OneWayHetvii["Departure Time"]

OneWayHetvii

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,flight_number,Calculated_Flight_Price,Departure DateTime
0,0,0,firstClass,GoAir,2019-09-26,Coimbatore,Visakhapatnam,1000.71,01:06,0 days 03:59:00,05:05,G84279,4810.84,2019-09-26 03:59:00
1,2,0,firstClass,IndiGo,2019-10-10,Ranchi,Shillong,709.80,00:47,0 days 01:02:00,01:49,6E4357O,3580.20,2019-10-10 01:02:00
2,7,0,economic,Air India,2019-11-14,Dabolim,Ranchi,1493.33,01:39,0 days 00:15:00,01:54,AI3905,3785.16,2019-11-14 00:15:00
3,11,0,premium,SpiceJet,2019-12-12,Ahmedabad,Raigarh,1117.55,01:14,0 days 17:35:00,18:49,SG2659K,3669.93,2019-12-12 17:35:00
4,13,0,firstClass,GoAir,2019-12-26,Hyderabad,Kolkata,1184.11,01:18,0 days 18:18:00,19:36,G83184,5780.44,2019-12-26 18:18:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39974,135938,1339,premium,Air India,2020-06-18,Indore,Dabolim,842.49,00:56,0 days 04:28:00,05:24,AI5405C,2949.67,2020-06-18 04:28:00
39975,135939,1339,premium,Akasa Air,2020-06-25,Ahmedabad,Shillong,1974.07,02:11,0 days 13:37:00,15:48,QP2071,5988.03,2020-06-25 13:37:00
39976,135940,1339,firstClass,Akasa Air,2020-02-07,Prayagraj,Visakhapatnam,874.72,00:58,0 days 17:27:00,18:25,QP589J,4272.88,2020-02-07 17:27:00
39977,135941,1339,firstClass,IndiGo,2020-09-07,Surat,Dabolim,655.18,00:43,0 days 00:46:00,01:29,6E4801N,3349.72,2020-09-07 00:46:00
39978,135942,1339,economic,IndiGo,2020-07-16,Bhopal,Prayagraj,511.46,00:34,0 days 12:14:00,12:48,6E4290X,1673.92,2020-07-16 12:14:00

In [283]:
RoundTripHetvii = RoundTripHetvi.copy()

In [286]:
RoundTripHetvii["Departure_date"] = pd.to_datetime(RoundTripHetvii["Departure_date"], errors="coerce")

# Convert Departure Time to timedelta format
RoundTripHetvii["Departure Time"] = pd.to_timedelta(RoundTripHetvii["Departure Time"] + ":00")

# Create new column for combined Departure DateTime
RoundTripHetvii["Departure DateTime"] = RoundTripHetvii["Departure_date"] + RoundTripHetvii["Departure Time"]

In [287]:
RoundTripHetvii

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price,flight_number,Departure DateTime
0,503,4,firstClass,Air India,2021-03-25,Itanagar,Surat,2204.62,02:26,0 days 00:56:00,03:22,12220.60,AI2544,2021-03-25 00:56:00
1,590,4,economic,SpiceJet,2021-04-02,Surat,Itanagar,2204.62,02:26,0 days 04:18:00,06:44,7562.36,SG5951,2021-04-02 04:18:00
2,1479,13,economic,IndiGo,2020-09-07,Bengaluru,Visakhapatnam,797.17,00:53,0 days 01:41:00,02:34,3110.76,6E406,2020-09-07 01:41:00
3,1507,13,economic,SpiceJet,2020-09-15,Visakhapatnam,Bengaluru,797.17,00:53,0 days 08:07:00,09:00,3330.76,SG2322V,2020-09-15 08:07:00
4,1666,15,firstClass,Air India,2019-11-28,Chandigarh,Navi Mumbai,1355.13,01:30,0 days 11:12:00,12:42,7763.15,AI4743,2019-11-28 11:12:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
568,133540,1315,economic,Akasa Air,2021-06-17,Delhi NCR,Shimla,271.89,00:18,0 days 13:48:00,14:06,1456.17,QP4135,2021-06-17 13:48:00
569,134586,1323,premium,Air India,2021-12-16,Hyderabad,Dehradun,1439.54,01:35,0 days 19:57:00,21:32,6288.84,AI5473,2021-12-16 19:57:00
570,134613,1323,firstClass,Akasa Air,2021-12-30,Dehradun,Hyderabad,1439.54,01:35,0 days 22:00:00,23:35,8153.95,QP1329I,2021-12-30 22:00:00
571,135670,1335,firstClass,IndiGo,2019-11-28,Raigarh,Kota,3289.60,03:39,0 days 10:34:00,14:13,17869.25,6E1467L,2019-11-28 10:34:00
572,135799,1335,premium,Akasa Air,2019-12-06,Kota,Raigarh,3289.60,03:39,0 days 22:43:00,02:22,13033.86,QP2867P,2019-12-06 22:43:00

In [288]:
RoundTripHetvi

,travelCode,User_ID,flightType,Flight_agency,Departure_date,Departure,Arrival,Flight Distance (km),Flight Duration (hh:mm),Departure Time,Arrival Time,Calculated_Flight_Price,flight_number
0,503,4,firstClass,Air India,2021-03-25 00:00:00,Itanagar,Surat,2204.62,02:26,00:56,03:22,12220.60,AI2544
1,590,4,economic,SpiceJet,2021-04-02 00:00:00,Surat,Itanagar,2204.62,02:26,04:18,06:44,7562.36,SG5951
2,1479,13,economic,IndiGo,2020-09-07 00:00:00,Bengaluru,Visakhapatnam,797.17,00:53,01:41,02:34,3110.76,6E406
3,1507,13,economic,SpiceJet,2020-09-15 00:00:00,Visakhapatnam,Bengaluru,797.17,00:53,08:07,09:00,3330.76,SG2322V
4,1666,15,firstClass,Air India,2019-11-28 00:00:00,Chandigarh,Navi Mumbai,1355.13,01:30,11:12,12:42,7763.15,AI4743
...,...,...,...,...,...,...,...,...,...,...,...,...,...
568,133540,1315,economic,Akasa Air,2021-06-17 00:00:00,Delhi NCR,Shimla,271.89,00:18,13:48,14:06,1456.17,QP4135
569,134586,1323,premium,Air India,2021-12-16 00:00:00,Hyderabad,Dehradun,1439.54,01:35,19:57,21:32,6288.84,AI5473
570,134613,1323,firstClass,Akasa Air,2021-12-30 00:00:00,Dehradun,Hyderabad,1439.54,01:35,22:00,23:35,8153.95,QP1329I
571,135670,1335,firstClass,IndiGo,2019-11-28 00:00:00,Raigarh,Kota,3289.60,03:39,10:34,14:13,17869.25,6E1467L
572,135799,1335,premium,Akasa Air,2019-12-06 00:00:00,Kota,Raigarh,3289.60,03:39,22:43,02:22,13033.86,QP2867P

In [289]:
OneWayHetvii.to_excel('OneWay_by_Hetvi.xlsx',index=False)
from IPython.display import FileLink
FileLink('OneWay_by_Hetvi.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\OneWay_by_Hetvi.xlsx

In [290]:
RoundTripHetvii.to_excel('RoundTrip_by_Hetvi.xlsx',index=False)
from IPython.display import FileLink
FileLink('RoundTrip_by_Hetvi.xlsx')

C:\Users\SURAJ\Desktop\Dataset\notebooks\RoundTrip_by_Hetvi.xlsx